#include "CharacterMotor.h"
#include "UniformGravity.h"
#include "RadicalGravity.h"
#include "SceneSerialization.h"
#include "SceneFingerprint.h"
#include "RuntimeWorld.h"
#include "ResourceManager.h"
#include "InputSystem.h"
#include "Prefab.h"
#include "WorldState.h"
#include <chrono>
#include <filesystem>
#include <fstream>
#include <cstdio>
int checks=0,failures=0;
void Check(bool ok,const char* label){++checks;if(!ok)++failures;std::printf("%s %s\n",ok?"PASS":"FAIL",label);}
bool Near(glm::vec3 a,glm::vec3 b,float eps=.02f){return glm::length(a-b)<eps;}
void Tick(CharacterMotor& m,PhysicsWorld& p,const GravityField& g,int n){for(int i=0;i<n;++i){p.Step(1.f/60);m.Step(p,g,1.f/60);}}
int main(){
 UniformGravity g({0,-9.81f,0}),zero({0,0,0});PhysicsWorld p;p.Init();auto floor=p.CreateStaticBox({0,-.5,0},{20,.5,20},.6,0);
 CharacterMotor m;m.Reset({0,.92,0},{1,0,0,0});Tick(m,p,g,3);Check(m.result.supported&&m.result.support.id==floor.id&&Near(m.result.supportNormal,{0,1,0}),"flat support / true geometry normal");
 auto q=glm::angleAxis(.8f,glm::normalize(glm::vec3(1,2,3)));PhysicsWorld rotated;rotated.Init();rotated.CreateStaticBox(q*glm::vec3(0,-.5,0),q,{20,.5,20},.6,0);UniformGravity rg(q*glm::vec3(0,-9.81f,0));CharacterMotor r;r.Reset(q*glm::vec3(0,.92,0),q);Tick(r,rotated,rg,3);Check(r.result.supported&&Near(glm::inverse(q)*r.position,m.position)&&Near(r.result.supportNormal,q*glm::vec3(0,1,0)),"arbitrarily rotated equivalent support");
 p.CreateStaticBox({2,2,0},{.2,2,4},.6,0);m.velocity={4,0,2};Tick(m,p,g,45);Check(m.position.x<1.51f&&m.position.z>.5f&&m.result.velocity.x<.01f,"wall sweep and slide resolves inward velocity");
 p.CreateStaticBox({0,2,2},{4,2,.2},.6,0);for(int i=0;i<30;++i){m.velocity={4,0,4};Tick(m,p,g,1);}Check(m.position.x<1.51f&&m.position.z<1.51f,"corner remains outside both walls");
 m.Reset({0,.5,0},{1,0,0,0});Tick(m,p,g,1);Check(m.position.y>.9f&&m.result.recovered,"signed-depth penetration recovery");
 PhysicsWorld stairs;stairs.Init();stairs.CreateStaticBox({0,-.5,0},{10,.5,10},.6,0);stairs.CreateStaticBox({1,.2,0},{.5,.2,2},.6,0);CharacterMotor step;step.Reset({0,.92,0},{1,0,0,0});Tick(step,stairs,g,2);
 for(int i=0;i<30;++i){step.velocity={3,0,0};Tick(step,stairs,g,1);}std::printf("STEP %.6f %.6f %.6f support=%d\n",step.position.x,step.position.y,step.position.z,step.result.supported);Check(step.position.x>1&&step.position.y>1.28f,"step up reuses proven up-forward-down sweeps");
 for(int i=0;i<25;++i){step.velocity={3,0,0};Tick(step,stairs,g,1);}std::printf("DOWN x=%g y=%g supported=%d\n",step.position.x,step.position.y,step.result.supported);Check(step.result.supported&&step.position.y<1.f,"step down/support following");
 PhysicsWorld slope;slope.Init();auto tilt=glm::angleAxis(glm::radians(65.f),glm::vec3(0,0,1));slope.CreateStaticBox({0,0,0},tilt,{4,.2,4},.6,0);CharacterMotor steep;steep.Reset(tilt*glm::vec3(0,1.12,0),{1,0,0,0});Tick(steep,slope,g,1);Check(!steep.result.supported,"steep contact is not accepted as support");
 PhysicsWorld platform;platform.Init();auto support=platform.CreateDynamicBox({0,-.25,0},{2,.25,2},500,.6,0);CharacterMotor passenger;passenger.Reset({1,.92,0},{1,0,0,0});Tick(passenger,platform,zero,1);platform.SetLinearVelocity(support,{1,0,0});platform.SetAngularVelocity(support,{0,1,0});auto old=passenger.position;Tick(passenger,platform,zero,1);
 Check(passenger.result.supported&&passenger.position.x>old.x&&passenger.position.z<old.z,"translating/rotating actual support carry");
 Check(passenger.result.supportVelocity.x>.9f&&passenger.result.supportVelocity.z<-.9f,"support point velocity includes angular motion");
 auto inherited=passenger.velocity;passenger.velocity+=glm::vec3(0,3,0);Tick(passenger,platform,zero,1);Check(!passenger.result.supported&&Near(glm::vec3(passenger.velocity.x,0,passenger.velocity.z),glm::vec3(inherited.x,0,inherited.z)),"departing retains support world momentum");
 platform.DestroyBody(support);auto replacement=platform.CreateDynamicBox({0,-.25,0},{2,.25,2},500,.6,0);Tick(passenger,platform,zero,1);Check(replacement.id!=support.id&&passenger.result.support.id!=support.id,"destroyed support generation never aliases reused slot");
 CharacterMotor air;air.Reset({0,5,0},q);air.velocity={1,2,3};Tick(air,platform,zero,1);Check(Near(air.result.displacement,glm::vec3(1,2,3)/60.f,.0001f)&&Near(air.orientation*glm::vec3(0,1,0),q*glm::vec3(0,1,0)),"zero-gravity airborne motion retains explicit orientation");
 PhysicsWorld planet;planet.Init();planet.CreateStaticSphere({0,0,0},10,.6,0);RadicalGravity radial({0,0,0},9.81f);CharacterMotor orbital;orbital.Reset({0,10.92f,0},{1,0,0,0});Tick(orbital,planet,radial,2);for(int i=0;i<60;++i){auto up=orbital.orientation*glm::vec3(0,1,0);orbital.velocity=glm::normalize(glm::cross(glm::vec3(0,0,1),up))*2.f;Tick(orbital,planet,radial,1);}std::printf("RADIAL %.6f %.6f %.6f support=%d r=%.6f\n",orbital.position.x,orbital.position.y,orbital.position.z,orbital.result.supported,glm::length(orbital.position));Check(orbital.result.supported&&glm::length(orbital.position)>10.85f&&std::abs(orbital.position.x)>1,"radial gravity tangent movement follows real sphere");
 PhysicsWorld push;push.Init();auto body=push.CreateDynamicBox({1,1,0},{.4,.4,.4},1000,.6,0);CharacterMotor driver;driver.settings.gravityScale=0;driver.settings.maxPushImpulse=2;driver.Reset({0,1,0},{1,0,0,0});driver.velocity={5,0,0};Tick(driver,push,zero,10);Check(push.GetLinearVelocity(body).x>0&&push.GetLinearVelocity(body).x<=.021f,"dynamic push is finite bounded impulse, not velocity seeding");
 driver.Reset({0,1,0},{1,0,0,0});driver.settings.collisionMask=0;driver.velocity={5,0,0};Tick(driver,push,zero,20);Check(driver.position.x>1.5f,"M39 bilateral mask excludes body");
 driver.settings.collisionMask=kAllCategories;driver.filter.ignoredBodies={body};driver.Reset({0,1,0},{1,0,0,0});driver.velocity={5,0,0};Tick(driver,push,zero,20);Check(driver.position.x>1.5f,"generation-aware ignored body");
 driver.filter.ignoredBodies.clear();push.SetBodyTags(body,CategoryBit(1));driver.settings.excludedTags=CategoryBit(1);driver.Reset({0,1,0},{1,0,0,0});driver.velocity={5,0,0};Tick(driver,push,zero,20);Check(driver.position.x>1.5f,"project tag exclusion uses same authoritative body tags");
 Scene scene;auto id=scene.CreateObject("motor").id;scene.Find(id)->characterMotor=CharacterMotorSettings{};scene.Find(id)->transform.position={0,2,0};scene.Find(id)->render=SceneRenderComponent{};
 std::string error,text,hash,changed;Scene copy;SaveSceneToString(scene,text);Check(LoadSceneFromString(text,copy,error)&&ScenesEqual(scene,copy),"motor component serialization round-trip");ComputeSceneFingerprint(scene,hash,error);copy.Find(id)->characterMotor->stepHeight=.3f;ComputeSceneFingerprint(copy,changed,error);Check(changed!=hash,"motor authored settings change strict baseline fingerprint");
 RuntimeWorld world;Check(world.Build(scene,nullptr,error),"headless motor world needs no PlayerController/input/camera");auto* a=world.RuntimeCharacter(id);a->settings.gravityScale=0;world.SetCharacterSettings(id,a->settings);a->velocity={1,0,0};world.UpdateCharacters(1.f/60);Check(world.RuntimeDefinition(id)->transform.position.x>0&&world.RuntimeCharacter(id)->result.displacement.x>0,"ordinary runtime entity publishes resolved motion");
 world.SetCharacterSettings(id,CharacterMotorSettings{});world.SetCharacterSettings(id,CharacterMotorSettings{false});auto position=world.RuntimeDefinition(id)->transform.position;world.UpdateCharacters(1.f/60);Check(world.RuntimeDefinition(id)->transform.position==position&&!world.RuntimeCharacter(id)->result.supported,"disable retains pose and clears support");world.RestoreAuthoredState();Check(Near(world.RuntimeCharacter(id)->position,{0,2,0})&&world.RuntimeCharacter(id)->velocity==glm::vec3(0),"authored reset discards stale motor state");world.Destroy();Check(!world.RuntimeCharacter(id),"world destruction invalidates character access");
 namespace fs=std::filesystem;auto root=fs::absolute("build/m49-focused");fs::remove_all(root);fs::create_directories(root/"Assets");std::ofstream(root/"Assets/motor.js")<<R"JS(import {input,world} from 'judas';
 export default class {constructor({entity}){this.entity=entity;this.state={};}fixedUpdate(){const m=this.entity.character;m.configure({gravityScale:0,collisionLayer:"Default",collisionMask:["Default"],requiredTags:[],excludedTags:[]});m.velocity={x:input.axis('move_x')+1,y:0,z:0};m.accelerate({x:0,y:1,z:0});this.state.safe=!!m;this.state.support=m.state.supportEntity;this.state.gravity=m.gravity;} })JS";
 AssetDatabase db;db.Scan(root.string(),(root/"Assets").string());AssetRecord script,prefab;Check(db.Track((root/"Assets/motor.js").string(),script,error),"registered script asset");scene.Find(id)->scripts.push_back({1,script.id,true,"{}"});SaveSceneToFile(scene,(root/"Assets/motor.judasprefab").string(),error);db.Track((root/"Assets/motor.judasprefab").string(),prefab,error);ResourceManager resources(nullptr,&db);Check(world.Build(scene,&resources,error),"scriptable world build");InputSystem input;input.SetPhysical("key:D",1);input.BeginFixedStep();world.FixedScripts(&input,1.f/60);world.UpdateCharacters(1.f/60);Check(world.Scripts()->Diagnostics().empty()&&world.RuntimeCharacter(id)->position.x>.03f,"JS fixedUpdate reads logical input and drives motor");
 SceneTransform placement;placement.position={5,2,0};auto spawned=world.SpawnPrefab(prefab.id,placement,error);Check(spawned&&world.RuntimeCharacter(spawned),"prefab runtime spawn contains normal motor");world.FixedScripts(&input,1.f/60);world.UpdateCharacters(1.f/60);Check(world.RuntimeCharacter(id)!=world.RuntimeCharacter(spawned)&&world.RuntimeCharacter(spawned)->position.x>5,"independent motor/script instances");Check(world.DestroyHierarchy(spawned,error)&&!world.RuntimeCharacter(spawned),"destroy hierarchy safely retires motor entity");world.UpdateCharacters(1.f/60);world.Destroy();Check(world.Build(scene,&resources,error)&&world.RuntimeCharacter(id)->velocity==glm::vec3(0),"reload starts fresh runtime state");world.Destroy();
 for(int count:{1,10,100}){PhysicsWorld perf;perf.Init();perf.CreateStaticBox({0,-.5,0},{200,.5,200},.6,0);std::vector<CharacterMotor> motors(count);for(int i=0;i<count;++i)motors[i].Reset({float(i*2),.92f,0},{1,0,0,0});auto start=std::chrono::steady_clock::now();for(int f=0;f<120;++f){perf.Step(1.f/60);for(auto& motor:motors)motor.Step(perf,g,1.f/60);}std::printf("PERF %d motors whole_motor_batch_us %.3f samples=120\n",count,std::chrono::duration<double,std::micro>(std::chrono::steady_clock::now()-start).count()/120);}
 std::printf("SUMMARY %d checks %d failures\n",checks,failures);return failures?1:0;
}
