#include "CollisionAsset.h"
#include "CollisionGeometry.h"
#include "PhysicsWorld.h"
#include "CharacterMotor.h"
#include "UniformGravity.h"
#include "RadicalGravity.h"
#include "FluidHydrostatics.h"
#include "CollisionAuthoring.h"
#include "Deformable.h"
#include <glm/gtc/matrix_transform.hpp>
#include <fstream>
#include <chrono>
#include <filesystem>
#include <iostream>
#include <stdexcept>
#include <glm/gtc/quaternion.hpp>
namespace {
unsigned checks=0;
void require(bool condition,const char* message){++checks;if(!condition)throw std::runtime_error(message);}
MeshData cube(){MeshData m;for(int z:{-1,1})for(int y:{-1,1})for(int x:{-1,1}){MeshVertex v;v.position={float(x),float(y),float(z)};m.vertices.push_back(v);}m.indices={0,4,6,0,6,2,1,3,7,1,7,5,0,1,5,0,5,4,2,6,7,2,7,3,0,2,3,0,3,1,4,5,7,4,7,6};return m;}
}
int main(){try{
 std::string error;CollisionAsset asset;CollisionCookSettings settings;settings.convex=true;
 if(!CookCollision(cube(),settings,asset,error))throw std::runtime_error(error);require(true,"convex cook");require(std::abs(asset.volume-8)<1e-8,"cube convex volume");require(glm::length(asset.centerOfMass)<1e-8,"cube convex COM");require(std::abs(asset.unitInertia[0][0]-16./3)<1e-8,"analytic cube inertia");
 require(SaveCollisionAsset("/tmp/judas-m64-test.judascollision",asset,error),error.c_str());CollisionAsset loaded;require(LoadCollisionAsset("/tmp/judas-m64-test.judascollision",loaded,error),error.c_str());require(loaded.faces.size()==asset.faces.size(),"cook roundtrip");
 auto shared=std::make_shared<CollisionAsset>(asset);Shape hull=Shape::Cooked(shared,"fixture");RigidBody body;body.position={0,0,0};body.orientation={1,0,0,0};auto pose=PrimitiveAt(hull,body,0);auto point=PointGeometry({0,0,0},pose);require(point.valid&&point.contains&&std::abs(point.gap-1)<1e-8,"inside nearest surface distinct from contains");
 PhysicsWorld world;world.Init();auto h=world.CreateShape(hull,{{0,0,0},{1,0,0,0}},false,0,.5,0);auto hit=world.Raycast({0,0,5},{0,0,-1},10);require(hit.hit&&hit.body.id==h.id&&std::abs(hit.distance-4)<1e-5,"hull ray exact face");auto sphere=world.SphereCast({0,0,5},.5,{0,0,-1},10);require(sphere.hit&&std::abs(sphere.distance-3.5)<1e-4,"hull sphere cast");
 settings.convex=false;MeshData plane;for(auto p:{glm::vec3(-10,0,-10),glm::vec3(10,0,-10),glm::vec3(10,0,10),glm::vec3(-10,0,10)}){MeshVertex v;v.position=p;plane.vertices.push_back(v);}plane.indices={0,2,1,0,3,2};if(!CookCollision(plane,settings,loaded,error))throw std::runtime_error(error);require(true,"plane cook");require(!loaded.faces[0].active[0],"coplanar diagonal inactive");Shape mesh=Shape::Cooked(std::make_shared<CollisionAsset>(loaded),"plane");auto floor=world.CreateShape(mesh,{{0,-3,0},{1,0,0,0}},false,0,.5,0);auto ray=world.Raycast({5,0,5},{0,-1,0},10);require(ray.hit&&ray.body.id==floor.id&&std::abs(ray.distance-3)<1e-5,"mesh ray real triangle");require(!world.Raycast({5,-4,5},{0,1,0},.5).hit,"one sided mesh backface");
 auto touchingRay=world.Raycast({5,-3,5},{1,0,0},0);require(touchingRay.hit&&touchingRay.initialOverlap&&touchingRay.distance==0,"zero distance tangent ray detects existing mesh touch");
 auto dynamic=world.CreateShape(hull,{{5,-2.1f,0},{1,0,0,0}},true,2,.5,0);world.ApplyLinearAcceleration(dynamic,{0,-9.8,0},1.f/60);world.Step(1.f/60);require(world.LastStepContactCount()>0,"dynamic hull contact mesh");

 require(asset.polygons.size()==6&&asset.edges.size()==12,"cooked cube has six full contact faces, twelve physical edges");
 CollisionAsset failed;auto malformed=cube();malformed.indices[0]=999;require(!CookCollision(malformed,settings,failed,error),"out of range source diagnosed");malformed=cube();malformed.vertices[0].position.x=INFINITY;require(!CookCollision(malformed,settings,failed,error),"nonfinite source rejected");
 auto mirrored=settings;mirrored.transform[0][0]=-1;require(!CookCollision(cube(),mirrored,failed,error),"mirrored cook rejected");auto sheared=settings;sheared.transform[1][0]=.2;require(!CookCollision(cube(),sheared,failed,error),"sheared cook rejected");
 auto scaled=settings;scaled.convex=true;scaled.transform[0][0]=2;scaled.transform[1][1]=3;scaled.transform[2][2]=4;scaled.transform[3][0]=5;require(CookCollision(cube(),scaled,failed,error)&&std::abs(failed.volume-192)<1e-6&&std::abs(failed.centerOfMass.x-5)<1e-6,"positive nonuniform baked scale / offset COM");
 auto offsetHull=Shape::Cooked(std::make_shared<CollisionAsset>(failed),"offset");PhysicsWorld asymmetric;asymmetric.Init();auto off=asymmetric.CreateShape(offsetHull,{{7,8,9},{1,0,0,0}},true,3,0,0);require(glm::length(asymmetric.GetTransform(off).position-glm::vec3(7,8,9))<1e-5,"authored pivot survives COM simulation");asymmetric.ApplyImpulseAtPoint(off,{0,1,0},{14,8,9});require(asymmetric.GetAngularVelocity(off).z>0,"off centre impulse uses true hull COM/inertia");asymmetric.Step(.01);auto path=asymmetric.GetBodyMotionSegments(off);require(!path.empty(),"asymmetric resolved motion recorded");auto endpoint=PhysicsWorld::EvaluateBodyMotionSegment(path.back(),path.back().end);require(glm::length(endpoint.position-asymmetric.GetTransform(off).position)<1e-4,"COM rotation preserves pivot motion trajectory");
 bool rejected=false;try{world.CreateShape(mesh,{},true,1,0,0);}catch(const std::invalid_argument&){rejected=true;}require(rejected,"dynamic concavity rejected");require(!world.SetBodySensor(floor,true),"open mesh volume sensor rejected");
 auto cp=world.ClosestPoint({0,0,0},2);require(cp.hit&&cp.body.id==h.id&&cp.contains&&std::abs(cp.distance-1)<1e-5,"nearest surface distinct from convex occupied point");require(!world.ClosestPoint({100,100,100},1).hit,"bounded closest-point miss");PhysicsQueryFilter ignore;ignore.ignoredBodies={h};require(!world.Raycast({0,0,5},{0,0,-1},5,ignore).hit,"new geometry ignored safe handle");world.SetBodyEnabled(h,false);require(!world.Raycast({0,0,5},{0,0,-1},5).hit,"disabled cooked collider rejected");world.SetBodyEnabled(h,true);world.SetCollisionFilter(h,3,kAllCategories);PhysicsQueryFilter layers;layers.includeLayers=CategoryBit(2);require(!world.Raycast({0,0,5},{0,0,-1},5,layers).hit,"M39 layer filtering applies to hull");world.SetBodyTags(h,CategoryBit(2));PhysicsQueryFilter tags;tags.excludedTags=CategoryBit(2);require(!world.Raycast({0,0,5},{0,0,-1},5,tags).hit,"M39 tags filter cooked queries");
 auto capsule=world.CapsuleCast({{0,0,5},{1,0,0,0}},.25,.5,{0,0,-1},10);require(capsule.hit&&std::abs(capsule.distance-3.75)<1e-4,"capsule hull analytic sweep");auto castBox=world.BoxCast({{0,0,5},{1,0,0,0}},{.25,.25,.25},{0,0,-1},10);require(castBox.hit&&std::abs(castBox.distance-3.75)<1e-4,"fixed box hull analytic sweep");auto overlap=world.SphereCast({0,0,0},.1,{0,0,1},0);require(overlap.hit&&overlap.initialOverlap&&overlap.distance==0,"zero distance initial overlap contract");
 PhysicsWorld seam;seam.Init();auto floorAsset=std::make_shared<CollisionAsset>(loaded);auto planeShape=Shape::Cooked(floorAsset,"plane");seam.CreateShape(planeShape,{},false,0,0,0);
 for(auto shape:{Shape::Box({.4,.2,.3}),Shape::Sphere(.2),hull}){double height=shape.type==ShapeType::ConvexHull?1: .2;auto body=seam.CreateShape(shape,{{-3,float(height+.001),0},{1,0,0,0}},true,1,0,0);seam.SetLinearVelocity(body,{4,0,0});double minimum=4,maximumImpulse=0,penetration=0;
  for(int i=0;i<90;++i){seam.ApplyLinearAcceleration(body,{0,-9.81,0},1.f/60);seam.Step(1.f/60);minimum=std::min(minimum,double(seam.GetLinearVelocity(body).x));for(auto& contact:seam.LastStepContacts()){penetration=std::max(penetration,double(contact.penetration));}for(auto& event:seam.LastStepTouchEvents())if(event.impulseAvailable)maximumImpulse=std::max(maximumImpulse,double(event.normalImpulse));}
  std::cout<<"SEAM shape="<<int(shape.type)<<" minimum_speed="<<minimum<<" max_impulse="<<maximumImpulse<<" penetration="<<penetration<<"\n";
  require(minimum>3.8,"no artificial flat diagonal barrier / speed loss");require(seam.GetTransform(body).position.x>2.8,"crosses flat diagonal without assistance");require(std::abs(seam.GetTransform(body).position.y-height)<.04,"stable rest height across shared edge");seam.DestroyBody(body);
 }
 auto alternate=plane;alternate.indices={0,3,1,1,3,2};CollisionAsset alternateAsset;require(CookCollision(alternate,settings,alternateAsset,error),"alternative diagonal cook");PhysicsWorld alt;alt.Init();alt.CreateShape(Shape::Cooked(std::make_shared<CollisionAsset>(alternateAsset),"alternate"),{},false,0,0,0);auto bx=alt.CreateDynamicBox({-3,.201,0},{.4,.2,.3},1,0,0);alt.SetLinearVelocity(bx,{4,0,0});for(int i=0;i<90;++i){alt.ApplyLinearAcceleration(bx,{0,-9.81,0},1.f/60);alt.Step(1.f/60);}require(std::abs(alt.GetLinearVelocity(bx).x-4)<.05,"retriangulation preserves flat slide");
 CompoundBox child;child.localCenter={1,0,0};child.halfExtents={1,.2,.3};child.rotation=glm::angleAxis(.7f,glm::vec3(0,0,1));child.key=17;CompoundBox ball;ball.type=ShapeType::Sphere;ball.radius=.3;ball.localCenter={-1,0,0};ball.key=22;CompoundBox convex;convex.type=ShapeType::ConvexHull;convex.asset=shared;convex.assetId="fixture";convex.localCenter={0,2,0};convex.key=31;auto compound=Shape::Compound({child,ball,convex});auto mass=ShapeMassProperties(compound);require(mass.volume>8&&glm::determinant(mass.inertia)>0,"oriented compound real mass tensor");PhysicsWorld parts;parts.Init();auto partBody=parts.CreateShape(compound,{{10,0,0},{1,0,0,0}},true,2,0,0);auto partHit=parts.Raycast({11,0,5},{0,0,-1},10);require(partHit.hit&&partHit.childKey==17,"rotated child ray returns stable key");auto pc=parts.ClosestPoint({9,0,.5},2);require(pc.hit&&pc.childKey==22&&std::abs(pc.distance-.2)<1e-5,"sphere child closestPoint exact");auto bounds=ShapeAabb(compound,{10,0,0},{1,0,0,0});require(bounds.max.y>2.99&&bounds.min.x<8.71,"compound bounds contain rotated and convex children");
 auto orientation=glm::angleAxis(.8f,glm::normalize(glm::vec3(1,2,3)));PhysicsWorld oblique;oblique.Init();oblique.CreateShape(planeShape,{{0,0,0},orientation},false,0,0,0);auto result=oblique.Raycast(orientation*glm::vec3(2,3,2),orientation*glm::vec3(0,-1,0),10);require(result.hit&&glm::length(result.normal-orientation*glm::vec3(0,1,0))<1e-5&&std::abs(result.distance-3)<1e-5,"arbitrary orientation same physical query");CharacterMotor motor;motor.Reset(orientation*glm::vec3(-2,.92,0),orientation);UniformGravity gravity(orientation*glm::vec3(0,-9.81,0));for(int i=0;i<90;++i){motor.velocity=orientation*glm::vec3(2,0,0);oblique.Step(1.f/60);motor.Step(oblique,gravity,1.f/60);}require(motor.result.supported&&glm::length(motor.result.supportNormal-orientation*glm::vec3(0,1,0))<.01,"CharacterMotor supports rotated real mesh");require((glm::inverse(orientation)*motor.position).x>.8,"motor crosses internal diagonal");
 auto fluid=MakeCompoundFluidVolume({child},4);require(std::abs(fluid.totalVolume-8*1*.2*.3)<1e-6&&fluid.solidBoxes[0].rotation==child.rotation,"rotated primitive liquid volume retained");rejected=false;try{MakeCompoundFluidVolume({convex},4);}catch(...){rejected=true;}require(rejected,"hull liquid displacement explicitly unsupported");
 world.DestroyBody(h);auto replacement=world.CreateShape(hull,{},false,0,0,0);require(replacement.id!=h.id&&!world.IsBodyEnabled(h),"destroyed cooked handle cannot alias reused slot");
 // Import/cook transactions, independent analytic tetrahedron and topology policy.
 CollisionCookSettings convexSettings;convexSettings.convex=true;
 MeshData tetra;for(auto p:{glm::vec3(0,0,0),glm::vec3(1,0,0),glm::vec3(0,1,0),glm::vec3(0,0,1)}){MeshVertex v;v.position=p;tetra.vertices.push_back(v);}tetra.indices={0,2,1,0,1,3,0,3,2,1,2,3};CollisionAsset tetraAsset;
 require(CookCollision(tetra,convexSettings,tetraAsset,error)&&std::abs(tetraAsset.volume-1./6)<1e-8&&glm::length(tetraAsset.centerOfMass-glm::dvec3(.25))<1e-8,"analytic tetra volume / COM");require(std::abs(tetraAsset.unitInertia[0][0]-.0125)<1e-8,"analytic tetra COM inertia");
 auto dirty=plane;dirty.indices.insert(dirty.indices.end(),{0,2,1,0,0,0});CollisionAsset cleaned;require(CookCollision(dirty,settings,cleaned,error)&&cleaned.faces.size()==2&&!cleaned.warnings.empty()&&cleaned.faces[0].source==0,"duplicate/degenerate cleanup and source feature map");
 auto junction=plane;MeshVertex extra;extra.position={0,0,-10};junction.vertices.push_back(extra);junction.indices.insert(junction.indices.end(),{0,4,3});require(!CookCollision(junction,settings,cleaned,error),"ambiguous T-junction diagnosed");
 const std::string source="/tmp/judas-m64-source.obj",cooked="/tmp/judas-m64-source.judascollision";
 {std::ofstream f(source);f<<"o chosen\nv 0 0 0\nv 2 0 0\nv 0 0 2\nf 1 3 2\no separate\nv 20 0 0\nv 22 0 0\nv 20 0 2\nf 4 6 5\n";}
 require(CookCollisionFile(source,"original-test",settings,cooked,cleaned,error)&&cleaned.maximum.x==2,"explicit OBJ primitive selection");require(!CollisionAssetStale(cleaned,source,error),"current source/settings cook identity");
 std::string accepted;{std::ifstream f(cooked);accepted.assign(std::istreambuf_iterator<char>(f),{});}auto absent=settings;absent.primitive=99;require(!CookCollisionFile(source,"original-test",absent,cooked,cleaned,error),"invalid source selection cook fails");std::string preserved;{std::ifstream f(cooked);preserved.assign(std::istreambuf_iterator<char>(f),{});}require(preserved==accepted,"failed replacement preserves previous good asset byte for byte");
 {std::ofstream f(source,std::ios::app);f<<"# change\n";}require(CollisionAssetStale(cleaned,source,error),"source change diagnosed stale");
 // Actual embedded GLB source selection preserves node TRS and excludes other nodes.
 std::string json=R"({"asset":{"version":"2.0"},"buffers":[{"byteLength":44}],"bufferViews":[{"buffer":0,"byteOffset":0,"byteLength":36},{"buffer":0,"byteOffset":36,"byteLength":6}],"accessors":[{"bufferView":0,"componentType":5126,"count":3,"type":"VEC3","min":[0,0,0],"max":[1,0,1]},{"bufferView":1,"componentType":5123,"count":3,"type":"SCALAR"}],"meshes":[{"primitives":[{"attributes":{"POSITION":0},"indices":1}]}],"nodes":[{"mesh":0,"translation":[4,0,0],"scale":[2,1,3]},{"mesh":0,"translation":[20,0,0]}],"scenes":[{"nodes":[0,1]}],"scene":0})";
 while(json.size()%4)json+=' ';const std::string glb="/tmp/judas-m64-selected.glb";
 {std::ofstream file(glb,std::ios::binary);auto word=[&](uint32_t n){for(unsigned k=0;k<4;++k)file.put(char(n>>(8*k)));};word(0x46546c67);word(2);word(12+8+json.size()+8+44);word(json.size());word(0x4e4f534a);file.write(json.data(),json.size());word(44);word(0x004e4942);float vertices[]={0,0,0,1,0,0,0,0,1};file.write(reinterpret_cast<char*>(vertices),36);uint16_t indices[]={0,2,1,0};file.write(reinterpret_cast<char*>(indices),8);}
 CollisionAsset glbCook;require(CookCollisionFile(glb,"GLB-test",settings,"/tmp/judas-m64-glb.judascollision",glbCook,error)&&glbCook.vertices.size()==3&&std::abs(glbCook.minimum.x-4)<1e-6&&std::abs(glbCook.maximum.x-6)<1e-6&&std::abs(glbCook.maximum.z-3)<1e-6,"GLB selected node nonuniform TRS is baked once");
 auto secondNode=settings;secondNode.primitive=1;require(CookCollisionFile(glb,"GLB-test",secondNode,"/tmp/judas-m64-glb2.judascollision",glbCook,error)&&glbCook.minimum.x==20&&glbCook.maximum.x==21,"GLB explicit selection does not concatenate the whole file");
 // Two disconnected patches: a nearby parallel patch is NOT a separating plane
 // for a later intersected patch. This independently fixes a concave sweep miss.
 MeshData disconnected;for(auto p:{glm::vec3(-5,0,-2),glm::vec3(5,0,-2),glm::vec3(0,0,2),glm::vec3(3,.2,-2),glm::vec3(3,4,-2),glm::vec3(3,.2,2)}){MeshVertex v;v.position=p;disconnected.vertices.push_back(v);}disconnected.indices={0,2,1,3,5,4};auto twoSided=settings;twoSided.twoSided=true;CollisionAsset patches;require(CookCollision(disconnected,twoSided,patches,error),"disconnected patches with physical boundaries");PhysicsWorld concave;concave.Init();concave.CreateShape(Shape::Cooked(std::make_shared<CollisionAsset>(patches),"patches"),{},false,0,0,0);auto patchHit=concave.SphereCast({0,1,0},.2,{1,0,0},5);require(patchHit.hit&&std::abs(patchHit.distance-2.8)<1e-4,"nonapproaching near sheet cannot mask farther shape-cast hit");
 auto edge=world.ClosestPoint({0,-3,0},4);require(edge.hit,"open sheet nearest geometry bounded");
 auto buildCurve=[&](unsigned segments){MeshData m;auto vertex=[&](double x,double y,double z){MeshVertex v;v.position={x,y,z};m.vertices.push_back(v);};vertex(-12,0,-2);vertex(-12,0,2);for(unsigned i=0;i<=segments;++i){double a=1.5707963267948966*i/segments;vertex(6*std::sin(a),6*(1-std::cos(a)),-2);vertex(6*std::sin(a),6*(1-std::cos(a)),2);}for(unsigned i=0;i<=segments;++i){unsigned a=2*i;m.indices.insert(m.indices.end(),{a,a+1,a+3,a,a+3,a+2});}return m;};
 for(unsigned resolution:{16u,32u,64u})for(unsigned kind=0;kind<3;++kind){CollisionAsset curve;require(CookCollision(buildCurve(resolution),settings,curve,error),"curved physical source cooks");PhysicsWorld ride;ride.Init();ride.CreateShape(Shape::Cooked(std::make_shared<CollisionAsset>(curve),"curve"),{},false,0,0,0);Shape shape=kind==0?Shape::Box({.3,.15,.2}):kind==1?Shape::Sphere(.2):hull;double height=kind==0?.151:kind==1?.201:1.001;auto moving=ride.CreateShape(shape,{{-2,float(height),0},{1,0,0,0}},true,1,0,0);ride.SetLinearVelocity(moving,{8,0,0});double progress=-2,maxImpulse=0,maxPen=0,initialEnergy=32+9.81*height,endEnergy=0;for(unsigned step=0;step<180;++step){ride.ApplyLinearAcceleration(moving,{0,-9.81,0},1.f/60);ride.Step(1.f/60);auto t=ride.GetTransform(moving);progress=std::max(progress,double(t.position.x));for(auto& event:ride.LastStepTouchEvents())if(event.impulseAvailable)maxImpulse=std::max(maxImpulse,double(event.normalImpulse));for(auto& contact:ride.LastStepContacts())maxPen=std::max(maxPen,double(contact.penetration));auto v=ride.GetLinearVelocity(moving),w=ride.GetAngularVelocity(moving);endEnergy=.5*glm::dot(v,v)+.5*glm::dot(w,ride.GetInertiaWorld(moving)*w)+9.81*t.position.y;}
 std::cout<<"CURVE unassisted resolution="<<resolution<<" kind="<<kind<<" max_progress="<<progress<<" max_impulse="<<maxImpulse<<" penetration="<<maxPen<<" initial_energy="<<initialEnergy<<" final_energy="<<endEnergy<<"\n";require(progress>1,"unassisted primitive progresses into real curve without seam wall");require(maxPen<.15,"curved contact bounded penetration");}
 // M62 uses the same rigid-contact seam; no hidden primitive fallback.
 PhysicsWorld clothWorld;clothWorld.Init();clothWorld.CreateShape(planeShape,{},false,0,0,0);DeformableInstance drape;auto sheet=std::make_shared<DeformableAsset>(MakeDeformableSheet(4,4,2,2));DeformableSettings clothSettings;clothSettings.selfContact=false;auto placement=glm::translate(glm::dmat4(1),glm::dvec3(0,1,0))*glm::mat4_cast(glm::angleAxis(-1.5707963267948966,glm::dvec3(1,0,0)));drape.Initialize(sheet,clothSettings,placement,1);UniformGravity down({0,-9.81,0});unsigned clothContacts=0;for(int i=0;i<90;++i){drape.Step(1./60,clothWorld,down,{});clothContacts+=drape.stats.contacts;}require(drape.error.empty()&&clothContacts>0&&drape.Minimum().y>-.1,"M62 cloth contacts actual mesh without fallback boxes");
 DeformableInstance soft;auto solid=std::make_shared<DeformableAsset>(MakeDeformableBlock({2,2,2},{1,1,1}));soft.Initialize(solid,clothSettings,glm::translate(glm::dmat4(1),glm::dvec3(3,2,0)),2);unsigned softContacts=0;for(int i=0;i<90;++i){soft.Step(1./60,clothWorld,down,{});softContacts+=soft.stats.contacts;}require(soft.error.empty()&&softContacts>0&&soft.Minimum().y>-.1,"M62 soft block contacts actual mesh");
 // Radial field has no geometry-type branch; equivalent local tangent placement.
 PhysicsWorld radialWorld;radialWorld.Init();radialWorld.CreateShape(planeShape,{{0,50,0},orientation},false,0,0,0);auto radialBody=radialWorld.CreateShape(hull,{{0,52,0},orientation},true,1,0,0);RadicalGravity radial({0,0,0},9.81);for(int i=0;i<60;++i){radialWorld.ApplyLinearAcceleration(radialBody,radial.Sample(radialWorld.GetTransform(radialBody).position),1.f/60);radialWorld.Step(1.f/60);}require(radialWorld.GetTransform(radialBody).position.y>48,"hull responds to actual radial gravity and oblique surface");
 auto hugePose=PrimitiveAt(planeShape,RigidBody{},0);const glm::dvec3 fixedOrigin(1e12,-2e12,3e12);hugePose.parentPosition=glm::vec3(fixedOrigin-fixedOrigin);auto precise=PointGeometry(fixedOrigin+glm::dvec3(2,3,2)-fixedOrigin,hugePose,4);require(precise.valid&&std::abs(precise.gap-3)<1e-8,"geometry subtracts precise large local origin before evaluation");
 SceneObject incompatible;incompatible.body=SceneBodyComponent{};incompatible.body->shape=SceneShape::ConvexHull;require(!ValidateCollisionFluid(incompatible,true,error),"unsupported PBF hull loading rejected explicitly");incompatible.body->fluidCavities.push_back({});require(!ValidateCollisionFluid(incompatible,false,error),"hull does not invent a cavity/volume proxy");


 // Events are body-pair observations, independent of triangle/manifold churn.
 PhysicsWorld pairs;pairs.Init();auto pairFloor=pairs.CreateShape(planeShape,{},false,0,0,0);
 auto pairBody=pairs.CreateDynamicBox({-3,.201,0},{.3,.2,.3},1,0,0);pairs.SetLinearVelocity(pairBody,{4,0,0});
 unsigned enters=0,stays=0,exits=0;for(int i=0;i<90;++i){pairs.ApplyLinearAcceleration(pairBody,{0,-9.81,0},1.f/60);pairs.Step(1.f/60);
  for(const auto& e:pairs.LastStepTouchEvents()){enters+=e.phase==PhysicsWorld::TouchPhase::Enter;stays+=e.phase==PhysicsWorld::TouchPhase::Stay;exits+=e.phase==PhysicsWorld::TouchPhase::Exit;}
 }
 require(enters==1&&stays==89&&exits==0,"M42 one enter/stay pair across mesh triangles");
 pairs.DestroyBody(pairFloor);pairs.Step(1.f/60);require(pairs.LastStepTouchEvents().size()==1&&pairs.LastStepTouchEvents()[0].phase==PhysicsWorld::TouchPhase::Exit,"mesh destruction emits one exit, no ghost pair");
 PhysicsWorld stack;stack.Init();stack.CreateShape(planeShape,{},false,0,.5,0);std::vector<BodyHandle> stacked;
 for(int i=0;i<3;++i)stacked.push_back(stack.CreateShape(hull,{{0,1.f+2.01f*i,0},{1,0,0,0}},true,1,.5,0));
 for(int i=0;i<180;++i){for(auto b:stacked)stack.ApplyLinearAcceleration(b,{0,-9.81,0},1.f/60);stack.Step(1.f/60);}
 for(int i=0;i<3;++i){auto t=stack.GetTransform(stacked[i]);require(std::abs(t.position.y-(1+2*i))<.15&&std::abs(t.position.x)<.1,"modest hull stack rests with normal contacts");}
 PhysicsWorld fast;fast.Init();fast.CreateShape(planeShape,{},false,0,0,0);auto fastBody=fast.CreateDynamicBox({0,5,0},{.25,.25,.25},1,0,0);fast.SetLinearVelocity(fastBody,{0,-100,0});fast.Step(.1f);
 require(fast.GetTransform(fastBody).position.y>=.24,"bounded fast box approach uses existing impact path for mesh");
 require(std::abs(parts.GetBodySupportDistance(partBody,{0,1,0})-float(bounds.max.y-mass.center.y))<1e-4,"compound directional support includes hull vertices and COM");
 CollisionAsset cubeMesh;require(CookCollision(cube(),settings,cubeMesh,error),"closed triangle fixture cooks with physical convex corners");PhysicsWorld corner;corner.Init();corner.CreateShape(Shape::Cooked(std::make_shared<CollisionAsset>(cubeMesh),"cube surface"),{},false,0,0,0);
 auto cornerHit=corner.SphereCast({3,3,3},.2,glm::normalize(glm::vec3(-1)),5);require(cornerHit.hit&&std::abs(cornerHit.distance-(2*std::sqrt(3.)-.2))<2e-4,"real convex corner retains geometric sweep barrier");
 auto corrupt=*floorAsset;corrupt.faces[0].adjacent[0]=-1;require(!SaveCollisionAsset("/tmp/judas-m64-corrupt.judascollision",corrupt,error),"malformed adjacency cannot replace accepted cook");
 // Two-sided geometry is invariant under reversing authored winding. Backside
 // convex/concave crease classification must follow the side being contacted.
 MeshData valley;for(auto p:{glm::vec3(-2,1,-2),glm::vec3(-2,1,2),glm::vec3(0,0,-2),glm::vec3(0,0,2),glm::vec3(2,1,-2),glm::vec3(2,1,2)}){MeshVertex v;v.position=p;valley.vertices.push_back(v);}valley.indices={0,1,3,0,3,2,2,3,5,2,5,4};
 auto reversedValley=valley;for(unsigned i=0;i<reversedValley.indices.size();i+=3)std::swap(reversedValley.indices[i+1],reversedValley.indices[i+2]);CollisionAsset frontValley,backValley;
 require(CookCollision(valley,twoSided,frontValley,error)&&CookCollision(reversedValley,twoSided,backValley,error),"two-sided crease winding fixtures cook");
 PrimitivePose valleyA,valleyB,under;valleyA.shape=Shape::Cooked(std::make_shared<CollisionAsset>(frontValley),"valley");valleyB.shape=Shape::Cooked(std::make_shared<CollisionAsset>(backValley),"reversed valley");under.shape=Shape::Box({.4,.2,.3});under.parentPosition={-.4,-.2,0};under.parentOrientation=glm::angleAxis(.2f,glm::normalize(glm::vec3(1,2,3)));
 auto frontContact=CookedContacts(under,valleyA,.001),backContact=CookedContacts(under,valleyB,.001);
 require(frontContact.count&&backContact.count,"two-sided backside crease produces real contact");
 require(glm::length(frontContact.points[0].preciseNormal-backContact.points[0].preciseNormal)<1e-7,"reversed winding preserves backside physical crease normal");
 require(std::abs(frontContact.points[0].signedSeparation-backContact.points[0].signedSeparation)<1e-7,"reversed winding preserves backside separation");
 // Large mesh locality and primitive reference: each workload uses the same query count.
 MeshData grid;constexpr unsigned n=81;for(unsigned z=0;z<n;++z)for(unsigned x=0;x<n;++x){MeshVertex v;v.position={float(x)-40,0,float(z)-40};grid.vertices.push_back(v);}
 for(unsigned z=0;z<n-1;++z)for(unsigned x=0;x<n-1;++x){unsigned a=z*n+x;grid.indices.insert(grid.indices.end(),{a,a+n,a+1,a+1,a+n,a+n+1});}
 auto begin=std::chrono::steady_clock::now();CollisionAsset large;require(CookCollision(grid,settings,large,error),"representative 12800 triangle source cooks");double cookMs=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-begin).count();require(SaveCollisionAsset("/tmp/judas-m64-large.judascollision",large,error),"large cook safely saved");begin=std::chrono::steady_clock::now();CollisionAsset cold;require(LoadCollisionAsset("/tmp/judas-m64-large.judascollision",cold,error),"cold BVH decode without geometry recooking");double loadMs=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-begin).count();
 std::cout<<"COOK triangles="<<large.faces.size()<<" nodes="<<large.nodes.size()<<" ms="<<cookMs<<" cold_load_ms="<<loadMs<<" bytes="<<std::filesystem::file_size("/tmp/judas-m64-large.judascollision")<<"\n";
 for(bool useMesh:{false,true}){PhysicsWorld measured;measured.Init();if(useMesh)measured.CreateShape(Shape::Cooked(std::make_shared<CollisionAsset>(large),"large"),{},false,0,0,0);else measured.CreateStaticBox({0,-.1,0},{1,0,0,0},{40,.1,40},0,0);
  for(unsigned kind=0;kind<5;++kind){ResetCollisionGeometryStats();begin=std::chrono::steady_clock::now();unsigned found=0;for(unsigned i=0;i<200;++i){glm::vec3 q(-35+float(i%20)*3.5f,3,-35+float(i/20)*7.f);
   if(kind==0)found+=measured.Raycast(q,{0,-1,0},6).hit;
   if(kind==1)found+=measured.SphereCast(q,.2,{0,-1,0},6).hit;
   if(kind==2)found+=measured.CapsuleCast({q,{1,0,0,0}},.2,.4,{0,-1,0},6).hit;
   if(kind==3)found+=measured.BoxCast({q,{1,0,0,0}},{.2,.4,.2},{0,-1,0},6).hit;
   if(kind==4)found+=measured.ClosestPoint(q,4).hit;
  }auto counters=GetCollisionGeometryStats();double us=std::chrono::duration<double,std::micro>(std::chrono::steady_clock::now()-begin).count();require(found==200,"representative workload returns real geometry for every expected query");if(useMesh)require(counters.triangles<200*large.faces.size()/10,"BVH rejects most park triangles rather than full scan");std::cout<<"QUERY mesh="<<useMesh<<" kind="<<kind<<" count=200 us="<<us<<" nodes="<<counters.nodes<<" triangles="<<counters.triangles<<"\n";}
 }

 // Modest rigid workload, matching primitive-only reference and rotated compounds.
 for(unsigned variant=0;variant<3;++variant){PhysicsWorld run;run.Init();if(variant==0)run.CreateStaticBox({0,-.1,0},{1,0,0,0},{40,.1,40},.5,0);else run.CreateShape(Shape::Cooked(std::make_shared<CollisionAsset>(large),"large"),{},false,0,.5,0);
  std::vector<BodyHandle> bodies;for(int i=0;i<12;++i)bodies.push_back(run.CreateShape(variant==2?compound:Shape::Box({.3,.2,.3}),{{float(i*6-33),variant==2?4.f:.201f,0},{1,0,0,0}},true,2,.5,0));
  std::vector<double> times;for(unsigned i=0;i<180;++i){for(auto b:bodies)run.ApplyLinearAcceleration(b,{0,-9.81,0},1.f/60);auto t=std::chrono::steady_clock::now();run.Step(1.f/60);if(i>30)times.push_back(std::chrono::duration<double,std::micro>(std::chrono::steady_clock::now()-t).count());}
  std::sort(times.begin(),times.end());std::cout<<"CONTACT_PERF variant="<<variant<<" bodies=12 median_us="<<times[times.size()/2]<<" p95_us="<<times[times.size()*95/100]<<" max_us="<<times.back()<<"\n";
 }

 ResetCollisionGeometryStats();auto start=std::chrono::steady_clock::now();for(int i=0;i<1000;++i)world.Raycast({5,0,5},{0,-1,0},10);auto stats=GetCollisionGeometryStats();std::cout<<"PERF 1000 rays us="<<std::chrono::duration<double,std::micro>(std::chrono::steady_clock::now()-start).count()<<" BVH_nodes="<<stats.nodes<<" triangles="<<stats.triangles<<"\n";
 std::cout<<checks<<" collision geometry checks passed\n";return 0;
 }catch(const std::exception& e){std::cerr<<"FAIL after "<<checks<<": "<<e.what()<<"\n";return 1;}}
