#include "Deformable.h"
#include "UniformGravity.h"
#include "PerformanceProfiler.h"
#include <chrono>
#include <cstdlib>
#include <new>
#include <cstdio>
#include <algorithm>
static size_t allocations=0,allocatedBytes=0;static bool measuring=false;
void* operator new(size_t n){if(measuring){++allocations;allocatedBytes+=n;}if(auto p=std::malloc(n))return p;throw std::bad_alloc();}
void operator delete(void* p)noexcept{std::free(p);}void operator delete(void* p,size_t)noexcept{std::free(p);}
int main(){std::setvbuf(stdout,nullptr,_IOLBF,0);PhysicsWorld physics;physics.Init();UniformGravity zero({0,0,0});auto sheet=std::make_shared<DeformableAsset>(MakeDeformableSheet(33,45,4,5,1));auto solid=std::make_shared<DeformableAsset>(MakeDeformableBlock({4,3,4},{2,1,2}));DeformableSettings cfg;cfg.substeps=4;cfg.iterations=4;cfg.material.damping=.7;cfg.material.thickness=.02;DeformableInstance cloth,block;cloth.Initialize(sheet,cfg,glm::dmat4(1),1);cfg.material.density=80;block.Initialize(solid,cfg,glm::translate(glm::dmat4(1),glm::dvec3(10,0,0)),2);auto& profiler=PerformanceProfiler::Get();profiler.Enable(true);
 for(int mode=0;mode<3;++mode){std::vector<double> times;times.reserve(120);allocations=allocatedBytes=0;for(int step=0;step<35;++step){profiler.BeginFrame("M62 CPU benchmark");if(mode==0)cloth.Force("",{.1,0,.1});auto start=std::chrono::steady_clock::now();measuring=step>=15;physics.Step(1.f/60);if(mode!=2){cloth.Step(1./60,physics,zero,{});block.Step(1./60,physics,zero,{});}measuring=false;double ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();if(step>=15)times.push_back(ms);profiler.EndFrame();}std::sort(times.begin(),times.end());double slowest=0;std::string phase;auto snap=profiler.Snapshot(profiler.FrameId()-1);for(auto& scope:snap.scopes){double ms=double(scope.end-scope.start)*1e-6;if(ms>slowest&&std::string_view(scope.name).find("Deformable")!=std::string_view::npos){phase=scope.name.c_str();slowest=ms;}}std::map<std::string,double> phases;for(auto& s:snap.scopes)phases[s.name.c_str()]+=double(s.end-s.start)*1e-6;for(auto& [name,time]:phases)if(name.find("Deformable")!=std::string::npos)std::printf("PHASE %s %.6fms\n",name.c_str(),time);std::printf("PERFORMANCE mode=%s nodes=%zu triangles=%zu tets=%zu constraints=%zu substeps=4 iterations=4 median_ms=%.6f p95_ms=%.6f max_ms=%.6f hot_allocations=%zu hot_bytes=%zu contacts=%zu candidates=%zu sleeping=%d/%d slowest=%s %.6fms\n",mode==0?"active":mode==1?"settling/sleeping":"no-deformable",mode==2?0:sheet->nodes.size()+solid->nodes.size(),sheet->triangles.size()+solid->triangles.size(),solid->solids.size(),sheet->cloth.size()*3+sheet->bends.size()+solid->solids.size()*7,times[times.size()/2],times[size_t(times.size()*.95)],times.back(),allocations,allocatedBytes,cloth.stats.contacts+block.stats.contacts,cloth.stats.candidates+block.stats.candidates,cloth.sleeping,block.sleeping,phase.c_str(),slowest);if(mode==0){cloth.Reset(glm::dmat4(1));block.Reset(glm::translate(glm::dmat4(1),glm::dvec3(10,0,0)));for(int i=0;i<75;++i){cloth.Step(1./60,physics,zero,{});block.Step(1./60,physics,zero,{});}}}return 0;}
