#include "Deformable.h"
#include "SaveArchive.h"
#include "UniformGravity.h"
#include <glm/gtc/matrix_transform.hpp>
#include <cstdio>
#include <stdexcept>
#include <chrono>
#include <fstream>
#include "RadicalGravity.h"
namespace {unsigned checks=0;void check(bool v,const char* m){++checks;if(!v)throw std::runtime_error(m);}}
int main(){try{
    std::string error;auto asset=std::make_shared<DeformableAsset>(MakeFractureBlock({3,1,1},{3,1,1},false));
    check(asset->fracture->parts.size()==3&&asset->fracture->bonds.size()==2,"baked part/interface graph");
    double volume=0;for(auto t:asset->solids)volume+=t.volume;check(std::abs(volume-3)<1e-10,"partition covers material volume once");
    auto bytes=EncodeDeformableAsset(*asset);DeformableAsset decoded;check(DecodeDeformableAsset({bytes.begin(),bytes.end()},decoded,error)&&decoded.fracture->parts.size()==3,"versioned fracture import round trip");
    auto invalid=decoded;invalid.fracture=std::make_shared<FractureCook>(*decoded.fracture);invalid.fracture->parts[1].nodes.push_back(invalid.fracture->parts[0].nodes[0]);check(!PrepareDeformableAsset(invalid,error),"overlapping material partition rejected");
    FractureState graph;graph.Initialize(*asset->fracture);check(graph.component[2]==0,"intact connected component");check(graph.Request(*asset->fracture,0,1)&&graph.Commit(*asset->fracture),"atomic explicit interface release");check(graph.component[0]!=graph.component[1]&&graph.component[1]==graph.component[2],"cut preserves remaining connected material");check(!graph.Request(*asset->fracture,1,1),"stale topology reference rejected");
    auto loop=MakeFractureBlock({2,2,1},{2,2,1},false);FractureState alternate;alternate.Initialize(*loop.fracture);alternate.Request(*loop.fracture,0,1);alternate.Commit(*loop.fracture);check(alternate.component[3]==alternate.component[0],"alternate load path survives partial crack");
    PhysicsWorld p;check(p.Init(),"ordinary PhysicsWorld initialization");UniformGravity zero({0,0,0});DeformableSettings settings;settings.selfContact=false;settings.material.density=10;settings.material.shearCompliance=1e-6;settings.material.volumeCompliance=1e-7;settings.material.damping=.5;DeformableAttachment pin;pin.group="left";settings.attachments={pin};DeformableTarget target;target.valid=true;
    asset->fracture->tension=80;asset->fracture->shear=80;asset->fracture->compliance=1e-6;
    auto specimen=[&](double force,unsigned sub,unsigned iter){DeformableInstance s;auto cfg=settings;cfg.substeps=sub;cfg.iterations=iter;s.Initialize(asset,cfg,glm::dmat4(1),100+sub);for(int i=0;i<120;++i){s.Force("right",{force,0,0});s.Step(1./60,p,zero,{target});s.fracture.Commit(*asset->fracture);if(!s.error.empty())throw std::runtime_error(s.error);if(s.fracture.revision>1)break;}double demand=0;for(auto d:s.fracture.tensionDemand)demand=std::max(demand,d);std::printf("LOAD force=%.6g sub=%u iterations=%u demand=%.9g revision=%llu\n",force,sub,iter,demand,(unsigned long long)s.fracture.revision);return s;};
    auto low=specimen(5,4,4),high=specimen(400,4,4),fine=specimen(400,8,6);check(low.fracture.revision==1,"below-threshold physical load survives");check(high.fracture.revision>1&&fine.fracture.revision>1,"above-threshold demand fails at two practical quality settings");
    DeformableInstance free;auto cfg=settings;cfg.attachments.clear();cfg.material.damping=0;free.Initialize(asset,cfg,glm::dmat4(1),200);UniformGravity down({0,-9.81f,0});for(int i=0;i<60;++i){free.Step(1./60,p,down,{});free.fracture.Commit(*asset->fracture);}check(free.fracture.revision==1,"free fall produces no fictitious support stress");
    auto q=glm::angleAxis(.73,glm::normalize(glm::dvec3(1,2,3)));DeformableInstance rotated;rotated.Initialize(asset,cfg,glm::mat4_cast(q),201);UniformGravity oblique(glm::vec3(q*glm::dvec3(0,-9.81,0)));for(int i=0;i<60;++i){rotated.Step(1./60,p,oblique,{});rotated.fracture.Commit(*asset->fracture);}double deviation=0;for(unsigned i=0;i<free.positions.size();++i)deviation=std::max(deviation,glm::length(q*free.positions[i]-rotated.positions[i]));std::printf("ROTATION deviation=%.9g revision=%llu\n",deviation,(unsigned long long)rotated.fracture.revision);check(deviation<1e-6&&rotated.fracture.revision==1,"rotation/gravity equivalence and no rigid rotation strain");
    check(std::abs(high.Mass()-low.Mass())<1e-10,"fracture never duplicates/removes mass");MeshData intact,broken;low.MapRender(1,intact);high.MapRender(1,broken);check(broken.indices.size()>intact.indices.size(),"interior faces exposed after cut");
    SaveArchive save;high.Persist(save);DeformableInstance restored;restored.Initialize(asset,settings,glm::dmat4(1),300);SaveArchive read(save.bytes);restored.Persist(read);read.Finish();check(restored.positions==high.positions&&restored.fracture.broken==high.fracture.broken&&restored.plasticRest==high.plasticRest,"restore retains deformed shape/bonds/plastic state");check(restored.fracture.committed.empty(),"restore does not replay fracture events");
    auto independent=specimen(5,4,4);check(independent.fracture.revision==1,"shared immutable cook has independent state");

    FractureState demand;demand.Initialize(*asset->fracture);demand.Observe(*asset->fracture,0,{-200,0,0},{1,0,0});check(!demand.pending[0],"compression is not tensile damage when crushing is disabled");demand.Observe(*asset->fracture,0,{0,200,0},{1,0,0});check(demand.pending[0]==1&&demand.shearDemand[0]>80,"shear separated from tensile demand");
    auto shearSpec=settings;DeformableInstance lateral;lateral.Initialize(asset,shearSpec,glm::dmat4(1),401);for(int i=0;i<60&&lateral.fracture.revision==1;++i){lateral.Force("right",{0,0,400});lateral.Step(1./60,p,zero,{target});lateral.fracture.Commit(*asset->fracture);}check(lateral.error.empty()&&lateral.fracture.revision>1,"actual solved lateral loading drives shear/bending failure");
    FractureState budget;budget.Initialize(*asset->fracture);auto limited=*asset->fracture;limited.pieceBudget=1;budget.Request(limited,0,1);check(!budget.Commit(limited)&&budget.revision==1&&!budget.broken[0]&&!budget.error.empty(),"budget failure retains whole last coherent topology");
    auto before=high.positions;high.fracture.RequestRemoval(*asset->fracture,2,high.fracture.revision);high.fracture.Commit(*asset->fracture);check(high.fracture.removed[2]&&std::abs(high.Mass()-20)<1e-8&&high.positions==before,"explicit part removal discards only its material, never moves surviving nodes");
    auto hit=low.Raycast({0,0,3},{0,0,-1},10);check(hit.hit,"surface query has current material location");low.fracture.Request(*asset->fracture,0,low.fracture.revision);low.fracture.Commit(*asset->fracture);check(!low.Impulse(hit.location,{0,0,1}),"old topology hit cannot load unrelated new boundary");
    auto removedHit=hit.location;removedHit.topologyRevision=low.fracture.revision;for(unsigned part=0;part<asset->fracture->parts.size();++part)low.fracture.RequestRemoval(*asset->fracture,part,low.fracture.revision);low.fracture.Commit(*asset->fracture);removedHit.topologyRevision=low.fracture.revision;check(!low.Impulse(removedHit,{0,0,1}),"removed material rejects even a forged current-revision surface pick");DeformableInstance other;other.Initialize(std::make_shared<DeformableAsset>(MakeDeformableBlock({1,1,1},{1,1,1})),cfg,glm::dmat4(1),700);auto untouched=other.positions;DeformableInstance::SurfaceContacts(low,other,1./60);DeformableInstance::SurfaceContacts(other,low,1./60);check(other.positions==untouched,"removed soft material has no ghost edge/face contact with another family");
    auto malformed=*asset;malformed.fracture=std::make_shared<FractureCook>(*asset->fracture);malformed.fracture->bonds[0].normal={-1,0,0};check(!PrepareDeformableAsset(malformed,error),"wrong interface normal rejected against real oriented faces");
    std::ifstream source("projects/fracture_lab/Assets/deformables/L-partition.source");std::string input{std::istreambuf_iterator<char>(source),{}};DeformableAsset imported;check(ImportFracturePartition(input,imported,error)&&imported.fracture->parts.size()==3,"reusable explicit nonrectangular volumetric partition import");check(!ImportFracturePartition(input+"junk",imported,error),"trailing malformed partition rejected");
    DeformableInstance radial;radial.Initialize(asset,cfg,glm::translate(glm::dmat4(1),glm::dvec3(6,20,0)),501);RadicalGravity field({0,0,0},9.81f);for(int i=0;i<10;++i){radial.Step(1./60,p,field,{});radial.fracture.Commit(*asset->fracture);}check(radial.error.empty()&&radial.fracture.revision==1&&radial.velocities[0].x<0,"small real radial free assembly has no fabricated support damage");
    DeformableInstance translated;translated.Initialize(asset,cfg,glm::translate(glm::dmat4(1),glm::dvec3(2000,0,0)),502);for(int i=0;i<60;++i){translated.Step(1./60,p,down,{});translated.fracture.Commit(*asset->fracture);}check(glm::length(translated.positions[0]-glm::dvec3(2000,0,0)-free.positions[0])<1e-6,"precise local simulation independent of fixed absolute origin offset");
    std::printf("M63 core: %u checks passed\n",checks);return 0;
}catch(const std::exception& e){std::fprintf(stderr,"M63 failure: %s\n",e.what());return 1;}}
