// M54 normal project/resource/physics path. Fixture transforms probe geometry;
// operator bucket controls use ordinary forces/torque, never scripted filling.
#include "EngineHost.h"
#include "RuntimeWorld.h"
#include "GameSession.h"
#include "Simulation.h"
#include "Project.h"
#include "SceneSerialization.h"
#include "Prefab.h"
#include "WorldPresentation.h"
#include "ScreenshotWriter.h"
#include <filesystem>
#include <glm/gtc/matrix_transform.hpp>
#include <chrono>
#include <cstdio>
#include <algorithm>
int main(){int checks=0,failures=0;auto check=[&](bool ok,const char* label){++checks;failures+=!ok;std::printf("%s %s\n",ok?"PASS":"FAIL",label);};auto near=[](double a,double b,double eps=1e-8){return std::abs(a-b)<=eps;};std::string error;Project project;check(project.Load("projects/liquid_reservoir_demo/liquid_reservoir_demo.judasproj",error),"ordinary registered M54 project");EngineHost host;check(host.Init("M54 liquid application",640,360,false,error),"normal EngineHost");if(failures)return 1;host.OpenProjectAssets(project.RootDir(),project.AssetsDir());auto& window=host.GetWindow();window.SetTestInputMode(true);window.Input().SetMap(project.Settings().input,error);
 for(const char* name:{"lab","radial"}){Scene scene;check(LoadSceneFromFile(project.RootDir()+"/Scenes/"+name+".judas",scene,error),"current scene loads");RuntimeWorld world;world.legacyGameplay=false;GameSession game;check(world.Build(scene,&host.Resources(),error,&project.Settings().classification)&&game.Begin(world,error),"ordinary resource/world/session path");if(!world.IsBuilt()){std::puts(error.c_str());return 1;}host.Resources().WaitForAll();auto step=[&](int count){for(int i=0;i<count;++i){window.Input().BeginFixedStep();world.UpdateUIScripts(&window.Input(),1.f/60);world.UpdateScripts(&window.Input(),1.f/60);StepPlayedWorld(game,window,1.f/60);world.PresentationScripts(&window.Input(),1.f/60,.5f);window.Input().BeginFrame();}};step(2);check(world.Liquids().Errors().empty(),"all ordinary baked/cavity assets resolve");check(world.Scripts()->Diagnostics().empty(),"project liquid HUD/controls execute");auto& l=world.Liquids();auto main=l.Handle(std::string(name)=="lab"?20:120),storage=l.Handle(std::string(name)=="lab"?21:121);auto initial=l.Get(main)->volume,q=l.Get(main)->q;window.Input().SetPhysical("key:Q",1);step(1);window.Input().SetPhysical("key:Q",0);check(near(l.Get(main)->volume,initial-.8)&&near(l.Get(storage)->volume,.8),"JS fixedUpdate transfers exactly 800 L");window.Input().SetPhysical("key:E",1);step(1);window.Input().SetPhysical("key:E",0);check(near(l.Get(main)->volume,initial)&&near(l.Get(main)->q,q),"refill restores identical equilibrium");check(scene.Settings().worldOrigin.x==1e12&&l.Sample(std::string(name)=="lab"?glm::vec3(-3,.1,-3):scene.Find(120)->transform.position+scene.Find(120)->transform.rotation*glm::vec3(0,.1,0)),"fixed double absolute origin preserves local submersion");
 if(std::string(name)=="lab"){
  Scene resolved;check(ResolvePrefabs(scene,&host.Assets(),resolved,error)&&resolved.Find(200)->body->compoundBoxes.size()==5,"prefab generic serialization preserves every cavity wall");auto bucket=l.Handle(200);check(bucket.id&&near(l.Get(bucket)->volume,0),"prefab bucket begins genuinely empty");auto pose=world.RuntimeDefinition(200)->transform;pose.position={-3,.20f,-3};world.SetRuntimeTransform(200,pose);for(int i=0;i<120;++i)world.UpdateLiquids(1./60);double filled=l.Get(bucket)->volume;check(filled>.02&&near(l.Get(main)->volume+filled,1),"connected opening scoop debits main basin by contained volume");auto first=filled;pose.position={0,2,1};world.SetRuntimeTransform(200,pose);for(int i=0;i<60;++i)world.UpdateLiquids(1./60);check(near(l.Get(bucket)->volume,first),"removed cup carries actual water without external connectivity");auto carryPose=pose;pose.position={2000,2,1};world.SetRuntimeTransform(200,pose);world.UpdateLiquids(1./60);
  check(!l.Get(bucket)->equilibriumValid&&near(l.Get(bucket)->volume,first)&&!l.Sample({0,2.05f,1})&&l.Errors().count(200),"unsupported gravity suspends old cavity while retaining volume and diagnostic");
  pose=carryPose;world.SetRuntimeTransform(200,pose);world.UpdateLiquids(1./60);
  check(l.Get(bucket)->equilibriumValid&&near(l.Get(bucket)->volume,first)&&!l.Errors().count(200),"supported return reconstructs current cavity and clears diagnostic");
  pose.position={-3,.20f,-3};world.SetRuntimeTransform(200,pose);for(int i=0;i<60;++i)world.UpdateLiquids(1./60);check(near(l.Get(bucket)->volume,first),"second scoop equilibrates delta without repeated duplication");
  pose.position={1.5f,.75f,-2.7f};pose.rotation=glm::angleAxis(-glm::half_pi<float>(),glm::vec3(1,0,0));world.SetRuntimeTransform(200,pose);for(int i=0;i<360;++i)world.UpdateLiquids(1./60);auto receiver=l.Get(l.Handle(22))->volume;auto accounting=l.Accounting("water");std::printf("POUR main=%.12g bucket=%.12g receiver=%.12g detached=%.12g total=%.12g error=%.12g\n",l.Get(main)->volume,l.Get(bucket)->volume,receiver,accounting.detached,accounting.total,accounting.error);check(l.Get(bucket)->volume<first*.6&&receiver>first*.25,"tilt emits ballistic conserved parcels into actual receiving basin");check(std::abs(accounting.error)<=accounting.tolerance,"scoop carry pour conserves complete material ledger");
  auto a=l.Handle(30),b=l.Handle(31),tank=l.Handle(32);check(!l.Connections().at(33),"separate depressions disconnected below saddle");l.Transfer(tank,a,1.1);for(int i=0;i<360;++i)world.UpdateLiquids(1./60);check(l.Connections().at(33)&&l.Get(b)->volume>.3,"above saddle opens hydraulic redistribution");check(near(l.Accounting("graph-water").total,1.8),"graph merge never duplicates owned quantity");l.Transfer(a,tank,l.Get(a)->volume-.1);l.Transfer(b,tank,l.Get(b)->volume-.1);world.UpdateLiquids(1./60);check(!l.Connections().at(33)&&near(l.Get(a)->volume,.1)&&near(l.Get(b)->volume,.1),"drain closes connection and preserves separate residual pools");
  SceneTransform placement;placement.position={0,2,1};auto spawned=world.SpawnPrefab("54545454545454545454545454540008",placement,error);host.Resources().WaitForAll();world.UpdateLiquids(1./60);auto h=l.Handle(spawned);check(spawned&&h.id&&l.Get(h)->container&&near(l.Get(h)->volume,0),"ordinary runtime prefab creates independent empty container");l.Transfer(main,h,.01);double before=l.Accounting("water").total;check(world.DestroyHierarchy(spawned,error)&&!l.Get(h)&&near(l.Accounting("water").total,before),"destroyed container invalidates handle and retains owned detached volume");
 }
 // Actual opt-in force, gravity and existing physics solver, not a render-only prop.
 step(180);auto body=world.RuntimeBody(201);check(world.Physics().IsDynamicBody(body)&&world.Physics().IsBodyEnabled(body),"ordinary buoyant rigid body remains live");auto bodyPose=world.Physics().GetTransform(body);auto center=std::string(name)=="lab"?glm::vec3(-3,0,-3):scene.Find(120)->transform.position;auto up=std::string(name)=="lab"?glm::vec3(0,1,0):glm::normalize(center);check(glm::dot(bodyPose.position-center,up)>.05f&&std::isfinite(glm::length(world.Physics().GetLinearVelocity(body))),"implicit hydrostatics physically support ordinary body under selected gravity");
 auto start=std::chrono::steady_clock::now();step(120);double fixed=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count()/120;std::vector<double> frames;unsigned draws=0;for(int i=0;i<35;++i){auto begin=std::chrono::steady_clock::now();step(1);auto camera=world.view->pose;auto view=glm::mat4_cast(glm::inverse(camera.rotation))*glm::translate(glm::mat4(1),-camera.position),projection=glm::perspective(glm::radians(70.f),640.f/360,.05f,120.f);host.GetRenderer().ResetStats();RenderWorldFrame(host.GetRenderer(),640,360,world,&game,view,projection,camera.position,.5f);host.GetRenderer().BeginUIFrame(640,360);world.UI().Draw(host.GetRenderer(),640,360);host.GetRenderer().EndUIFrame();if(i==34){std::filesystem::create_directories("build/m54-visual");std::vector<unsigned char> rgb;host.GetRenderer().CaptureFrame(640,360,rgb);WriteRgbPng(std::string("build/m54-visual/")+name+".png",640,360,rgb);}window.SwapBuffers();draws=host.GetRenderer().Stats().drawCalls;if(i>=5)frames.push_back(std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-begin).count());}std::sort(frames.begin(),frames.end());double sum=0;for(double n:frames)sum+=n;std::printf("M54 %s fixed/script %.4f ms; rendered offscreen640x360 mean %.3f ms %.1f FPS p95 %.3f ms max %.3f ms draws %u reservoirs %zu containers %zu parcels %zu bodies %zu\n",name,fixed,sum/frames.size(),1000/(sum/frames.size()),frames[28],frames.back(),draws,l.States().size()-(std::string(name)=="lab"?1:0),std::string(name)=="lab"?size_t(1):size_t(0),l.Parcels().size(),world.CountLifecycle().physicsBodies);
 check(world.Scripts()->Diagnostics().empty(),"continued scripts remain fault free");auto stale=main;game.ResetToAuthoredState();world.UpdateLiquids(1./60);check(!world.Liquids().Get(stale)&&near(world.Liquids().Get(world.Liquids().Handle(std::string(name)=="lab"?20:120))->volume,initial),"authored reset invalidates liquid handles and restores authored volume");game.End();world.Destroy();check(world.Liquids().States().empty()&&world.Liquids().Parcels().empty(),"Stop releases all world-owned liquid state");}
 host.Shutdown();std::printf("M54 application %d checks %d failures\n",checks,failures);return failures?1:0;}
