#include "LiquidSystem.h"
#include "Scene.h"
#include "UniformGravity.h"
#include "RadicalGravity.h"
#include "FaithfulGravity.h"
#include "GravityContextMap.h"
#include "BoxVolume.h"
#include <glm/gtc/quaternion.hpp>

#include <chrono>
#include <algorithm>
#include <limits>
#include <cstdio>
#include <cmath>
#include <filesystem>
int main(){int checks=0,failed=0;auto check=[&](bool b,const char* name){++checks;if(!b)++failed;std::printf("%s %s\n",b?"PASS":"FAIL",name);};auto near=[](double a,double b,double t=1e-7){return std::abs(a-b)<=t;};std::string error;UniformGravity gravity({0,-9.81f,0});GravityEquilibrium eq;check(gravity.Equilibrium({},eq),"generic uniform equilibrium capability");check(near(eq.Potential({0,2,0}),19.62,1e-5),"potential agrees with actual uniform acceleration");FaithfulGravity faithful;GravityEquilibrium faithfulEq;check(faithful.Equilibrium({},faithfulEq),"FaithfulGravity exposes same conservative contract");auto geometry=LiquidBox({-1,0,-1},{1,1,1});check(ValidateLiquidGeometry(geometry,error),"disjoint cavity tetrahedra validate");auto overlap=geometry;overlap.cells.push_back(geometry.cells[0]);check(!ValidateLiquidGeometry(overlap,error),"overlapping accounting geometry rejected");LiquidBasinData b;check(BakeLiquidBasin(geometry,eq,1e-6,.001,"fixture",b,error),"actual geometry capacity bake");check(near(b.capacity,4),"rectangular tank analytic full capacity");check(near(LiquidCapacity(geometry,eq,.25),1),"rectangle clipping matches area times height");check(near(LiquidInverse(b,1),.25),"binary-search inverse matches analytic height");bool monotonic=true;for(size_t i=1;i<b.curve.size();++i)monotonic&=b.curve[i].q>b.curve[i-1].q&&b.curve[i].volume>=b.curve[i-1].volume;check(monotonic,"curve is monotonic");check(near(b.curve.back().volume,b.capacity),"capacity endpoint matches total geometry");
 // Wedge floor y=.25*x: independent analytic integral at h=.5 over x in [0,2].
 auto wedge=LiquidBox({0,0,0},{2,1,1});for(auto& t:wedge.cells)for(auto& v:t)if(v.y==0)v.y=.25*v.x;LiquidBasinData w;check(BakeLiquidBasin(wedge,eq,1e-6,.002,"wedge",w,error),"irregular wedge capacity adapts nonlinear region");check(near(LiquidCapacity(wedge,eq,.5),.5),"irregular volume from independent floor integral");double maximumResidual=0;for(int i=0;i<=100;++i){double amount=w.capacity*i/100.;maximumResidual=std::max(maximumResidual,std::abs(LiquidCapacity(wedge,eq,LiquidInverse(w,amount))-amount));}check(maximumResidual<=w.volumeTolerance,"adaptive volume residual meets declared tolerance");std::printf("M54 geometry volume residual %.12g m3, samples %zu\n",maximumResidual,w.curve.size());
 SceneObject duplicate;duplicate.liquidBasin=LiquidBasinSettings{};duplicate.fluidVolume=SceneFluidVolumeComponent{};check(!ValidateLiquidComponents(duplicate,error),"one water body cannot register particle and conserved ownership together");
 LiquidSystem invalid;LiquidBasinSettings nan;nan.initialVolume=std::numeric_limits<double>::quiet_NaN();check(!invalid.AddBasin(1,nan,{},std::make_shared<LiquidBasinData>(b),error).id,"nonfinite initial quantity rejected before ledger mutation");
  LiquidSystem system;check(near(system.Accounting("water").total,0),"empty ledger is zero");LiquidBasinSettings settings;settings.initialVolume=1;auto a=system.AddBasin(1,settings,{},std::make_shared<LiquidBasinData>(w),error);settings.initialVolume=0;auto storage=system.AddBasin(2,settings,{},std::make_shared<LiquidBasinData>(b),error);check(a.id&&storage.id,"reservoirs have stable generation handles");double original=system.Get(a)->q;check(near(system.Transfer(a,storage,.8),.8),"exact 800 litre transaction");check(near(system.Get(a)->volume,.2),"1000 litre to 200 litre ledger proof");check(near(LiquidCapacity(wedge,eq,system.Get(a)->q),.2,1e-6),"200 litre surface against actual geometry");check(near(system.Transfer(storage,a,.8),.8)&&near(system.Get(a)->q,original,1e-6),"return 800 litres restores same equilibrium");check(near(system.Transfer(a,storage,100),1),"transfer bounded by source");check(near(system.Transfer(storage,a,100),1),"reverse transfer source limited");settings.initialVolume=3.9;auto full=system.AddBasin(3,settings,{},std::make_shared<LiquidBasinData>(b),error);check(near(system.Transfer(a,full,1),.1),"destination finite capacity respected");system.Transfer(full,a,.1);for(int i=0;i<10000;++i){system.Transfer(a,storage,.00001234);system.Transfer(storage,a,.00001234);}auto accounting=system.Accounting("water");check(std::abs(accounting.error)<=accounting.tolerance,"repeated paired transfers remain within FP ledger tolerance");std::printf("M54 ledger error %.17g m3 tolerance %.17g\n",accounting.error,accounting.tolerance);
 check(system.SetEnabled(a,false)&&system.Transfer(a,storage,.2)==0,"disabled owner retains liquid and rejects transactions");system.SetEnabled(a,true);check(system.Transfer(a,{999,0},.2)==0&&near(system.Get(a)->volume,1),"stale destination cannot partially debit source");check(system.Transfer(a,a,.5)==0,"self transfer no-op");
 auto cupGeom=LiquidBox({-.2,-.3,-.2},{.2,.3,.2});LiquidContainerSettings cup;cup.initialVolume=.01;cup.opening={{-.2,.3,-.2},{.2,.3,-.2},{.2,.3,.2},{-.2,.3,.2}};SceneTransform pose;auto c=system.AddContainer(4,cup,pose,cupGeom,eq,error);check(c.id&&near(system.Get(c)->capacity,.096),"container real cavity capacity");check(near(system.Get(c)->q,-.2375,1e-7),"known internal volume exact plane");auto rotate=glm::angleAxis(glm::radians(90.f),glm::normalize(glm::vec3(1,0,1)));pose.rotation=rotate;check(system.SetContainerPose(c,pose,eq,error),"rotating cavity solves current gravity-relative plane");check(near(system.Get(c)->volume,.01),"rotation changes geometry not quantity");check(system.Get(c)->stableCapacity<system.Get(c)->capacity,"explicit lip sets tilted stable capacity");auto before=system.Accounting("water").total;system.Emit(c,.004,{2,1,0},{0,0,0});check(near(system.Get(c)->volume,.006),"pour debits contained amount");check(near(system.Accounting("water").detached,.004),"detached parcel owns full emitted amount");auto parcel=system.Parcels().begin()->first;check(near(system.Receive(parcel,storage,.004),.004),"receiver coherently acquires parcel volume");check(system.Parcels().empty(),"merged parcel removed");check(near(system.Accounting("water").total,before),"entire detached pour conserves ledger");auto stale=c;check(system.Remove(c)&&!system.Get(stale),"container removal invalidates generation handle");check(system.Accounting("water").detached>.0059,"destruction retains volume in parked parcel");auto again=system.AddContainer(4,cup,{},cupGeom,eq,error);check(again.id!=stale.id&&!system.Get(stale),"owner reuse cannot alias stale handle");LiquidSystem another;check(!another.Get(a),"world generation rejects previous-world handle");
 LiquidSystem bath;settings.initialVolume=2;auto bathHandle=bath.AddBasin(10,settings,{},std::make_shared<LiquidBasinData>(b),error);check(bath.Sample({0,.25f,0}).has_value(),"point inside implicit bulk");check(!bath.Sample({0,.75f,0}),"point above equilibrium is dry");check(!bath.Sample({3,.25f,0}),"point outside actual basin geometry is dry");auto sample=bath.Sample({0,.25f,0});check(sample&&near(sample->depth,.25),"equilibrium depth correct");auto object=LiquidBox({-.25,.25,-.25},{.25,.75,.25});auto sub=bath.Submerged(object);check(near(sub.volume,.0625),"actual submerged box volume");check(near(sub.buoyancy.y,1000*.0625*9.81,1e-3),"analytic Archimedes force");check(near(sub.center.y,.375),"center of displaced volume");
 GravityEquilibrium oblique;UniformGravity arbitrary({-6,-2,7});arbitrary.Equilibrium({},oblique);SceneTransform oriented;oriented.rotation=glm::normalize(glm::quat(float(1+oblique.up.y),glm::cross(glm::vec3(0,1,0),glm::vec3(oblique.up))));auto rotatedEq=oblique;rotatedEq.up=glm::inverse(glm::dquat(oriented.rotation))*oblique.up;LiquidBasinData rotated;check(BakeLiquidBasin(geometry,rotatedEq,1e-6,.001,"rotated",rotated,error),"oblique uniform basin bake");LiquidSystem tilted;settings.initialVolume=2;auto th=tilted.AddBasin(1,settings,oriented,std::make_shared<LiquidBasinData>(rotated),error);glm::vec3 test=oriented.rotation*glm::vec3(0,.25,0);auto rs=tilted.Sample(test);check(rs&&glm::length(rs->normal-glm::vec3(oblique.up))<1e-5,"submersion follows arbitrary up, not world Y");check(th.id&&bathHandle.id,"independent oriented reservoir handles");
 RadicalGravity radial({0,0,0},4);GravityEquilibrium radialEq;check(radial.Equilibrium({0,10,0},radialEq)&&radialEq.kind==GravityEquilibrium::Kind::Radius,"actual constant-magnitude radial model exposes radius equipotential");check(near(radialEq.Potential({0,10,0}),40),"radial potential matches existing gravity magnitude law");auto bowl=LiquidBox({-.5,10,-.5},{.5,11,.5});LiquidBasinData radialData;check(BakeLiquidBasin(bowl,radialEq,.0001,.02,"radial",radialData,error),"curved radial capacity bake");double radialLevel=LiquidInverse(radialData,.4);check(radialLevel>10.3&&radialLevel<10.5,"known radial bowl volume produces sensible radius");// Independent sphere/box cross-section quadrature, not tetra clipping.
 double reference=0;for(int x=0;x<256;++x)for(int z=0;z<256;++z){double px=(x+.5)/256.-.5,pz=(z+.5)/256.-.5;reference+=std::clamp(std::sqrt(10.4*10.4-px*px-pz*pz)-10.,0.,1.)/(256.*256.);}check(std::abs(LiquidCapacity(radialData.geometry,radialEq,10.4)-reference)<=radialData.coordinateError,"radial capacity agrees with independent spherical cross-section within curved geometry bound");
 check(radialData.coordinateError<=radialData.heightTolerance*.25,"radial interpolation has declared curvature bound");LiquidSystem radialWorld;settings.initialVolume=.4;auto rh=radialWorld.AddBasin(1,settings,{},std::make_shared<LiquidBasinData>(radialData),error);auto radialSample=radialWorld.Sample({.4f,10.1f,0});check(radialSample&&std::abs(glm::length(radialSample->surfacePoint)-radialLevel)<.005,"query surface is curved equipotential not flat plane");radialWorld.Transfer(rh,rh,0);check(near(radialWorld.Accounting("water").total,.4),"radial geometry cannot alter authoritative quantity");
 // Unsupported equilibrium must suspend geometry without losing owned volume.
 LiquidSystem suspended;auto suspendedHandle=suspended.AddContainer(900,cup,{},cupGeom,eq,error);GravityEquilibrium zero=eq;zero.magnitude=0;
 check(!suspended.SetContainerPose(suspendedHandle,{},zero,error)&&!suspended.Sample({0,-.28f,0})&&near(suspended.Get(suspendedHandle)->volume,.01),"unsupported gravity suspends stale query geometry while retaining liquid");
 check(suspended.SetContainerPose(suspendedHandle,{},eq,error)&&suspended.Sample({0,-.28f,0})&&near(suspended.Get(suspendedHandle)->volume,.01),"return to supported gravity resolves retained container geometry");
 auto path=std::filesystem::path("build/m54-fixture.judasbasin");check(SaveLiquidBasin(path.string(),w,error),"baked basin serialization");LiquidBasinData reload;check(LoadLiquidBasin(path.string(),reload,error)&&near(reload.capacity,w.capacity)&&reload.fingerprint==w.fingerprint,"baked asset round-trip");check(!DecodeLiquidBasin({'b','a','d'},reload,error),"malformed baked header rejected cleanly");
 auto start=std::chrono::steady_clock::now();volatile double result=0;for(int i=0;i<1000;++i)result+=LiquidInverse(w,(i%100)*w.capacity/100);double ms=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();std::printf("M54 1000 inversions %.6f ms, 1 ~%.6f ms\n",ms,ms/1000);for(double depth:{10.,100.}){LiquidBasinData deep;BakeLiquidBasin(LiquidBox({0,0,0},{2,depth,2}),eq,1e-6,.001,"depth",deep,error);auto t=std::chrono::steady_clock::now();for(int i=0;i<10000;++i)result+=LiquidInverse(deep,deep.capacity*(i%100)/100.);std::printf("M54 depth %.0f m: %zu curve samples, 10000 inversions %.5f ms\n",depth,deep.curve.size(),std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-t).count());}
 for(int count:{1,10,100}){auto t=std::chrono::steady_clock::now();for(int i=0;i<count;++i){pose.rotation=glm::angleAxis(float(i)*.07f,glm::normalize(glm::vec3(1,2,3)));system.SetContainerPose(again,pose,eq,error);}std::printf("M54 %d rotating container solves %.5f ms\n",count,std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-t).count());}
 auto transferStart=std::chrono::steady_clock::now();for(int i=0;i<1000;++i){system.Transfer(a,storage,.0001);system.Transfer(storage,a,.0001);}std::printf("M54 2000 paired transfers/resolves %.4f ms\n",std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-transferStart).count());
  check(std::isfinite(result),"performance query results retained");std::printf("M54 %d checks %d failures\n",checks,failed);return failed?1:0;}
