#include "EngineHost.h"
#include "RuntimeWorld.h"
#include "GameSession.h"
#include "Simulation.h"
#include "Project.h"
#include "SceneSerialization.h"
#include "SceneSession.h"
#include "WorldPresentation.h"
#include <glm/gtc/matrix_transform.hpp>
#include <glm/gtc/quaternion.hpp>
#include <algorithm>
#include <cstdio>
#include <filesystem>
#include <chrono>
#include <cmath>
#include <fstream>
int main(){int checks=0,failures=0;auto check=[&](bool ok,const char* label){++checks;failures+=!ok;std::printf("%s %s\n",ok?"PASS":"FAIL",label);};std::string error;Project project;check(project.Load("projects/shooter_game/shooter_game.judasproj",error),"ordinary Spring Range project");EngineHost host;check(host.Init("M53 navigation game",640,360,false,error),"normal engine host");if(failures)return 1;host.Audio().Init(error,true);host.OpenProjectAssets(project.RootDir(),project.AssetsDir());auto& window=host.GetWindow();window.SetTestInputMode(true);window.Input().SetMap(project.Settings().input,error);Scene scene;LoadSceneFromFile(project.StartupScenePath(),scene,error);RuntimeWorld world;world.legacyGameplay=false;world.SetSceneControl(std::make_shared<SceneSession>(project,project.StartupScenePath()));check(world.Build(scene,&host.Resources(),error,&project.Settings().classification,&project.Settings().navigation),"actual scene and prefabs build");if(failures){std::puts(error.c_str());return 1;}GameSession game;check(game.Begin(world,error),"normal fixed-step game");host.Resources().WaitForAll();auto step=[&](int count){for(int i=0;i<count;++i){window.Input().BeginFixedStep();world.UpdateUIScripts(&window.Input(),1.f/60);world.UpdateScripts(&window.Input(),1.f/60);if(!world.UI().Paused())StepPlayedWorld(game,window,1.f/60);world.PresentationScripts(&window.Input(),1.f/60,.5f);window.Input().BeginFrame();}};
 auto state=[&](EntityId id){for(auto& value:world.Scripts()->Capture())if(value.entity==id)return value.json;return std::string{};};
 auto first=world.RuntimeCharacter(1000)->position;step(120);check(world.Navigation().Errors().empty(),"baked assets current; no navigation errors");for(auto [id,msg]:world.Navigation().Errors())std::puts(msg.c_str());check(world.Scripts()->Diagnostics().empty(),"all chase/shooter scripts execute fault-free");check(world.QueryEntities(CategoryBit(2)).size()==12,"six independent prefab roots and sensors");check(glm::distance(world.RuntimeCharacter(1000)->position,first)>.5f,"JS navigation guidance actually moves motor");auto agent=world.Navigation().Agent(1000);check(agent&&agent->path.status!=NavigationPath::Status::Failed&&agent->hasDestination,"chase agent holds a route");check(world.RuntimeCharacter(1000)->result.supported,"chase remains physically supported");check(world.Navigation().Sample({34,0,-4},1).has_value(),"separate landing surface coexists");auto route=world.Navigation().FindPath({34,0,-4},{0,0,-4});bool link=false;for(auto c:route.corners)link|=c.link==552;check(route.status==NavigationPath::Status::Complete&&link,"actual project link connects separate region");
 auto stats=world.Navigation().Statistics();std::printf("NAV game: %zu surfaces %zu tile layers %zu polygons %zu agents %zu obstacles\n",stats.surfaces,stats.tiles,stats.polygons,stats.agents,stats.obstacles);
 const auto revision=world.Navigation().Revision();window.Input().SetPhysical("key:B",1);step(1);window.Input().SetPhysical("key:B",0);step(15);check(!world.RuntimeDefinition(554)->navigationObstacle->enabled&&world.Navigation().Revision()>revision,"JS disables generic obstacle; cache revision changes");check(!world.Physics().IsBodyEnabled(world.RuntimeBody(554)),"physical blocker changes independently through normal collider API");
 window.Input().SetPhysical("key:N",1);step(1);window.Input().SetPhysical("key:N",0);step(15);check(world.QueryEntities(CategoryBit(2)).size()==14,"runtime prefab spawn creates another independent navigator");
 // Ordinary public project weapon ray detects the motor's separate sensor proxy.
 auto pose=world.RuntimeDefinition(10)->transform;pose.position={-20,.92f,10};world.SetRuntimeTransform(10,pose);auto target=world.RuntimeDefinition(1000)->transform;target.position={-20,.92f,5};world.SetRuntimeTransform(1000,target);world.Navigation().ClearDestination(1000);step(1);auto proxy=world.RuntimeDefinition(1001)->transform;check(glm::distance(proxy.position,world.RuntimeDefinition(1000)->transform.position)<.1f,"authoritative sensor follows current motor pose");window.Input().SetPhysical("mouse:Left",1);step(1);window.Input().SetPhysical("mouse:Left",0);step(15);check(state(1000).find("\"health\":1")!=std::string::npos,"real ray hit reaches JS enemy health");window.Input().SetPhysical("mouse:Left",1);step(1);window.Input().SetPhysical("mouse:Left",0);step(1);check(state(1000).find("\"defeated\":true")!=std::string::npos,"second real hit defeats through JS only");check(!world.RuntimeDefinition(1000)->navigationAgent->enabled&&!world.Physics().IsBodyEnabled(world.RuntimeBody(1001)),"defeat clears navigation and sensor lifecycle");
 auto start=std::chrono::steady_clock::now();step(180);std::printf("M53 GAME fixed/script/presentation %.3f ms/step, %zu bodies\n",std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count()/180,world.CountLifecycle().physicsBodies);std::vector<double> frames;unsigned draws=0;double startup=0;for(int i=0;i<65;++i){auto t=std::chrono::steady_clock::now();step(1);auto pose=world.view->pose;auto view=glm::mat4_cast(glm::inverse(pose.rotation))*glm::translate(glm::mat4(1),-pose.position);auto projection=glm::perspective(glm::radians(world.view->fov),640.f/360,.05f,120.f);host.GetRenderer().ResetStats();RenderWorldFrame(host.GetRenderer(),640,360,world,&game,view,projection,pose.position,.5f);world.UI().Draw(host.GetRenderer(),640,360);window.SwapBuffers();draws=host.GetRenderer().Stats().drawCalls;double elapsed=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-t).count();if(i==0)startup=elapsed;if(i>=5)frames.push_back(elapsed);}std::sort(frames.begin(),frames.end());double sum=0;for(auto n:frames)sum+=n;std::printf("M53 rendered offscreen 640x360: mean %.3f ms (%.1f FPS) p95 %.3f ms max %.3f ms, draws %u; first render %.3f ms\n",sum/frames.size(),1000/(sum/frames.size()),frames[57],frames.back(),draws,startup);
 check(world.Scripts()->Diagnostics().empty(),"continued game remains fault-free");game.End();world.Destroy();check(!world.IsBuilt()&&!world.Scripts(),"Stop destroys world-owned navigation and scripts");// Direct RuntimeWorld destruction must retain navigation until script cleanup finishes.
 auto fixture=std::filesystem::path("build/m53-direct-destroy-project");std::filesystem::remove_all(fixture);std::filesystem::copy("projects/shooter_game",fixture,std::filesystem::copy_options::recursive);std::ofstream(fixture/"Assets/scripts/enemy.js")<<R"JS(import {console} from 'judas';
 export default class {constructor({entity}){this.entity=entity;}destroy(){if(this.entity.valid){this.entity.navigation.clear();console.log('M53_NAV_DESTROY_CALLBACK');}}}
 )JS";Project lifetimeProject;check(lifetimeProject.Load((fixture/"shooter_game.judasproj").string(),error),"normal cleanup fixture project");host.OpenProjectAssets(lifetimeProject.RootDir(),lifetimeProject.AssetsDir());Scene lifetimeScene;LoadSceneFromFile(lifetimeProject.StartupScenePath(),lifetimeScene,error);RuntimeWorld lifetime;check(lifetime.Build(lifetimeScene,&host.Resources(),error,&lifetimeProject.Settings().classification,&lifetimeProject.Settings().navigation),"cleanup fixture world builds");lifetime.SetSceneControl(std::make_shared<SceneSession>(lifetimeProject,lifetimeProject.StartupScenePath()));GameSession lifetimeGame;check(lifetimeGame.Begin(lifetime,error),"cleanup fixture fixed-step session");host.Resources().WaitForAll();StepPlayedWorld(lifetimeGame,window,1.f/60);check(lifetime.Scripts()&&lifetime.Scripts()->Diagnostics().empty(),"cleanup fixture callbacks start safely");lifetimeGame.End();lifetime.Destroy();check(!lifetime.IsBuilt()&&!lifetime.Scripts(),"direct destruction permits navigation cleanup callbacks");
 host.Shutdown();std::printf("M53 game %d checks, %d failures\n",checks,failures);return failures?1:0;}
