#include "PoseComposition.h"
#include "ModelLoader.h"
#include "RuntimeWorld.h"
#include "SceneSerialization.h"
#include "SceneFingerprint.h"
#include <chrono>
#include <cstdio>
int checks=0,failures=0;void Check(bool ok,const char* text){++checks;failures+=!ok;std::printf("%s %s\n",ok?"PASS":"FAIL",text);}bool Near(float a,float b){return std::abs(a-b)<2e-5f;}
int main(){MeshData mesh;std::string error;Check(LoadModelMesh("projects/animation_demo/Assets/models/bend_bar.glb",mesh,error),"shared M46 import reused");if(!mesh.skeletal)return 1;const auto& asset=*mesh.skeletal;const auto& s=asset.skeleton;
 auto a=s.rest,b=a;b.local[1].translation.x=2;b.local[1].scale=glm::vec3(3);b.local[1].rotation=glm::angleAxis(1.f,glm::vec3(0,0,1));auto blend=BlendPoses(a,b,.5);
 Check(Near(blend.local[1].translation.x,1)&&Near(blend.local[1].scale.x,2),"50/50 translation and scale");Check(Near(blend.local[1].rotation.z,std::sin(.25f))&&Near(glm::length(blend.local[1].rotation),1),"normalized shortest path quaternion blend");b.local[1].rotation=-b.local[1].rotation;Check(Near(std::abs(glm::dot(blend.local[1].rotation,BlendPoses(a,b,.5).local[1].rotation)),1),"equivalent quaternion signs");
 std::vector<int> mask;Check(ResolveJointMask(s,{"Root/Elbow"},mask,error)&&mask==std::vector<int>{1},"stable hierarchy key resolves mask");blend=BlendPoses(a,b,1,mask);Check(blend.local[0].translation==a.local[0].translation&&blend.local[2].rotation==a.local[2].rotation,"mask leaves other local joints unchanged");auto skin=ResolveSkinMatrices(s,blend);auto point=skin[2]*glm::vec4(0,2,0,1);Check(Near(point.x,2-3*std::sin(1.f))&&Near(point.y,1+3*std::cos(1.f)),"masked parent correctly carries child hierarchy");
 PoseContribution c;c.pose=b;c.reference=a;c.weight=.5;c.additive=true;c.mask={1};auto add=ResolvePose(s,a,{c});Check(Near(add.local[1].translation.x,1)&&Near(std::abs(add.local[1].rotation.z),std::sin(.25f)),"additive evaluated against explicit reference");Check(Near(std::abs(add.local[1].rotation.z),std::sin(.25f))&&Near(add.local[1].scale.x,2),"additive rotation and relative scale");
 AnimationPlayback p;p.clip="Wave";PoseMixer mixer;auto initial=mixer.Sample(asset,p,.3);mixer.CrossFade(p,"Stretch",1);auto begin=mixer.Sample(asset,p,0);Check(begin.local[1].rotation==initial.local[1].rotation,"crossfade begins without pop");mixer.Sample(asset,p,1);Check(!mixer.Transitioning()&&p.clip=="Stretch"&&Near(p.time,1),"crossfade completes and retires outgoing contributors");mixer.CrossFade(p,"Wave",1);auto middle=mixer.Sample(asset,p,.25);mixer.CrossFade(p,"Stretch",.5);auto interrupted=mixer.Sample(asset,p,0);Check(Near(std::abs(glm::dot(middle.local[1].rotation,interrupted.local[1].rotation)),1),"interrupted fade preserves current weighted state");mixer.CrossFade(p,"Wave",0);Check(!mixer.Transitioning()&&Near(p.time,0),"zero-duration replacement");AnimationPlayback independent;independent.clip="Stretch";PoseMixer other;other.Sample(asset,independent,.4);mixer.Sample(asset,p,.1);Check(Near(independent.time,.4)&&Near(p.time,.1),"independent instance mixer clocks");
 Scene scene,round;LoadSceneFromFile("projects/animation_demo/Scenes/main.judas",scene,error);AnimationLayerSettings layer;layer.id="tip";layer.clip="Wave";layer.weight=.5;layer.mask={"Root/Elbow/Tip"};scene.Find(10)->animation->layers={layer};std::string text;SaveSceneToString(scene,text);Check(LoadSceneFromString(text,round,error)&&ScenesEqual(scene,round),"authored layers and mask round-trip");std::string h1,h2;ComputeSceneFingerprint(scene,h1,error);round.Find(10)->animation->layers[0].weight=.3;ComputeSceneFingerprint(round,h2,error);Check(h1!=h2,"layer changes enter strict authored fingerprint");
 auto start=std::chrono::steady_clock::now();for(int i=0;i<10000;++i){auto pose=ResolvePose(s,a,{c,c,c});if(pose.local.empty())return 1;}std::printf("PERFORMANCE three_layers_us=%.6f\n",std::chrono::duration<double,std::micro>(std::chrono::steady_clock::now()-start).count()/10000);Skeleton modest;for(int i=0;i<32;++i){modest.names.push_back("joint"+std::to_string(i));modest.parents.push_back(i-1);modest.order.push_back(i);modest.rest.local.push_back({});}PoseContribution layer32;layer32.pose=modest.rest;layer32.reference=modest.rest;layer32.weight=.5;layer32.pose.local[12].rotation=glm::angleAxis(.4f,glm::vec3(1,0,0));start=std::chrono::steady_clock::now();for(int frame=0;frame<1000;++frame)for(int instance=0;instance<8;++instance){auto pose=ResolvePose(modest,modest.rest,{layer32,layer32,layer32});if(pose.local.size()!=32)return 1;}std::printf("PERFORMANCE eight_instances_32_nodes_three_layers_us=%.6f samples=1000\n",std::chrono::duration<double,std::micro>(std::chrono::steady_clock::now()-start).count()/1000);std::printf("SUMMARY %d checks %d failures\n",checks,failures);return failures?1:0;}
