#include "EngineHost.h"
#include "RuntimeWorld.h"
#include "GameSession.h"
#include "Project.h"
#include "Simulation.h"
#include "SceneSerialization.h"
#include "SceneFingerprint.h"
#include "WorldPersistence.h"
#include <chrono>
#include <filesystem>
#include <iostream>
#include <stdexcept>
namespace{unsigned checks=0;void require(bool v,const char* message){++checks;if(!v)throw std::runtime_error(message);}}
int main(){std::cout<<std::unitbuf;try{
 auto physical=std::make_unique<PhysicsWorld>();require(physical->Init(),"joint policy world");auto body=physical->CreateDynamicSphere({0,0,0},.3f,2,.5f,0);JointSettings joint;joint.type=JointType::Ball;joint.bodyA=body;joint.rotationalResistance=.2f;auto handle=physical->CreateJoint(joint);physical->SetAngularVelocity(body,{0,4,0});physical->Step(1.f/60);const float inertia=.4f*2*.3f*.3f;require(std::abs(physical->GetAngularVelocity(body).y-4/(1+.2f/(60*inertia)))<1e-4f,"implicit passive resistance independent expectation");for(int i=0;i<1200;++i)physical->Step(1.f/60);require(physical->IsSleeping(body),"quiescent world-anchored body sleeps at normal thresholds");require(physical->SetJoint(handle,joint)&&physical->IsSleeping(body),"unchanged constraint write preserves sleep");joint.rotationalResistance=.3f;require(physical->SetJoint(handle,joint)&&!physical->IsSleeping(body),"changed resistance wakes authoritative articulation");physical.reset();
 Scene original;std::string error;require(LoadSceneFromFile("projects/post_m65_consumers/Scenes/skate/park.judas",original,error),"real imported Skate scene");auto rig=*original.Find(12);rig.scripts.clear();auto floor=*original.Find(2);floor.id=1;floor.transform.position={90,-.5f,0};floor.body->halfExtents={30,.5f,30};
 Project project;require(project.Load("projects/post_m65_consumers/post_m65_consumers.judasproj",error),"consumer classifications");
 EngineHost host;require(host.Init("Imported rig repair checks",320,240,false,error),"host");host.GetWindow().SetTestInputMode(true);host.OpenProjectAssets(project.RootDir(),project.AssetsDir());host.Resources().GetMesh(rig.render->meshAsset,error);host.Resources().WaitForAll();
 for(int count:{1,10,20}){
  Scene scene;scene.Settings()=original.Settings();scene.Objects().push_back(floor);SceneObject gravity;gravity.id=2;gravity.gravity=SceneGravityComponent{};gravity.gravity->kind=SceneGravityKind::Uniform;gravity.gravity->regionShape=SceneRegionShape::Box;gravity.gravity->regionHalfExtents={1000,1000,1000};scene.Objects().push_back(gravity);
  std::vector<EntityId> owners;for(int i=0;i<count;++i){auto r=rig;r.id=200+i;r.transform.position={78.f+(i%5)*5,2.f,-8.f+(i/5)*5};scene.Objects().push_back(r);owners.push_back(r.id);}scene.SetNextId(500);
  RuntimeWorld world;world.legacyGameplay=false;require(world.Build(scene,&host.Resources(),error,&project.Settings().classification),"real mapped rig build");host.Resources().WaitForAll();for(int k=0;k<60;++k)world.UpdateAnimations(1.f/60);for(auto id:owners){if(!world.EnterRagdoll(id,error))throw std::runtime_error("Ride activation: "+error);require(true,"current Ride pose activation");}GameSession game;require(game.Begin(world,error),"normal fixed-step path");
  auto step=[&](int n){auto t=std::chrono::steady_clock::now();for(int j=0;j<n;++j)StepPlayedWorld(game,host.GetWindow(),1.f/60);return std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-t).count()/n;};
  auto asleep=[&](){unsigned sleeping=0;for(auto id:owners)for(const auto& b:rig.ragdoll->bones)sleeping+=world.Physics().IsSleeping(world.RuntimeBody(world.RagdollBody(id,b.joint)));return sleeping;};
  double settleMs=0;int sleepAt=-1;for(int t=0;t<1800;++t){settleMs+=step(1);if(t%60==59&&sleepAt<0&&asleep()==unsigned(count*13))sleepAt=t+1;}auto cost=settleMs/1800;auto resting=asleep();auto quietCost=step(120);std::cout<<"RIG sleep_latency_seconds="<<sleepAt/60.f<<" sleeping_fixed_ms="<<quietCost<<"\n";for(auto id:owners){unsigned n=0;for(const auto& b:rig.ragdoll->bones)n+=world.Physics().IsSleeping(world.RuntimeBody(world.RagdollBody(id,b.joint)));std::cout<<"ARTICULATION id="<<id<<" sleeping="<<n<<"/13\n";}std::cout<<"RIG count="<<count<<" mapped="<<count*13<<" sleeping="<<resting<<" fixed_ms="<<cost<<"\n";if(resting!=unsigned(count*13))for(const auto& b:rig.ragdoll->bones){auto h=world.RuntimeBody(world.RagdollBody(owners[0],b.joint));auto v=world.Physics().GetLinearVelocity(h),w=world.Physics().GetAngularVelocity(h);std::cout<<b.joint<<" resistance="<<b.constraint.rotationalResistance<<" v="<<glm::length(v)<<" w="<<glm::length(w)<<"\n";}require(resting==unsigned(count*13),"all actual rig members settle, not unrelated floor bodies");
  for(int cycle=0;cycle<3;++cycle){auto h=world.RuntimeBody(world.RagdollBody(owners[0],"mixamorig:Hips"));world.Physics().ApplyLinearImpulse(h,{20,3,0});require(!world.Physics().IsSleeping(h),"impact wakes connected island");if(cycle==2){auto head=world.RuntimeBody(world.RagdollBody(owners[0],"mixamorig:Head"));for(int k=0;k<120;++k){world.Physics().ApplyTorque(head,{0,.6f,0});step(1);}require(!world.Physics().IsSleeping(h),"continuously disturbed actual rig cannot sleep");}auto disturbanceCost=step(1800);std::cout<<"RIG resettle cycle="<<cycle<<" fixed_ms="<<disturbanceCost<<"\n";require(asleep()==unsigned(count*13),"physical disturbance resettles");}
  std::map<std::string,SaveChunk> chunks;require(WorldPersistence::Capture(world,chunks,error),"cold-save capture settled imported articulations");Scene saved;require(WorldPersistence::SceneFrom(chunks,saved,error),"cold-save snapshot scene");RuntimeWorld resumed;resumed.legacyGameplay=false;if(!resumed.Build(saved,&host.Resources(),error,&project.Settings().classification,nullptr,true))throw std::runtime_error("cold build: "+error);host.Resources().WaitForAll();resumed.UpdateAnimations(0);if(!WorldPersistence::Prepare(resumed,error))throw std::runtime_error("cold participant preflight: "+error);if(!WorldPersistence::Restore(resumed,chunks,error))throw std::runtime_error("cold restore: "+error);require(true,"cold process-style construction restores resistance and sleep");WorldPersistence::Published(resumed);require(resumed.RagdollActive(owners[0]),"restored articulation exists");
  auto head=resumed.RuntimeBody(resumed.RagdollBody(owners[0],"mixamorig:Head"));require(resumed.Physics().IsSleeping(head),"sleep state preserved for imported head");GameSession restoredGame;require(restoredGame.Begin(resumed,error),"resumed fixed path");StepPlayedWorld(restoredGame,host.GetWindow(),1.f/60);require(glm::length(resumed.Physics().GetAngularVelocity(head))<.03f,"first resumed step remains quiet");restoredGame.End();resumed.Destroy();
  auto root=world.RuntimeBody(world.RagdollBody(owners[0],"mixamorig:Hips"));world.DestroyEntity(1);step(2);require(!world.Physics().IsSleeping(root)&&world.Physics().GetLinearVelocity(root).y<0,"removing support wakes falling articulation");game.End();world.Destroy();
 }
 host.Shutdown();std::cout<<"Imported ragdoll checks "<<checks<<" PASS\n";return 0;
}catch(const std::exception& e){std::cerr<<"FAIL "<<e.what()<<" after "<<checks<<" checks\n";return 1;}}
