#include "Application.h"
#include "TestInput.h"
#include "EngineHost.h"
#include "InteractivePlay.h"
#include "SceneSession.h"
#include "WorldStreaming.h"
#include "RuntimeWorld.h"
#include "PerformanceProfiler.h"
#include "ScreenshotWriter.h"
#include <cmath>
#include <SDL2/SDL.h>
#include <atomic>
#include <chrono>
#include <thread>
#include <filesystem>
#include <fstream>
#include <cstdio>
namespace {void Quit(){SDL_Event e{};e.type=SDL_QUIT;SDL_PushEvent(&e);}int checks=0,failures=0;void check(bool value,const char* label){++checks;failures+=!value;std::printf("%s %s\n",value?"PASS":"FAIL",label);}}
int main(int argc,char** argv){std::string project=argc>1?argv[1]:"projects/streamed_range/streamed_range.judasproj";std::filesystem::path out=argc>2?argv[2]:"build/m59-app";std::filesystem::create_directories(out);
 std::atomic<bool> gate{false};unsigned frames=0,shotFrame=0,carryFrame=0;EntityId crate=0;glm::vec3 carryStart{0};int phase=0;uint64_t oldDemand=0;RuntimeWorld* rootWorld=nullptr;EntityId plate=0,navigator=0;std::string baseline;double liquidVolume=0;std::vector<double> work;ApplicationControl control;control.hidden=true;
 control.frameSeconds=[](float){return 1.f/60;};control.hostReady=[](EngineHost& host){SDL_GL_SetSwapInterval(0);host.GetWindow().SetTestInputMode(true);std::string error;host.Audio().Init(error,true);};
 control.beforeFrame=[&](EngineHost& host,RuntimeWorld& world,InteractivePlay&){
  // Exercise the authored carry branch even with an empty initial view.
  if(frames==31||frames==32)QueueTestKey(host.GetWindow(),SDL_SCANCODE_Q,frames==31);
  if(carryFrame&&frames==carryFrame){auto target=world.Physics().GetTransform(world.RuntimeBody(crate)).position;EntityPhysicalState player;world.GetEntityState(10,player);auto d=glm::normalize(target-(player.position+glm::vec3(0,.7f,0)));auto old=world.view->pose.rotation*glm::vec3(0,0,-1);SDL_Event motion{};motion.type=SDL_MOUSEMOTION;motion.motion.xrel=int(std::round(-(std::atan2(-d.x,-d.z)-std::atan2(-old.x,-old.z))/.0021f));motion.motion.yrel=int(std::round(-(std::asin(d.y)-std::asin(old.y))/.0021f));host.GetWindow().QueueTestPhysical("mouse:dx",float(motion.motion.xrel));host.GetWindow().QueueTestPhysical("mouse:dy",float(motion.motion.yrel));}
  if(carryFrame&&(frames==carryFrame+1||frames==carryFrame+2||frames==carryFrame+15||frames==carryFrame+16))QueueTestKey(host.GetWindow(),SDL_SCANCODE_Q,frames==carryFrame+1||frames==carryFrame+15);
  if(carryFrame&&(frames==carryFrame+7||frames==carryFrame+12))QueueTestKey(host.GetWindow(),SDL_SCANCODE_W,frames==carryFrame+7);
  if(carryFrame&&(frames==carryFrame+3||frames==carryFrame+4))QueueTestKey(host.GetWindow(),SDL_SCANCODE_F10,frames==carryFrame+3);
  if(shotFrame&&frames==shotFrame){EntityPhysicalState player;world.GetEntityState(10,player);auto delta=world.Physics().GetTransform(world.RuntimeBody(plate)).position-(player.position+glm::vec3(0,.7f,0));auto d=glm::normalize(delta);SDL_Event motion{};motion.type=SDL_MOUSEMOTION;motion.motion.xrel=int(std::round(-std::atan2(-d.x,-d.z)/.0021f));motion.motion.yrel=int(std::round(-std::asin(d.y)/.0021f));host.GetWindow().QueueTestPhysical("mouse:dx",float(motion.motion.xrel));host.GetWindow().QueueTestPhysical("mouse:dy",float(motion.motion.yrel));}
  if(shotFrame&&(frames==shotFrame+1||frames==shotFrame+2)){SDL_Event click{};click.type=frames==shotFrame+1?SDL_MOUSEBUTTONDOWN:SDL_MOUSEBUTTONUP;click.button.button=SDL_BUTTON_LEFT;host.GetWindow().QueueTestPhysical("mouse:Left",click.type==SDL_MOUSEBUTTONDOWN?1.f:0.f);}
 };
 control.worldReady=[&](EngineHost&,RuntimeWorld& world,InteractivePlay&){rootWorld=&world;std::string error;auto* stream=world.SceneControl()->Streaming(world,error);check(stream!=nullptr,"normal project manifest service");if(stream)stream->SetPreparationGate([&](const JobContext& ctx){while(!gate.load()&&!ctx.CancelRequested())std::this_thread::sleep_for(std::chrono::milliseconds(1));return !ctx.CancelRequested();});world.SceneControl()->Set("streamReview","123",error);};
 control.afterFrame=[&](EngineHost& host,RuntimeWorld& world,InteractivePlay& play){++frames;std::string error;auto* stream=world.SceneControl()->Streaming(world,error);if(!stream){check(false,error.c_str());Quit();return;}work.push_back(stream->Stats().integrationMs);
  if(frames==30){check(world.IsBuilt()&&world.Physics().AliveBodyCount()==2&&world.RuntimeBody(1).IsValid()&&world.RuntimeBody(10).IsValid()&&!world.Physics().IsDynamicBody(world.RuntimeBody(10)),"pending reads leave the root solid and massless motor proxy live");check(world.Scripts()&&world.Scripts()->Diagnostics().empty(),"root JS and localized UI execute during delayed load");check(world.SimulationTimeSeconds()>.1,"fixed simulation progresses during worker gate");gate=true;}
  if(frames==33)check(world.Scripts()->Diagnostics().empty(),"carry action against empty space does not disable player callbacks");
  auto active=[&](const char* name){for(auto& r:stream->Regions())if(r.id==name)return r.state=="active";return false;};
  if(phase==0&&active("gallery-0")){check(rootWorld==&world&&world.SceneControl()->Current()=="Scenes/bootstrap.judas","additive load preserves played world/root identity");check(world.UIIfLoaded()&&world.UI().Find("range_ui"),"persistent M58 UI survives activation");plate=stream->Resolve("gallery-0",100);auto joint=stream->Resolve("gallery-0",101);check(plate&&joint&&plate!=100&&world.RuntimeJoint(joint).IsValid(),"region local hinge IDs bind to ordinary physics");
   auto path=world.Navigation().FindPath({5,.1f,0},{5,.1f,-24});check(path.status==NavigationPath::Status::Complete,"cross-region route through ordinary explicit link");
   auto target=world.Physics().GetTransform(world.RuntimeBody(plate));auto before=world.Physics().GetLinearVelocity(world.RuntimeBody(plate));world.Physics().ApplyImpulseAtPoint(world.RuntimeBody(plate),{0,0,-8},target.position);check(world.Physics().GetLinearVelocity(world.RuntimeBody(plate))!=before,"streamed target receives real hit-point impulse");
   shotFrame=frames+45;QueueTestKey(host.GetWindow(),SDL_SCANCODE_F9,true);phase=1;
  }else if(phase==1&&active("gallery-1")){QueueTestKey(host.GetWindow(),SDL_SCANCODE_F9,false);check(true,"first F9 requests next gallery through real project input");auto other=stream->Resolve("gallery-1",100);check(other&&other!=plate,"adjacent scenes with identical IDs stay independent");check(world.Navigation().FindPath({5,.1f,-24},{5,.1f,-48}).status==NavigationPath::Status::Complete,"region-to-region navigation seam");
   auto actor=stream->Resolve("gallery-0",1000); // adopted by project JS, thus qualified source no longer owns it
   check(!actor,"travelling navigator adopted by ordinary project JS");for(auto id:world.QueryEntities(CategoryBit(2)))if(world.RuntimeCharacter(id)&&stream->Owner(id)=="root")navigator=id;check(navigator!=0,"ordinary prefab motor remains root-owned after adoption");
   QueueTestKey(host.GetWindow(),SDL_SCANCODE_F7,true);phase=2;
  }else if(phase==2&&active("liquid")){QueueTestKey(host.GetWindow(),SDL_SCANCODE_F7,false);check(true,"F7 requests liquid through real project input");world.UpdateLiquids(1./30);auto owner=stream->Resolve("liquid",10);auto h=world.Liquids().Handle(owner);check(h.id!=0,"required liquid resources ready at activation");liquidVolume=world.Liquids().Accounting("water").total;phase=3;
  }else if(phase==3&&navigator&&world.RuntimeDefinition(navigator)&&world.RuntimeDefinition(navigator)->transform.position.z>-11){check(world.RuntimeCharacter(navigator)!=nullptr,"real CharacterMotor navigator crosses additive seam through normal scripted link");auto rows=stream->Regions();auto r=std::find_if(rows.begin(),rows.end(),[](auto& r){return r.id=="liquid";});check(r!=rows.end()&&r->state=="active"&&!r->pins.empty(),"conserved liquid region remains explicitly pinned");check(std::abs(world.Liquids().Accounting("water").total-liquidVolume)<1e-9,"pin/release does not recreate initial liquid");check(world.Scripts()->Diagnostics().empty(),"project player/targets/navigator/residency scripts remain healthy");auto records=world.Scripts()->Capture();auto playerRecord=std::find_if(records.begin(),records.end(),[](auto& r){return r.entity==10;});if(playerRecord!=records.end())std::printf("PLAYER_SHOT %s\n",playerRecord->json.c_str());check(playerRecord!=records.end()&&playerRecord->json.find("\"score\":100")!=std::string::npos,"actual logical look/fire scores on a streamed physical target through project JS");std::vector<unsigned char> pixels;host.GetRenderer().CaptureFrame(host.GetWindow().Width(),host.GetWindow().Height(),pixels);check(WriteRgbPng((out/"game.png").string(),host.GetWindow().Width(),host.GetWindow().Height(),pixels),"ordinary actual-GL game screenshot");baseline=world.BaselineFingerprint();check(baseline.size()==64,"full authored composition baseline finishes asynchronously");
   crate=stream->Resolve("gallery-0",30);check(crate!=0,"streamed physical prop available for actual carry control");auto t=world.RuntimeDefinition(10)->transform;t.position=world.Physics().GetTransform(world.RuntimeBody(crate)).position+glm::vec3(0,0,3);t.position.y=.9f;world.SetRuntimeTransform(10,t);world.RuntimeCharacter(10)->velocity={0,0,0};carryStart=world.Physics().GetTransform(world.RuntimeBody(crate)).position;carryFrame=frames+3;phase=6;
  }else if(phase==6&&frames==carryFrame+6){check(stream->Owner(crate)=="root","Q raycast picks/adopts physical prop using public viewRay property");check(world.Scripts()->Diagnostics().empty(),"carry branch leaves player callbacks active");bool released=true;for(auto& r:stream->Regions())released&=r.demands==0;check(released,"F10 releases every manual demand through project input");check(active("liquid"),"F10 preserves safety-pinned conserved liquid");
  }else if(phase==6&&frames==carryFrame+18){check(glm::length(world.Physics().GetTransform(world.RuntimeBody(crate)).position-carryStart)>.1f,"carried prop responds to ordinary finite forces");check(world.RuntimeDefinition(10)->transform.position.z<carryStart.z+2.9f,"movement still responds after carry action");check(world.Scripts()->Diagnostics().empty(),"Q release and function keys keep demo fault-free");
   gate=false;oldDemand=stream->Request("oblique",false,error);stream->Advance(false);check(stream->Status(oldDemand)&&stream->Status(oldDemand)->state=="preparing","whole replacement occurs with an actual read outstanding");check(world.Localization().SetLocale("de",error),"session locale switch queues through ordinary M58 service");check(world.SceneControl()->Reload(error),"whole-world reload remains available");phase=4;
  }else if(phase==4&&rootWorld!=&world){check(!stream->Status(oldDemand),"whole replacement invalidates old request token");check(play.WorldStatePath().empty(),"composed disk saves remain disabled after whole reload");check(host.Resources().Jobs()->Stats().cancelled>0,"old-world held worker observes cancellation");check(!world.RuntimeDefinition(plate),"old region handles do not resurrect");check(world.SceneControl()->Get("streamReview")=="123","bounded session state survives whole replacement");check(world.UIIfLoaded()&&world.UI().Find("range_ui"),"fresh world UI constructed after reload");phase=5;}
  if(phase==5&&frames>120){check(world.Scripts()&&world.Scripts()->Diagnostics().empty(),"reload cleanup/start has no script faults");check(host.Resources().Jobs()->Stats().running<=16,"normal bounded worker pool");check(world.Localization().Locale()=="de","locale survives additive activation and whole-world replacement");PerformanceProfiler::Get().Export((out/"profile.json").string(),error);Quit();}
  if(frames%300==0){for(auto& r:stream->Regions())std::printf("STATE %s %s %s\n",r.id.c_str(),r.state.c_str(),r.error.c_str());for(auto& d:world.Scripts()->Diagnostics())std::printf("FAULT %s\n",d.message.c_str());}
  std::this_thread::sleep_for(std::chrono::milliseconds(1));
  if(frames>1200){check(false,"application phase deadline");Quit();}
 };
 Application app;char program[]="judas";char* arguments[]={program,project.data()};int result=app.Run(2,arguments,&control);check(result==0,"normal standalone application exits");std::ofstream stats(out/"summary.json");stats<<"{\"baseline\":\""<<baseline<<"\",\"checks\":"<<checks<<",\"failures\":"<<failures<<",\"frames\":"<<frames<<",\"integration_ms\":[";for(size_t i=0;i<work.size();++i){if(i)stats<<",";stats<<work[i];}stats<<"]}\n";std::printf("M59 application %d checks %d failures\n",checks,failures);return failures?1:0;
}
