#include "EngineHost.h"
#include "Renderer.h"
#include "ScreenshotWriter.h"
#include "PerformanceProfiler.h"
#include <filesystem>
#include <fstream>
#include <cstdio>
#include <cmath>
#include <algorithm>
namespace fs=std::filesystem;int checks=0,failures=0;void Check(bool x,const char* s){++checks;failures+=!x;std::printf("%s %s\n",x?"PASS":"FAIL",s);}
std::string Scalar(unsigned u){std::string s;if(u<128)s+=char(u);else if(u<2048){s+=char(192|(u>>6));s+=char(128|(u&63));}else{s+=char(224|(u>>12));s+=char(128|((u>>6)&63));s+=char(128|(u&63));}return s;}
int main(int argc,char** argv){fs::path out=argc>1?argv[1]:"build/m58-gl";fs::create_directories(out);std::string error;EngineHost host;Check(host.Init("M58 real glyphs",640,360,false,error),"normal GL renderer context");if(failures)return 1;auto& r=host.GetRenderer();std::printf("GL %s / %s\n",glGetString(GL_VENDOR),glGetString(GL_RENDERER));
 std::vector<std::shared_ptr<const TextFont>> fonts;for(auto name:{"DejaVuSans.ttf","NotoSansArabic-Regular.ttf","NotoSansDevanagari-Regular.ttf","NotoSansJP-Regular.otf"}){std::shared_ptr<const TextFont> font;Check(LoadTextFont(std::string("projects/text_lab/Assets/fonts/")+name,font,error),name);fonts.push_back(font);}r.SelectTextFonts(fonts);TextOptions o;o.pixels=32;o.width=610;o.wrap=true;auto layout=r.LayoutText("Café é / مرحبا 123 / क्षि / 日本語 / 😀",o);glm::vec2 position{16,20};
 auto draw=[&](const TextLayout& l,float exposure,bool clip){r.SetSceneAppearance(true,exposure,{},1,{1,0,0,0},false);r.BeginFrame(640,360);r.EndFrame();r.BeginUIFrame(640,360);r.DrawUIRect({0,0},{640,360},{0,0,0,1});if(clip)r.SetUIClip({16,20},{90,50});r.DrawTextLayout(l,position,{1,1,1,1});r.ClearUIClip();r.EndUIFrame();std::vector<unsigned char> image;r.CaptureFrame(640,360,image);return image;};auto image=draw(*layout,1,false);WriteRgbPng((out/"mixed.png").string(),640,360,image);
 // Independent CPU bilinear coverage oracle at the positions measured by the layout.
 TextEngine rasterizer;std::vector<double> expected(640*360);for(auto& g:layout->glyphs){TextRaster b;Check(rasterizer.Raster(g,o.pixels,b,error),"FT coverage available for submitted glyph");float left=position.x+g.x+b.left,top=position.y+g.y-b.top;for(int y=std::max(0,int(std::floor(top)));y<std::min(360,int(std::ceil(top+b.height)));++y)for(int x=std::max(0,int(std::floor(left)));x<std::min(640,int(std::ceil(left+b.width)));++x){if(x+.5<left||x+.5>=left+b.width||y+.5<top||y+.5>=top+b.height)continue;double u=x-left,v=y-top;int ix=int(std::floor(u)),iy=int(std::floor(v));double alpha=0;for(int dy=0;dy<2;++dy)for(int dx=0;dx<2;++dx){int a=ix+dx,z=iy+dy;if(a>=0&&a<b.width&&z>=0&&z<b.height)alpha+=b.coverage[z*b.width+a]/255.0*(dx?u-ix:1-u+ix)*(dy?v-iy:1-v+iy);}auto& p=expected[y*640+x];p=alpha+p*(1-alpha);}}
 unsigned differing=0,covered=0;double maxError=0;for(size_t p=0;p<expected.size();++p){double delta=std::abs(expected[p]*255-image[p*3]);covered+=expected[p]>.01;differing+=delta>4;maxError=std::max(maxError,delta);}std::printf("COVERAGE pixels=%u mismatched=%u max=%.2f\n",covered,differing,maxError);Check(covered>1000&&differing<covered/50,"actual GL glyph placement/coverage agrees with independent CPU raster positions");Check(r.UIDrawCalls()<layout->glyphs.size()/2,"consecutive compatible glyphs batched in hierarchy order");auto warm=r.TextStats();Check(draw(*layout,12,false)==image&&r.TextStats().rasters==warm.rasters,"warm glyphs do not rerasterize / UI is exposure independent");auto clipped=draw(*layout,.1f,true);unsigned outside=0,inside=0;for(int y=0;y<360;++y)for(int x=0;x<640;++x){auto value=clipped[(y*640+x)*3];if(x<16||x>=106||y<20||y>=70)outside+=value>0;else inside+=value>0;}Check(outside==0&&inside>0,"real GL rectangular text clipping");
 auto generation=r.TextAtlasGeneration();TextOptions large;large.pixels=170;std::string dense;for(unsigned c=0x4e00;c<0x4e00+900;++c)dense+=Scalar(c);auto stress=r.LayoutText(dense,large);r.BeginUIFrame(640,360);r.DrawTextLayout(*stress,{0,0},{1,1,1,1});r.EndUIFrame();Check(r.TextAtlasBytes()<=32*1024*1024&&r.TextAtlasGeneration()>generation,"bounded eight-page atlas evicts under real CJK glyph pressure");Check(draw(*layout,1,false)==image,"retained layout rerasterizes correctly after atlas eviction; no stale UVs");r.ResetProjectText();r.SelectTextFonts(fonts);Check(draw(*layout,1,false)==image,"font/project reset leaves retained CPU glyph identities safe");
 auto& profiler=PerformanceProfiler::Get();profiler.Enable(true);
 for(bool multilingual:{false,true}){r.ResetProjectText();r.SelectTextFonts(multilingual?fonts:std::vector<std::shared_ptr<const TextFont>>{fonts[0]});profiler.Clear();auto rasterBefore=r.TextStats().rasters;
 for(int frame=0;frame<120;++frame){profiler.BeginFrame(multilingual?"M58 100 multilingual labels":"M58 100 ASCII labels",frame==0);r.BeginFrame(640,360);r.EndFrame();r.BeginUIFrame(640,360);for(int i=0;i<100;++i){auto text=i<99?(multilingual?"Café مرحبا क्षि 日本語":"Score / Pause / Resume"):"score "+std::to_string(frame);auto l=r.LayoutText(text,TextOptions{});r.DrawTextLayout(*l,{float(i%5)*125,float(i/5)*18},{1,1,1,1});}r.EndUIFrame();profiler.EndFrame();}
 auto name=multilingual?"100-labels-profile.json":"ascii-profile.json";Check(profiler.Export((out/name).string(),error),"M56 profile exports cold/warm/changing HUD/layout/glyph/cache/draw evidence");auto stats=r.TextStats();auto timing=profiler.Summary();auto frames=profiler.History();double cold=frames.empty()?0:(frames[0].end-frames[0].start)/1e6;std::printf("PERFORMANCE %s 100 labels cold_ms=%.4f median_ms=%.4f p95_ms=%.4f max_ms=%.4f atlas_bytes=%zu layout_bytes=%zu font_bytes=%zu new_rasters=%llu draws=%u\n",multilingual?"multilingual":"ASCII",cold,timing.median,timing.p95,timing.maximum,r.TextAtlasBytes(),stats.layoutBytes,stats.fontBytes,(unsigned long long)(stats.rasters-rasterBefore),r.UIDrawCalls());}
 profiler.Enable(false);Check(glGetError()==GL_NO_ERROR,"GL text/eviction/clip/scale has no errors");host.Shutdown();std::printf("SUMMARY %d checks %d failures\n",checks,failures);return failures?1:0;}
