#include "TextLayout.h"
#include "Localization.h"
#include "Project.h"
#include "RuntimeUI.h"
#include "AssetDatabase.h"
#include "ResourceManager.h"
#include "JobSystem.h"
#include "SceneSerialization.h"
#include "SceneFingerprint.h"
#include "fixtures/m58/reference.h"
#include <unicode/uchar.h>
#include <unicode/locid.h>
#include <unicode/ulocdata.h>
#include <unicode/ubidi.h>
#include <filesystem>
#include <fstream>
#include <cstdio>
#include <cmath>
#include <algorithm>
#include <locale>
#include <chrono>
namespace fs=std::filesystem;int checks=0,failures=0;
void Check(bool x,const char* s){++checks;failures+=!x;std::printf("%s %s\n",x?"PASS":"FAIL",s);}
std::string Read(const fs::path& p){std::ifstream f(p);return {std::istreambuf_iterator<char>(f),{}};}
std::shared_ptr<const TextFont> Font(const char* name){std::shared_ptr<const TextFont> f;std::string e;Check(LoadTextFont(std::string("projects/text_lab/Assets/fonts/")+name,f,e),name);return f;}
template<size_t N> void Reference(TextEngine& engine,std::shared_ptr<const TextFont> font,const char* text,const char* locale,const ReferenceGlyph(&expected)[N],const char* label){TextOptions o;o.locale=locale;auto l=engine.Layout(text,{font},o);bool match=l->glyphs.size()==N;float pen=0;for(size_t i=0;i<std::min(N,l->glyphs.size());++i){auto& g=l->glyphs[i];auto& r=expected[i];match&=g.glyph==r.glyph&&g.cluster==r.cluster&&std::abs(g.x-(pen+r.dx/64.f))<.02f&&std::abs(g.y-(l->lines[0].baseline-r.dy/64.f))<.02f;pen+=r.advance/64.f;}Check(match&&std::abs(pen-l->width)<.02f,label);}
struct Comma:std::numpunct<char>{char do_decimal_point()const override{return ',';}};
int main(int argc,char** argv){fs::path out=argc>1?argv[1]:"build/m58-text";fs::create_directories(out);std::string error;
 auto latin=Font("DejaVuSans.ttf"),arabic=Font("NotoSansArabic-Regular.ttf"),indic=Font("NotoSansDevanagari-Regular.ttf"),jp=Font("NotoSansJP-Regular.otf");if(failures)return 1;TextEngine t;TextOptions o;
 Check(ValidTextUTF8("Café é 😀",error),"strict UTF-8 accepts combining and supplementary scalars");Check(!ValidTextUTF8(std::string("\xc0\xaf",2),error)&&!ValidTextUTF8(std::string("\xed\xa0\x80",3),error),"overlong and surrogate UTF-8 rejected");Check(t.Layout(std::string("bad\xff",4),{latin},o)->replacedInput,"runtime malformed sequence replaced safely");
 Check(t.Layout("",{latin},o)->lines.size()==1&&t.Layout("a\r\nb\n",{latin},o)->lines.size()==3,"empty text and mandatory CRLF/trailing paragraph");auto supplementary=t.Layout("A😀B",{latin},o);Check(supplementary->lines[0].end==4&&supplementary->glyphs.size()==3,"supplementary is one scalar / two UTF-16 units, no truncation");
 Reference(t,arabic,"مرحبا بالعالم","ar",arabicReference,"Arabic glyph IDs/clusters/positions match independent upstream hb-shape");Reference(t,indic,"नमस्ते दुनिया क्षि","hi",indicReference,"Indic reordered glyph IDs/positions match upstream hb-shape");Reference(t,latin,"Café AV office","en",marksReference,"marks / ligature / kerning match upstream hb-shape");
 auto missing=t.Layout("नमस्ते",{latin},o),fallback=t.Layout("नमस्ते",{latin,indic},o);Check(missing->missingClusters>0&&fallback->missingClusters==0&&std::all_of(fallback->glyphs.begin(),fallback->glyphs.end(),[&](auto& g){return g.font==indic&&g.glyph!=0;}),"genuinely missing DejaVu coverage falls back as whole Indic run");
 auto tall=t.Layout("a क्षि",{latin,indic},o);bool baseline=true;for(auto& g:tall->glyphs){TextRaster raster;if(!t.Raster(g,o.pixels,raster,error)){baseline=false;break;}baseline&=g.y-raster.top>=-2&&g.y-raster.top+raster.height<=tall->height+2;}Check(baseline,"mixed font marks fit real baseline/ascent/descent");
 auto unsupported=t.Layout("\xf4\x8f\xbf\xbf",{latin,jp},o);Check(unsupported->missingClusters&&unsupported->glyphs[0].glyph==0,"unsupported valid scalar retains visible primary .notdef");
 // Independent expected order for Hebrew + ASCII digits, UAX#9 LTR paragraph.
 auto bidi=t.Layout("abc אבג 123",{latin},o);std::vector<unsigned> visual;for(auto& g:bidi->glyphs)visual.push_back(g.cluster);Check(visual==std::vector<unsigned>({0,1,2,3,8,9,10,7,6,5,4}),"mixed bidi ASCII numbers stay LTR inside reversed Hebrew run (UAX9 expectation)");
 o.wrap=true;o.width=60;auto cjk=t.Layout("日本語の文章は空白がなくても改行できます。",{latin,jp},o);Check(cjk->lines.size()>2&&std::all_of(cjk->lines.begin(),cjk->lines.end(),[&](auto& l){return l.width<=o.width+1;}),"CJK wraps without spaces using ICU break opportunities");
 auto wrapped=t.Layout("abc אבג 123 abc אבג 456",{latin},o);Check(wrapped->lines.size()>2,"wrapped mixed bidi reshapes each line");bool coherent=true;for(auto& line:wrapped->lines)for(auto& g:wrapped->glyphs)if(g.cluster>=line.start&&g.cluster<line.end)coherent&=g.y>=line.baseline-30&&g.y<=line.baseline+30;Check(coherent,"wrapped lines keep logical cluster/baseline membership");
 // Independent ICU visual-index oracle: no shaping/segmentation wrapper is used here.
 auto source=icu::UnicodeString::fromUTF8("abc אבג 123 abc אבג 456");UErrorCode bidiError=U_ZERO_ERROR;auto* paragraph=ubidi_open();ubidi_setPara(paragraph,source.getBuffer(),source.length(),UBIDI_DEFAULT_LTR,nullptr,&bidiError);bool visualLines=true;
 for(auto& line:wrapped->lines){auto* view=ubidi_open();ubidi_setLine(paragraph,line.start,line.end,view,&bidiError);std::vector<int32_t> order(line.end-line.start);ubidi_getVisualMap(view,order.data(),&bidiError);std::vector<unsigned> actual,expected;for(auto& g:wrapped->glyphs)if(g.cluster>=line.start&&g.cluster<line.end)actual.push_back(g.cluster);for(auto i:order)expected.push_back(line.start+i);visualLines&=actual==expected;ubidi_close(view);}ubidi_close(paragraph);Check(U_SUCCESS(bidiError)&&visualLines,"wrapped mixed bidi visual glyph order matches independent ICU visual map");
 o.width=3;auto cluster=t.Layout("éक्षि",{latin,indic},o);Check(std::none_of(cluster->lines.begin(),cluster->lines.end(),[](auto& l){return l.end==1||l.end==3||l.end==4;}),"emergency wrapping never cuts combining/Indic clusters");
 o.wrap=false;o.width=200;o.direction=TextDirection::RTL;o.alignment=TextAlignment::Start;auto right=t.Layout("אבג",{latin},o);Check(right->glyphs[0].x>150,"RTL logical start resolves right");o.alignment=TextAlignment::Left;Check(t.Layout("אבג",{latin},o)->glyphs[0].x==0,"explicit left remains left under RTL");o={};auto cached=t.Layout("cache",{latin},o);auto stats=t.Stats();Check(t.Layout("cache",{latin},o)==cached&&t.Stats().shapes==stats.shapes,"unchanged layout cache avoids reshaping");for(int i=0;i<300;++i)t.Layout(std::to_string(i),{latin},o);Check(cached->glyphs[0].font==latin,"layout eviction does not invalidate retained immutable font/glyph identities");
 Project p;Check(p.Load("projects/text_lab/text_lab.judasproj",error),"ordinary localized project parses");ProjectSettings decoded;Check(Project::ParseFromString(Project::SerializeToString(p.Settings()),decoded,error)&&decoded.localization.Encode()==p.Settings().localization.Encode(),"project locale/font stable ID round trip"); {Project range;range.Load("projects/shooter_game/shooter_game.judasproj",error);auto before=Project::SerializeToString(range.Settings());Scene original;LoadSceneFromFile(range.StartupScenePath(),original,error);std::string sceneBefore;SaveSceneToString(original,sceneBefore);auto old=std::locale();std::locale::global(std::locale(std::locale::classic(),new Comma));Project numeric;Scene sceneAfter;std::string saved;bool ok=numeric.Load("projects/shooter_game/shooter_game.judasproj",error)&&Project::SerializeToString(numeric.Settings())==before&&LoadSceneFromFile(numeric.StartupScenePath(),sceneAfter,error);if(ok)SaveSceneToString(sceneAfter,saved);std::locale::global(old);Check(ok&&saved==sceneBefore,"comma process numeric locale preserves project input/navigation parsing and scene bytes");}
AssetDatabase assets;assets.Scan(p.RootDir(),p.AssetsDir());Check(assets.Problems().empty()&&ValidateLocalizationAssets(p.Settings().localization,assets,error),"registered font/catalog dependencies validate");ResourceManager resources(nullptr,&assets);resources.SetBlockingMode(true);
 {LocalizationSession l(p.Settings().localization);l.Bind(&resources);l.Refresh();Check(l.Format("lab.named",{{"first","A"},{"second","B"}},error)=="B — A","named placeholders reorder whole messages");Check(l.Format("lab.named",{{"first","{other}"},{"second","B"}},error)=="B — {other}","argument strings are data, not executable templates");Check(l.Format("missing.key",{},error)=="[missing.key]"&&!error.empty(),"missing key visible fallback and diagnostic");auto rev=l.Revision();Check(!l.SetLocale("unknown",error)&&l.Locale()=="en"&&l.Revision()==rev,"invalid locale cannot half-publish state");Check(l.SetLocale("ru",error)&&l.Format("lab.count",{{"count",22.0}},error)=="22 цели"&&l.Format("lab.count",{{"count",5.0}},error)=="5 целей","Russian few/many CLDR plural rules");Check(l.Format("lab.fallback",{},error)=="Default catalog fallback","missing requested message resolves project default");l.SetLocale("ar",error);Check(l.RTL()&&l.Format("lab.count",{{"count",2.0}},error)=="هدفان","Arabic two category and locale direction");l.Format("lab.count",{{"count","bad"}},error);Check(!error.empty(),"wrong plural argument type rejected");l.SetLocale("de",error);Check(l.Number(1234.5,{1,1,true},error)=="1.234,5","explicit German number formatting independent of host locale");l.SetLocale("ja",error);Check(l.Number(1234,{0,0,false},error)=="1234","bounded locale number options");}
 Catalog cat;Check(!ParseCatalog("JudasCatalog 1 \"en\"\n\"x\" \"{n,plural,one{bad}\"",cat,error),"malformed pattern rejected at import");Check(!ParseCatalog("JudasCatalog 1 \"en\"\n\"x\" \"{n,date}\"",cat,error)&&!ParseCatalog("JudasCatalog 1 \"en\"\n\"x\" \"{0}\"",cat,error),"unsupported date/positional types rejected at import");Check(!ParseCatalog("JudasCatalog 1 \"en\"\n\"x\" \"a\"\n\"x\" \"b\"",cat,error),"duplicate stable key rejected");auto cycle=p.Settings().localization;cycle.locales["en"].fallback="ar";Check(!cycle.Validate(error),"configured fallback cycles rejected");
 UIDocument doc;UIElement root;root.id="root";root.kind=UIKind::Canvas;doc.elements.push_back(root);UIElement label;label.id="label";label.parent="root";label.text="é 😀";label.textKey="lab.caption";label.textLogicalAlign=3;label.direction=TextDirection::RTL;doc.elements.push_back(label);UIDocument copy;Check(ParseUIDocument(SerializeUIDocument(doc),copy,error)&&copy.elements[1].text==label.text&&copy.elements[1].textKey==label.textKey,"authored UTF-8/key/direction UI v2 round trip");doc.elements[1].text="\xff";Check(!doc.Validate(error),"authored malformed text fails validation");doc.elements[1].text="valid";doc.elements[1].textKey=std::string("bad\0key",7);Check(!doc.Validate(error),"authored localization key rejects embedded NUL");doc.elements[1].textKey="";doc.elements[1].id="\xff";Check(!doc.Validate(error),"authored element identity also rejects malformed UTF-8");
 UVersionInfo v;u_getUnicodeVersion(v);UVersionInfo cldr;UErrorCode dataError=U_ZERO_ERROR;ulocdata_getCLDRVersion(cldr,&dataError);Check(U_SUCCESS(dataError)&&cldr[0]==46,"linked runtime CLDR data version verified");std::printf("VERSIONS ICU=%s Unicode=%d.%d CLDR=%d.%d\n",U_ICU_VERSION,v[0],v[1],cldr[0],cldr[1]);
 std::printf("SUMMARY %d checks %d failures\n",checks,failures);return failures?1:0;}
