#include "WorldPersistence.h"
#include "RuntimeWorld.h"
#include "ResourceManager.h"
#include "SceneSerialization.h"
#include "UniformGravity.h"
#include "CharacterMotor.h"
#include <cstdio>
#include <filesystem>
#include <fstream>
int checks=0,failures=0;
void Check(bool b,const char* s){++checks;failures+=!b;std::printf("%s %s\n",b?"PASS":"FAIL",s);}
int main(){
 std::string error;Scene scene;
 auto floorId=scene.CreateObject("support").id;auto* floor=scene.Find(floorId);floor->body=SceneBodyComponent{};floor->body->halfExtents={8,.5,8};floor->transform.position={0,-.5,0};
 auto bodyId=scene.CreateObject("ordinary body").id;auto* body=scene.Find(bodyId);body->body=SceneBodyComponent{};body->body->motion=SceneBodyMotion::Dynamic;body->body->managed=true;body->transform.position={3,2,0};
 auto motorId=scene.CreateObject("generic motor").id;scene.Find(motorId)->characterMotor=CharacterMotorSettings{};scene.Find(motorId)->transform.position={0,.92,0};
 scene.Find(motorId)->navigationAgent=NavigationAgentSettings{};
 auto linkId=scene.CreateObject("explicit link").id;scene.Find(linkId)->navigationLink=NavigationLinkSettings{};
 auto childId=scene.CreateObject("child").id;scene.Find(childId)->parent=bodyId;scene.Find(childId)->transform.position={0,1,0};scene.Find(childId)->render=SceneRenderComponent{};
 RuntimeWorld source,destination;Check(source.Build(scene,nullptr,error),"baseline world construction");auto native=source.RuntimeBody(bodyId);source.Physics().SetLinearVelocity(native,{1,2,3});source.UpdateCharacters(1.f/60);auto* motor=source.RuntimeCharacter(motorId);motor->velocity={4,0,0};motor->result.support=source.RuntimeBody(floorId);motor->result.supported=true;motor->result.supportVelocity={1,0,0};
 source.Navigation().RegisterAgent(motorId);auto* agent=source.Navigation().Agent(motorId);agent->hasDestination=true;agent->destination={0,0,-8};agent->onLink=true;agent->elapsed=.37;agent->path.status=NavigationPath::Status::Complete;agent->path.corners.push_back({{0,0,0},linkId,{0,0,-2}});
 source.Physics().ApplyForce(native,{2,0,0});
 SceneObject runtime;runtime.name="runtime";runtime.body=SceneBodyComponent{};runtime.body->motion=SceneBodyMotion::Dynamic;runtime.body->managed=true;runtime.transform.position={10,3,0};auto created=source.CreateEntity(runtime,nullptr,&error);
 std::map<std::string,SaveChunk> chunks;Check(WorldPersistence::Capture(source,chunks,error),"capture stable body/motor/runtime hierarchy state");if(!error.empty())std::puts(error.c_str());Scene restored;Check(WorldPersistence::SceneFrom(chunks,restored,error),"decode scene participant");if(!error.empty()){std::puts(error.c_str());return 1;}Check(destination.Build(restored,nullptr,error,nullptr,nullptr,true),"normal private construction from resolved snapshot");Check(WorldPersistence::Prepare(destination,error)&&WorldPersistence::Restore(destination,chunks,error),"participant restore/fixup");if(!error.empty())std::puts(error.c_str());
 EntityPhysicalState actual;destination.GetEntityState(bodyId,actual);Check(actual.linearVelocity==glm::vec3(1,2,3),"rigid momentum exact");Check(destination.RuntimeCharacter(motorId)->velocity==glm::vec3(4,0,0)&&destination.RuntimeCharacter(motorId)->result.support.id==destination.RuntimeBody(floorId).id,"motor velocity/support reference restored");Check(destination.RuntimeDefinition(created)&&destination.NextRuntimeEntityId()==source.NextRuntimeEntityId(),"runtime ID and allocation counter durable");Check(destination.RuntimeDefinition(childId)->parent==bodyId,"hierarchy stable identity retained");Check(destination.Physics().AliveBodyCount()==source.Physics().AliveBodyCount(),"no duplicate runtime bodies");Check(destination.Navigation().Agent(motorId)->onLink&&destination.Navigation().Agent(motorId)->path.corners[0].link==linkId&&std::abs(destination.Navigation().Agent(motorId)->elapsed-.37)<1e-6,"explicit navigation handoff resumes without new scripted action");
 Check(destination.RuntimeCharacter(motorId)->result.supportVelocity==glm::vec3(1,0,0),"support-following observation retained independently of gravity");
 source.Physics().Step(1.f/60);destination.Physics().Step(1.f/60);Check(glm::length(source.Physics().GetLinearVelocity(native)-destination.Physics().GetLinearVelocity(destination.RuntimeBody(bodyId)))<1e-6,"pending authoritative forces survive first resumed step");
 Check(!destination.Physics().IsDynamicBody(native),"old world native body handle cannot alias restored body");
 auto corrupt=chunks;corrupt["motors"].data.pop_back();RuntimeWorld rejected;rejected.Build(restored,nullptr,error,nullptr,nullptr,true);Check(!WorldPersistence::Restore(rejected,corrupt,error)&&destination.RuntimeDefinition(created),"truncated participant rejects private world without changing live world");
 auto missing=chunks;missing.erase("liquid");RuntimeWorld rejectedMissing;rejectedMissing.Build(restored,nullptr,error,nullptr,nullptr,true);WorldPersistence::Prepare(rejectedMissing,error);Check(!WorldPersistence::Restore(rejectedMissing,missing,error),"missing required participant rejects");
 auto newer=chunks;newer["motors"].version=99;RuntimeWorld rejectedNewer;rejectedNewer.Build(restored,nullptr,error,nullptr,nullptr,true);Check(!WorldPersistence::Restore(rejectedNewer,newer,error),"newer participant rejects before publication");
 Check(source.SetTransientEntity(created,true,error)&&!source.SetTransientEntity(motorId,true,error),"explicit simple transient accepted but required motor cannot be excluded");
 Check(source.DestroyHierarchy(bodyId,error),"destroy authored hierarchy through normal lifecycle");chunks.clear();error.clear();Check(WorldPersistence::Capture(source,chunks,error)&&WorldPersistence::SceneFrom(chunks,restored,error),"destroyed hierarchy capture");if(!error.empty())std::puts(error.c_str());Check(!restored.Find(bodyId),"destroyed authored entity does not resurrect");
 Scene touches;auto support=touches.CreateObject("static").id;touches.Find(support)->body=SceneBodyComponent{};auto touching=touches.CreateObject("touching sensor").id;auto* sensor=touches.Find(touching);sensor->body=SceneBodyComponent{};sensor->body->motion=SceneBodyMotion::Dynamic;sensor->body->managed=true;sensor->body->sensor=true;sensor->transform.position={0,.5,0};RuntimeWorld contactSource,contactRestored;contactSource.Build(touches,nullptr,error);contactSource.Physics().Step(1.f/60);chunks.clear();WorldPersistence::Capture(contactSource,chunks,error);WorldPersistence::SceneFrom(chunks,restored,error);contactRestored.Build(restored,nullptr,error,nullptr,nullptr,true);WorldPersistence::Prepare(contactRestored,error);Check(WorldPersistence::Restore(contactRestored,chunks,error),"authoritative contact history restored");contactRestored.Physics().Step(1.f/60);const auto& events=contactRestored.Physics().LastStepTouchEvents();Check(events.size()==1&&events.front().phase==PhysicsWorld::TouchPhase::Stay,"first resumed touching pair reports stay, never replays enter");
 Scene boot;auto bootMotor=boot.CreateObject("boot motor").id;boot.Find(bootMotor)->characterMotor=CharacterMotorSettings{};boot.Find(bootMotor)->navigationAgent=NavigationAgentSettings{};
 RuntimeWorld bootSource,bootRestored;bootSource.Build(boot,nullptr,error);chunks.clear();
 Check(WorldPersistence::Prepare(bootSource,error)&&WorldPersistence::Capture(bootSource,chunks,error),"boot save materializes lazy required participants without a fixed step");
 WorldPersistence::SceneFrom(chunks,restored,error);bootRestored.Build(restored,nullptr,error,nullptr,nullptr,true);WorldPersistence::Prepare(bootRestored,error);
 Check(WorldPersistence::Restore(bootRestored,chunks,error)&&bootRestored.RuntimeCharacter(bootMotor)->position==glm::vec3(0),"boot motor/navigation state reconstructs without motion or missing records");
 // Compare real translating/rotating support on the first resumed steps.
 Scene moving;auto platform=moving.CreateObject("moving support").id;auto* p=moving.Find(platform);p->body=SceneBodyComponent{};p->body->motion=SceneBodyMotion::Dynamic;p->body->managed=true;p->body->mass=500;p->body->halfExtents={2,.25,2};p->transform.position={0,-.25,0};
 auto passenger=moving.CreateObject("passenger").id;moving.Find(passenger)->characterMotor=CharacterMotorSettings{};moving.Find(passenger)->characterMotor->gravityScale=0;moving.Find(passenger)->transform.position={1,.92,0};
 RuntimeWorld movingSource,movingRestored;movingSource.Build(moving,nullptr,error);movingSource.UpdateCharacters(1.f/60);auto b=movingSource.RuntimeBody(platform);movingSource.Physics().SetLinearVelocity(b,{1,0,0});movingSource.Physics().SetAngularVelocity(b,{0,1,0});movingSource.Physics().Step(1.f/60);movingSource.UpdateCharacters(1.f/60);
 chunks.clear();WorldPersistence::Capture(movingSource,chunks,error);WorldPersistence::SceneFrom(chunks,restored,error);movingRestored.Build(restored,nullptr,error,nullptr,nullptr,true);WorldPersistence::Prepare(movingRestored,error);bool match=WorldPersistence::Restore(movingRestored,chunks,error);
 for(int i=0;i<3;++i){movingSource.Physics().Step(1.f/60);movingRestored.Physics().Step(1.f/60);movingSource.UpdateCharacters(1.f/60);movingRestored.UpdateCharacters(1.f/60);auto* a=movingSource.RuntimeCharacter(passenger);auto* c=movingRestored.RuntimeCharacter(passenger);match&=a->result.supported&&c->result.supported&&glm::length(a->position-c->position)<.001f&&glm::length(a->velocity-c->velocity)<.001f;}
 Check(match,"moving and rotating support resumes without doubled carrier motion or false landing");
 // Resting contact and a loaded spring hinge: caches rebuild, compare bounded continuation.
 Scene mechanical;auto ground=mechanical.CreateObject("ground").id;auto* groundObject=mechanical.Find(ground);groundObject->body=SceneBodyComponent{};groundObject->body->halfExtents={8,.5,8};groundObject->transform.position={0,-.5,0};
 auto resting=mechanical.CreateObject("resting body").id;auto* restObject=mechanical.Find(resting);restObject->body=SceneBodyComponent{};restObject->body->motion=SceneBodyMotion::Dynamic;restObject->body->managed=true;restObject->transform.position={-2,.51,0};
 auto plate=mechanical.CreateObject("hinged plate").id;auto* plateObject=mechanical.Find(plate);plateObject->body=SceneBodyComponent{};plateObject->body->motion=SceneBodyMotion::Dynamic;plateObject->body->managed=true;plateObject->body->halfExtents={.6f,.8f,.1f};plateObject->transform.position={2,1,0};
 auto hinge=mechanical.CreateObject("hinge").id;SceneJointComponent definition;definition.bodyA=plate;definition.bodyB=ground;definition.settings.type=JointType::Hinge;definition.settings.anchorA={0,.8f,0};definition.settings.anchorB={2,2.3f,0};definition.settings.spring=true;definition.settings.stiffness=8;definition.settings.damping=1;definition.settings.limits=true;definition.settings.lower=-1;definition.settings.upper=1;mechanical.Find(hinge)->joint=definition;
 RuntimeWorld mechanicalSource,mechanicalRestore;mechanicalSource.Build(mechanical,nullptr,error);
 auto advance=[&](RuntimeWorld& w){for(auto id:{resting,plate})w.Physics().ApplyForce(w.RuntimeBody(id),{0,-9.81f,0});w.Physics().Step(1.f/60);};for(int i=0;i<60;++i)advance(mechanicalSource);
 mechanicalSource.Physics().ApplyImpulseAtPoint(mechanicalSource.RuntimeBody(plate),{0,0,1},{2,1,0});advance(mechanicalSource);
 chunks.clear();bool stable=WorldPersistence::Capture(mechanicalSource,chunks,error)&&WorldPersistence::SceneFrom(chunks,restored,error)&&mechanicalRestore.Build(restored,nullptr,error,nullptr,nullptr,true)&&WorldPersistence::Prepare(mechanicalRestore,error)&&WorldPersistence::Restore(mechanicalRestore,chunks,error);
 for(int i=0;i<3&&stable;++i){advance(mechanicalSource);advance(mechanicalRestore);for(auto id:{resting,plate})stable&=glm::length(mechanicalSource.Physics().GetTransform(mechanicalSource.RuntimeBody(id)).position-mechanicalRestore.Physics().GetTransform(mechanicalRestore.RuntimeBody(id)).position)<.01f;JointState a,c;stable&=mechanicalSource.Physics().GetJoint(mechanicalSource.RuntimeJoint(hinge),a)&&mechanicalRestore.Physics().GetJoint(mechanicalRestore.RuntimeJoint(hinge),c)&&std::abs(a.coordinate-c.coordinate)<.01f;}
 Check(stable,"resting body and spring hinge remain stable over first three resumed steps");
 std::printf("SUMMARY %d checks %d failures\n",checks,failures);return failures?1:0;
}
