#include "NavigationAsset.h"
#include "NavigationSystem.h"
#include "AssetDatabase.h"
#include "Project.h"
#include "Prefab.h"
#include "SceneSerialization.h"
#include <filesystem>
#include <cstdio>
#include <chrono>
int main(int argc,char** argv){if(argc!=3){std::puts("usage: judas_navigation_bake project.judasproj scene-relative-path");return 2;}Project project;Scene scene,resolved,flat;AssetDatabase assets;std::string error;auto fail=[&](){std::fprintf(stderr,"%s\n",error.c_str());return 1;};if(!project.Load(argv[1],error))return fail();assets.Scan(project.RootDir(),project.AssetsDir());auto path=std::filesystem::path(project.RootDir())/argv[2];if(!LoadSceneFromFile(path.string(),scene,error)||!ResolvePrefabs(scene,&assets,resolved,error)||!FlattenHierarchy(resolved,flat,error))return fail();for(auto& o:scene.Objects())if(o.navigationSurface){auto start=std::chrono::steady_clock::now();NavigationData data;auto source=flat.Find(o.id);if(!source||!BakeNavigation(flat,*source,project.Settings().navigation,data,error))return fail();auto output=std::filesystem::path(project.AssetsDir())/"navigation"/("surface-"+std::to_string(o.id)+".judasnav");std::filesystem::create_directories(output.parent_path());if(!SaveNavigation(output.string(),data,error))return fail();AssetRecord record;auto* existing=assets.FindByRelativePath(std::filesystem::relative(output,project.RootDir()).generic_string());if(existing)record=*existing;else if(!assets.Track(output.string(),record,error))return fail();o.navigationSurface->asset=record.id;NavigationSystem preview(project.Settings().navigation);if(!preview.LoadSurface(o.id,source->transform,std::make_shared<NavigationData>(data),error))return fail();auto stats=preview.Statistics();std::printf("surface %llu: %zu layers, %zu polygons, %.2f ms, source %s\n",static_cast<unsigned long long>(o.id),data.layers.size(),stats.polygons,std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count(),data.fingerprint.c_str());}if(!SaveSceneToFile(scene,path.string(),error))return fail();return 0;}
