#include "LiquidGeometry.h"
#include <glm/gtc/matrix_inverse.hpp>
#include <algorithm>
#include <fstream>
#include <functional>
#include <iomanip>
#include <sstream>
#include <cmath>
namespace {
using V=glm::dvec3;using Face=std::vector<V>;using Poly=std::vector<Face>;
const int faces[4][3]={{1,2,3},{0,3,2},{0,1,3},{0,2,1}};
double tetVolume(const LiquidTet& t){return std::abs(glm::dot(t[1]-t[0],glm::cross(t[2]-t[0],t[3]-t[0])))/6;}
Poly poly(const LiquidTet& t){Poly p;V c=(t[0]+t[1]+t[2]+t[3])*.25;for(auto& f:faces){Face a{t[f[0]],t[f[1]],t[f[2]]};if(glm::dot(glm::cross(a[1]-a[0],a[2]-a[0]),c-a[0])>0)std::reverse(a.begin(),a.end());p.push_back(a);}return p;}
// Convex clipping retains actual faces and a consistently oriented cap.
Poly cut(const Poly& p,V n,double d,Face* cap=nullptr){Poly out;Face rim;for(auto& f:p){Face a;for(size_t i=0;i<f.size();++i){V x=f[i],y=f[(i+1)%f.size()];double sx=glm::dot(n,x)-d,sy=glm::dot(n,y)-d;bool ix=sx<=1e-12,iy=sy<=1e-12;if(ix)a.push_back(x);if(ix!=iy){V v=x+(y-x)*(sx/(sx-sy));a.push_back(v);bool unique=true;for(V r:rim)if(glm::length(r-v)<1e-9)unique=false;if(unique)rim.push_back(v);}}if(a.size()>=3)out.push_back(a);}
 if(rim.size()>=3){V c(0);for(V v:rim)c+=v;c/=double(rim.size());V u=glm::normalize(rim[0]-c),v=glm::cross(glm::normalize(n),u);std::sort(rim.begin(),rim.end(),[&](V a,V b){return std::atan2(glm::dot(a-c,v),glm::dot(a-c,u))<std::atan2(glm::dot(b-c,v),glm::dot(b-c,u));});out.push_back(rim);if(cap)*cap=rim;}return out;}
LiquidMoment moment(const Poly& p){LiquidMoment r;V c(0);size_t count=0;for(auto& f:p)for(V v:f){c+=v;++count;}if(!count)return r;c/=double(count);for(auto& f:p)for(size_t i=1;i+1<f.size();++i){double v=std::abs(glm::dot(f[0]-c,glm::cross(f[i]-c,f[i+1]-c)))/6;r.volume+=v;r.first+=v*(c+f[0]+f[i]+f[i+1])*.25;}return r;}
bool affine(const LiquidTet& t,const std::array<double,4>& values,V& n,double& d){glm::dmat3 m(t[1]-t[0],t[2]-t[0],t[3]-t[0]);if(std::abs(glm::determinant(m))<1e-15)return false;n=glm::transpose(glm::inverse(m))*V(values[1]-values[0],values[2]-values[0],values[3]-values[0]);d=values[0]-glm::dot(n,t[0]);return true;}
std::array<double,4> coords(const LiquidTet& t,const GravityEquilibrium& e){return {e.Coordinate(t[0]),e.Coordinate(t[1]),e.Coordinate(t[2]),e.Coordinate(t[3])};}
}
LiquidGeometry LiquidBox(V a,V b){std::array<V,8> p;for(int i=0;i<8;++i)p[i]=V(i&1?b.x:a.x,i&2?b.y:a.y,i&4?b.z:a.z);LiquidGeometry g;const int ids[6][4]={{0,1,3,7},{0,3,2,7},{0,2,6,7},{0,6,4,7},{0,4,5,7},{0,5,1,7}};for(auto& t:ids)g.cells.push_back({p[t[0]],p[t[1]],p[t[2]],p[t[3]]});return g;}
LiquidMoment LiquidClip(const LiquidTet& t,const std::array<double,4>& q,double level,MeshData* mesh){double lo=*std::min_element(q.begin(),q.end()),hi=*std::max_element(q.begin(),q.end());if(level<=lo)return {};if(level>=hi){if(mesh&&std::abs(level-hi)<1e-9)for(auto& f:faces)if(std::abs(q[f[0]]-level)<1e-9&&std::abs(q[f[1]]-level)<1e-9&&std::abs(q[f[2]]-level)<1e-9){V n;double d;if(affine(t,q,n,d))for(int index:f)mesh->vertices.push_back({glm::vec3(t[index]),glm::vec3(glm::normalize(n)),{0,0}});}return {tetVolume(t),tetVolume(t)*(t[0]+t[1]+t[2]+t[3])*.25};}V n;double d;if(!affine(t,q,n,d))return {};Face cap;auto result=moment(cut(poly(t),n,level-d,&cap));if(mesh&&cap.size()>=3)for(size_t i=1;i+1<cap.size();++i)for(V v:{cap[0],cap[i],cap[i+1]})mesh->vertices.push_back({glm::vec3(v),glm::vec3(glm::normalize(n)),{0,0}});return result;}
double LiquidCapacity(const LiquidGeometry& g,const GravityEquilibrium& e,double q){double v=0;for(auto& t:g.cells)v+=LiquidClip(t,coords(t,e),q).volume;return v;}
double LiquidCoordinate(const LiquidTet& t,const GravityEquilibrium& e,V p,bool& inside){auto m=glm::dmat3(t[1]-t[0],t[2]-t[0],t[3]-t[0]);V b=glm::inverse(m)*(p-t[0]);inside=b.x>=-1e-8&&b.y>=-1e-8&&b.z>=-1e-8&&b.x+b.y+b.z<=1+1e-8;auto q=coords(t,e);return q[0]+b.x*(q[1]-q[0])+b.y*(q[2]-q[0])+b.z*(q[3]-q[0]);}
LiquidMoment LiquidIntersection(const LiquidTet& body,const LiquidTet& basin,const GravityEquilibrium& e,double q){Poly p=poly(body);for(auto& f:poly(basin)){V n=glm::cross(f[1]-f[0],f[2]-f[0]);p=cut(p,n,glm::dot(n,f[0]));if(p.empty())return {};}V n;double d;affine(basin,coords(basin,e),n,d);return moment(cut(p,n,q-d));}
bool ValidateLiquidGeometry(const LiquidGeometry& g,std::string& error){if(g.cells.empty()||g.cells.size()>16384){error="cavity needs 1..16384 nonoverlapping tetrahedra";return false;}for(auto& t:g.cells){for(V p:t)if(!std::isfinite(glm::dot(p,p))||glm::length(p)>1e6){error="invalid cavity coordinate";return false;}if(tetVolume(t)<1e-12){error="degenerate cavity tetrahedron";return false;}}
 // Full authored validation only, not per frame. Broad AABB rejection avoids most pairs.
 for(size_t i=0;i<g.cells.size();++i)for(size_t j=0;j<i;++j){V a(1e30),b(-1e30),c=a,d=b;for(V v:g.cells[i]){a=glm::min(a,v);b=glm::max(b,v);}for(V v:g.cells[j]){c=glm::min(c,v);d=glm::max(d,v);}if(b.x<=c.x+1e-9||d.x<=a.x+1e-9||b.y<=c.y+1e-9||d.y<=a.y+1e-9||b.z<=c.z+1e-9||d.z<=a.z+1e-9)continue;Poly p=poly(g.cells[i]);for(auto& f:poly(g.cells[j])){V n=glm::cross(f[1]-f[0],f[2]-f[0]);p=cut(p,n,glm::dot(n,f[0]));}if(moment(p).volume>1e-9){error="overlapping cavity tetrahedra would double-count liquid";return false;}}
 return true;}
bool LoadLiquidGeometry(const std::string& path,LiquidGeometry& out,std::string& error){std::ifstream s(path);std::string magic;size_t n;LiquidGeometry g;if(!(s>>magic>>n)||magic!="JudasCavity1"||n>16384){error="invalid JudasCavity1 header";return false;}g.cells.resize(n);for(auto& t:g.cells)for(V& v:t)if(!(s>>v.x>>v.y>>v.z)){error="truncated cavity";return false;}s>>std::ws;if(!s.eof()||!ValidateLiquidGeometry(g,error))return false;out=std::move(g);return true;}
double LiquidInverse(const LiquidBasinData& b,double v){if(v<=0)return b.curve.front().q;if(v>=b.capacity)return b.curve.back().q;auto it=std::lower_bound(b.curve.begin(),b.curve.end(),v,[](auto p,double target){return p.volume<target;});auto a=*(it-1);return a.q+(it->q-a.q)*(v-a.volume)/(it->volume-a.volume);}
bool BakeLiquidBasin(const LiquidGeometry& source,const GravityEquilibrium& e,double vt,double ht,const std::string& hash,LiquidBasinData& out,std::string& error){if(!ValidateLiquidGeometry(source,error)||vt<=0||ht<=0||!std::isfinite(vt+ht)||e.magnitude<=0){error="invalid cavity/gravity/bake tolerances: "+error;return false;}LiquidBasinData b;b.geometry=source;b.equilibrium=e;b.fingerprint=hash;b.volumeTolerance=vt;b.heightTolerance=ht;
 if(e.kind==GravityEquilibrium::Kind::Radius){std::vector<LiquidTet> pending=source.cells;b.geometry.cells.clear();while(!pending.empty()){auto t=pending.back();pending.pop_back();double length=0;int a=0,c=1;for(int i=0;i<4;++i)for(int j=i+1;j<4;++j)if(glm::length(t[i]-t[j])>length){length=glm::length(t[i]-t[j]);a=i;c=j;}double radius=1e30;for(V v:t)radius=std::min(radius,e.Coordinate(v));double lower=radius-length;if(lower<=0){error="radial cavity crosses gravity centre or exceeds local radial domain";return false;}double bound=length*length/(2*lower);if(bound>ht*.25){V mid=(t[a]+t[c])*.5;auto left=t,right=t;left[a]=mid;right[c]=mid;pending.push_back(left);pending.push_back(right);}else{b.coordinateError=std::max(b.coordinateError,bound);b.geometry.cells.push_back(t);}if(pending.size()+b.geometry.cells.size()>262144){error="radial refinement exceeded 262144 cells; loosen declared height tolerance";return false;}}}
 std::vector<double> knots;for(auto& t:b.geometry.cells)for(V v:t)knots.push_back(e.Coordinate(v));std::sort(knots.begin(),knots.end());knots.erase(std::unique(knots.begin(),knots.end(),[](double a,double c){return std::abs(a-c)<1e-10;}),knots.end());double min=knots.front(),max=knots.back();b.capacity=LiquidCapacity(b.geometry,e,max);b.curve.push_back({min,0});
 // Every interval is refined at quarter/mid/three-quarter positions. Bernstein
 // cubic interpolation bound: capacity is piecewise cubic between vertex knots.
 std::function<bool(double,double,double,double,int)> refine=[&](double a,double va,double c,double vc,int depth){double mid=(a+c)*.5,vm=LiquidCapacity(b.geometry,e,mid),v1=LiquidCapacity(b.geometry,e,(3*a+c)*.25),v3=LiquidCapacity(b.geometry,e,(a+3*c)*.25);double err=std::max({std::abs(vm-(va+vc)*.5),std::abs(v1-(3*va+vc)*.25),std::abs(v3-(va+3*vc)*.25)})*4;bool good=err<=vt&&((c-a)<=ht||err<=std::max(1e-13,(vc-va)*1e-10));if(good){b.curve.push_back({c,vc});return true;}if(depth>30||b.curve.size()>65536){error="capacity curve refinement exceeded budget";return false;}return refine(a,va,mid,vm,depth+1)&&refine(mid,vm,c,vc,depth+1);};
 // Retain every vertex knot: the cubic interpolation error bound only applies
 // between these knots. Never replace them with an unverified coarse grid.
 for(size_t i=1;i<knots.size();++i)if(!refine(knots[i-1],b.curve.back().volume,knots[i],LiquidCapacity(b.geometry,e,knots[i]),0))return false;
 out=std::move(b);return true;}
bool SaveLiquidBasin(const std::string& path,const LiquidBasinData& b,std::string& error){std::ofstream s(path);if(!s){error="cannot write basin asset";return false;}s<<std::setprecision(17)<<"JudasBasin1 "<<std::quoted(b.fingerprint)<<' '<<int(b.equilibrium.kind)<<' '<<b.equilibrium.up.x<<' '<<b.equilibrium.up.y<<' '<<b.equilibrium.up.z<<' '<<b.equilibrium.center.x<<' '<<b.equilibrium.center.y<<' '<<b.equilibrium.center.z<<' '<<b.equilibrium.magnitude<<' '<<b.volumeTolerance<<' '<<b.heightTolerance<<' '<<b.coordinateError<<' '<<b.capacity<<' '<<b.geometry.cells.size()<<' '<<b.curve.size()<<'\n';for(auto& t:b.geometry.cells){for(V v:t)s<<v.x<<' '<<v.y<<' '<<v.z<<' ';s<<'\n';}for(auto p:b.curve)s<<p.q<<' '<<p.volume<<'\n';if(!s){error="failed basin write";return false;}return true;}
bool DecodeLiquidBasin(const std::vector<unsigned char>& bytes,LiquidBasinData& out,std::string& error){if(bytes.size()>128*1024*1024){error="basin asset exceeds 128 MiB";return false;}std::istringstream s(std::string(bytes.begin(),bytes.end()));LiquidBasinData b;std::string magic;int kind;size_t nt,nc;auto& e=b.equilibrium;if(!(s>>magic>>std::quoted(b.fingerprint)>>kind>>e.up.x>>e.up.y>>e.up.z>>e.center.x>>e.center.y>>e.center.z>>e.magnitude>>b.volumeTolerance>>b.heightTolerance>>b.coordinateError>>b.capacity>>nt>>nc)||magic!="JudasBasin1"||kind<0||kind>1||nt==0||nt>262144||nc<2||nc>65536){error="invalid JudasBasin1 header";return false;}e.kind=GravityEquilibrium::Kind(kind);b.geometry.cells.resize(nt);b.curve.resize(nc);for(auto& t:b.geometry.cells)for(V& p:t)if(!(s>>p.x>>p.y>>p.z)||!std::isfinite(glm::dot(p,p))){error="invalid basin tetrahedra";return false;}for(auto& t:b.geometry.cells)if(tetVolume(t)<1e-12){error="degenerate basin cell";return false;}double prevQ=-1e30,prevV=-1;for(auto& p:b.curve){if(!(s>>p.q>>p.volume)||!std::isfinite(p.q+p.volume)||p.q<=prevQ||p.volume<prevV){error="nonmonotonic basin capacity";return false;}prevQ=p.q;prevV=p.volume;}s>>std::ws;if(!s.eof()||b.capacity<=0||b.volumeTolerance<=0||b.heightTolerance<=0||e.magnitude<=0||b.coordinateError<0||!std::isfinite(e.magnitude+b.volumeTolerance+b.heightTolerance+b.coordinateError+b.capacity+glm::dot(e.center,e.center))||std::abs(glm::length(e.up)-1)>1e-6||b.curve.front().volume!=0||std::abs(b.curve.back().volume-b.capacity)>1e-9){error="invalid basin metadata/endpoints";return false;}out=std::move(b);return true;}
bool LoadLiquidBasin(const std::string& path,LiquidBasinData& out,std::string& error){std::ifstream s(path,std::ios::binary);if(!s){error="missing basin asset";return false;}std::vector<unsigned char> bytes{std::istreambuf_iterator<char>(s),{}};return DecodeLiquidBasin(bytes,out,error);}
