#include "LiquidSystem.h"
#include "RuntimeWorld.h"
#include "ResourceManager.h"
#include <glm/gtc/quaternion.hpp>
#include <algorithm>
#include <atomic>
#include <cmath>
#include <limits>
namespace {
using V=glm::dvec3;
std::atomic<std::uint64_t> generations{1};
V local(const SceneTransform& p,V v){return glm::inverse(glm::dquat(p.rotation))*(v-V(p.position));}
V global(const SceneTransform& p,V v){return V(p.position)+glm::dquat(p.rotation)*v;}
GravityEquilibrium localized(GravityEquilibrium e,const SceneTransform& p){e.up=glm::inverse(glm::dquat(p.rotation))*e.up;e.center=local(p,e.center);return e;}
std::array<double,4> coordinates(const LiquidTet& t,const GravityEquilibrium& e){return {e.Coordinate(t[0]),e.Coordinate(t[1]),e.Coordinate(t[2]),e.Coordinate(t[3])};}
bool aabb(const LiquidTet& t,V lo,V hi){V a(1e30),b(-1e30);for(V p:t){a=glm::min(a,p);b=glm::max(b,p);}return a.x<hi.x&&b.x>lo.x&&a.y<hi.y&&b.y>lo.y&&a.z<hi.z&&b.z>lo.z;}
// Openings are authored convex polygons on an exterior cavity face. Orient the
// plane away from the cavity interior; winding does not carry game semantics.
V openingNormal(const LiquidState& s){const auto& o=s.containerSettings.opening;V n=glm::normalize(glm::cross(o[1]-o[0],o[2]-o[0])),center(0);size_t count=0;for(auto& t:s.geometry.cells)for(V v:t){center+=v;++count;}center/=double(count);if(glm::dot(n,center-o[0])>0)n=-n;return n;}
bool throughOpening(const LiquidState& s,V start,V end){start=local(s.pose,start);end=local(s.pose,end);const auto& o=s.containerSettings.opening;V n=openingNormal(s);double a=glm::dot(n,start-o[0]),b=glm::dot(n,end-o[0]);if(a<0||b>0||a-b<1e-12)return false;V p=start+(end-start)*(a/(a-b));double sign=0;for(size_t i=0;i<o.size();++i){double side=glm::dot(glm::cross(o[(i+1)%o.size()]-o[i],p-o[i]),n);if(std::abs(side)<1e-8)continue;if(sign&&side*sign<0)return false;sign=side;}return true;}
double surfaceQ(const LiquidState& s){return s.equilibrium.kind==GravityEquilibrium::Kind::Plane?s.q+glm::dot(glm::dquat(s.pose.rotation)*s.equilibrium.up,V(s.pose.position)):s.q;}
}
LiquidSystem::LiquidSystem():m_generation(generations.fetch_add(1)){}
LiquidHandle LiquidSystem::Insert(LiquidState state,std::string& error){if(m_entities.count(state.entity)){error="duplicate liquid owner";return {};}if(!std::isfinite(state.volume+state.capacity+state.material.density)||state.material.id.empty()||state.material.density<=0||state.capacity<=0||state.volume<0||state.volume>state.capacity+1e-12){error="initial liquid exceeds capacity";return {};}if(m_density.count(state.material.id)&&m_density[state.material.id]!=state.material.density){error="material identity has contradictory density";return {};}state.handle={m_next++,m_generation};m_density[state.material.id]=state.material.density;m_expected[state.material.id]+=state.volume;auto h=state.handle;Resolve(state);m_entities[state.entity]=h;m_states[h.id]=std::move(state);return h;}
LiquidHandle LiquidSystem::AddBasin(SceneObjectId entity,const LiquidBasinSettings& a,const SceneTransform& pose,std::shared_ptr<const LiquidBasinData> data,std::string& error){if(!data||data->curve.empty()){error="missing capacity data";return {};}LiquidState s;s.entity=entity;s.enabled=a.enabled;s.material=a.material;s.volume=a.initialVolume;s.capacity=data->capacity;s.geometry=data->geometry;s.equilibrium=data->equilibrium;s.basin=data;s.pose=pose;return Insert(std::move(s),error);}
LiquidHandle LiquidSystem::AddContainer(SceneObjectId entity,const LiquidContainerSettings& a,const SceneTransform& p,const LiquidGeometry& g,const GravityEquilibrium& e,std::string& error){if(!ValidateLiquidGeometry(g,error))return {};if(!std::isfinite(e.magnitude)||e.magnitude<=0){error="container requires nonzero gravity";return {};}if(a.opening.size()<3){error="opening needs a polygon";return {};}V n=glm::cross(a.opening[1]-a.opening[0],a.opening[2]-a.opening[0]);if(glm::length(n)<1e-10){error="degenerate container opening";return {};}n=glm::normalize(n);double sign=0;for(auto& t:g.cells)for(V p:t){double d=glm::dot(n,p-a.opening[0]);if(std::abs(d)<1e-8)continue;if(sign&&d*sign<0){error="opening must be an exterior cavity face";return {};}sign=d;}for(V p:a.opening)if(std::abs(glm::dot(n,p-a.opening[0]))>1e-7){error="opening must be planar";return {};}double turn=0;for(size_t i=0;i<a.opening.size();++i){V u=a.opening[(i+1)%a.opening.size()]-a.opening[i],v=a.opening[(i+2)%a.opening.size()]-a.opening[(i+1)%a.opening.size()];double d=glm::dot(glm::cross(u,v),n);if(std::abs(d)<1e-10)continue;if(turn&&d*turn<0){error="opening must be convex and ordered";return {};}turn=d;}LiquidState s;s.entity=entity;s.container=true;s.enabled=a.enabled;s.material=a.material;s.volume=a.initialVolume;s.pose=p;s.equilibrium=localized(e,p);s.equilibrium.kind=GravityEquilibrium::Kind::Plane;s.equilibrium.up=glm::inverse(glm::dquat(p.rotation))*e.Up(V(p.position));s.geometry=g;s.containerSettings=a;for(auto& t:g.cells){auto q=coordinates(t,s.equilibrium);s.capacity+=LiquidClip(t,q,*std::max_element(q.begin(),q.end())).volume;}return Insert(std::move(s),error);}
LiquidState* LiquidSystem::Get(LiquidHandle h){auto it=m_states.find(h.id);return h.generation==m_generation&&it!=m_states.end()?&it->second:nullptr;}
const LiquidState* LiquidSystem::Get(LiquidHandle h)const{auto it=m_states.find(h.id);return h.generation==m_generation&&it!=m_states.end()?&it->second:nullptr;}
LiquidHandle LiquidSystem::Handle(SceneObjectId id)const{auto it=m_entities.find(id);return it==m_entities.end()?LiquidHandle{}:it->second;}
bool LiquidSystem::Remove(LiquidHandle h){auto* s=Get(h);if(!s)return false;if(s->volume>0){auto id=m_nextParcel++;m_parcels[id]={id,s->material,s->volume,s->pose.position,{0,0,0},true};}m_entities.erase(s->entity);m_states.erase(h.id);return true;}
bool LiquidSystem::SetEnabled(LiquidHandle h,bool enabled){auto* s=Get(h);if(!s)return false;s->enabled=enabled;return true;}
void LiquidSystem::Resolve(LiquidState& s){double lo=1e30,hi=-1e30;s.minimum=V(1e30);s.maximum=V(-1e30);for(auto& t:s.geometry.cells)for(V p:t){lo=std::min(lo,s.equilibrium.Coordinate(p));hi=std::max(hi,s.equilibrium.Coordinate(p));s.minimum=glm::min(s.minimum,p);s.maximum=glm::max(s.maximum,p);}s.stableCapacity=s.capacity;if(s.container){double lip=hi;for(V p:s.containerSettings.opening)lip=std::min(lip,s.equilibrium.Coordinate(p));s.stableCapacity=LiquidCapacity(s.geometry,s.equilibrium,lip);double a=lo,b=hi;for(int i=0;i<40;++i){double q=(a+b)*.5;if(LiquidCapacity(s.geometry,s.equilibrium,q)<s.volume)a=q;else b=q;}s.q=(a+b)*.5;}else s.q=LiquidInverse(*s.basin,s.volume);
 s.surface.vertices.clear();if(s.volume>1e-14)for(auto& t:s.geometry.cells)LiquidClip(t,coordinates(t,s.equilibrium),s.q,&s.surface);}
double LiquidSystem::Transfer(LiquidHandle a,LiquidHandle b,double request){auto* source=Get(a);auto* target=Get(b);if(!source||!target||a==b||!source->enabled||!target->enabled||!source->equilibriumValid||!target->equilibriumValid||source->material.id!=target->material.id||!std::isfinite(request)||request<0)return 0;double delta=std::min({request,source->volume,std::max(0.,target->capacity-target->volume)});if(delta<=0)return 0;source->volume-=delta;target->volume+=delta;Resolve(*source);Resolve(*target);return delta;}
double LiquidSystem::Emit(LiquidHandle h,double request,glm::vec3 p,glm::vec3 v){auto* s=Get(h);if(!s||!s->enabled||!s->equilibriumValid||!std::isfinite(request)||request<0||!std::isfinite(glm::dot(p,p)+glm::dot(v,v)))return 0;double amount=std::min(request,s->volume);if(amount<=0)return 0;auto id=m_nextParcel++;m_parcels[id]={id,s->material,amount,p,v,false,s->entity};s->volume-=amount;Resolve(*s);return amount;}
double LiquidSystem::Receive(std::uint64_t id,LiquidHandle h,double maximum){auto it=m_parcels.find(id);auto* s=Get(h);if(it==m_parcels.end()||!s||!s->enabled||!s->equilibriumValid||s->material.id!=it->second.material.id||!std::isfinite(maximum)||maximum<0)return 0;double amount=std::min({maximum,it->second.volume,std::max(0.,s->capacity-s->volume)});s->volume+=amount;it->second.volume-=amount;if(it->second.volume==0)m_parcels.erase(it);Resolve(*s);return amount;}
LiquidAccounting LiquidSystem::Accounting(const std::string& name)const{LiquidAccounting a;for(const auto& [id,s]:m_states)if(s.material.id==name){if(s.container)a.containers+=s.volume;else a.reservoirs+=s.volume;}for(const auto& [id,p]:m_parcels)if(p.material.id==name)a.detached+=p.volume;a.total=a.reservoirs+a.containers+a.detached;auto it=m_expected.find(name);if(it!=m_expected.end())a.expected=it->second;a.error=a.total-a.expected;a.tolerance=std::max(1e-12,64*std::numeric_limits<double>::epsilon()*std::max(1.,a.expected)*(m_states.size()+m_parcels.size()+1));return a;}
std::optional<LiquidSample> LiquidSystem::Sample(glm::vec3 p,LiquidHandle excluded)const{for(auto& [id,s]:m_states){if(!s.enabled||!s.equilibriumValid||s.volume<=0||s.handle==excluded)continue;V v=local(s.pose,V(p));if(v.x<s.minimum.x||v.y<s.minimum.y||v.z<s.minimum.z||v.x>s.maximum.x||v.y>s.maximum.y||v.z>s.maximum.z)continue;for(auto& t:s.geometry.cells){bool inside=false;double q=LiquidCoordinate(t,s.equilibrium,v,inside);if(inside&&q<=s.q+1e-9){LiquidSample sample;sample.handle=s.handle;sample.entity=s.entity;sample.material=s.material;sample.depth=std::max(0.,s.q-s.equilibrium.Coordinate(v));sample.coordinate=s.q;V up=s.equilibrium.Up(v);sample.normal=glm::vec3(glm::dquat(s.pose.rotation)*up);sample.surfacePoint=glm::vec3(global(s.pose,v+up*sample.depth));return sample;}}}return {};}
bool LiquidSystem::SetContainerPose(LiquidHandle h,const SceneTransform& pose,const GravityEquilibrium& e,std::string& error){auto* s=Get(h);if(!s||!s->container){error="invalid container handle";return false;}if(!std::isfinite(e.magnitude)||e.magnitude<=0){s->equilibriumValid=false;s->pose=pose;s->surface.vertices.clear();error="container requires nonzero gravity";return false;}s->equilibriumValid=true;s->pose=pose;s->equilibrium=localized(e,pose);s->equilibrium.kind=GravityEquilibrium::Kind::Plane;s->equilibrium.up=glm::inverse(glm::dquat(pose.rotation))*e.Up(V(pose.position));Resolve(*s);return true;}
void LiquidSystem::Synchronize(RuntimeWorld& world){auto objects=world.ScriptObjects();for(auto& o:objects)if(o.liquidBasin||o.liquidContainer){if(Handle(o.id).id)continue;auto* assets=world.Resources();if(!assets||!assets->Assets())continue;std::string error;auto resource=assets->GetLiquid(o.liquidBasin?o.liquidBasin->asset:o.liquidContainer->geometry,error);if(!resource){if(error!="loading")m_errors[o.id]=error;continue;}auto pose=world.PresentedTransform(o.id,o.transform,1);if(o.liquidBasin){if(!resource->basin){m_errors[o.id]="basin asset is a cavity, not a baked curve";continue;}AddBasin(o.id,*o.liquidBasin,pose,resource->basin,error);}else{GravityEquilibrium eq;if(!world.Gravity().Equilibrium(pose.position,eq)){m_errors[o.id]="unsupported container gravity equilibrium";continue;}AddContainer(o.id,*o.liquidContainer,pose,resource->geometry,eq,error);}if(!error.empty())m_errors[o.id]=error;else m_errors.erase(o.id);}
 std::vector<LiquidHandle> dead;for(const auto& [id,s]:m_states){auto* e=world.FindEntity(s.entity);if(!e||e->lifecycle==EntityLifecycle::Destroyed)dead.push_back(s.handle);}for(auto h:dead)Remove(h);}
LiquidSubmersion LiquidSystem::Submerged(const LiquidGeometry& geometry)const{LiquidSubmersion out;V first(0),force(0);for(auto& [id,s]:m_states)if(s.enabled&&!s.container&&s.volume>0)for(auto worldTet:geometry.cells){LiquidTet body;for(int i=0;i<4;++i)body[i]=local(s.pose,worldTet[i]);if(!aabb(body,s.minimum,s.maximum))continue;for(auto& basin:s.geometry.cells){V lo(1e30),hi(-1e30);for(V v:basin){lo=glm::min(lo,v);hi=glm::max(hi,v);}if(!aabb(body,lo,hi))continue;auto m=LiquidIntersection(body,basin,s.equilibrium,s.q);if(m.volume>0){V c=global(s.pose,m.first/m.volume);out.volume+=m.volume;out.displacedMass+=s.material.density*m.volume;first+=c*m.volume;force+=glm::dquat(s.pose.rotation)*s.equilibrium.Up(m.first/m.volume)*(s.material.density*s.equilibrium.magnitude*m.volume);}}}if(out.volume>0)out.center=glm::vec3(first/out.volume);out.buoyancy=glm::vec3(force);return out;}
void LiquidSystem::Update(RuntimeWorld& world,double dt){if(dt<=0||!std::isfinite(dt))return;m_connections.clear();Synchronize(world);
 for(auto& [id,s]:m_states)if(s.enabled&&s.container){auto* o=world.RuntimeDefinition(s.entity);if(!o)continue;auto pose=world.PresentedTransform(s.entity,o->transform,1);GravityEquilibrium eq;std::string error;if(!world.Gravity().Equilibrium(pose.position,eq)||!SetContainerPose(s.handle,pose,eq,error)){s.equilibriumValid=false;s.pose=pose;s.surface.vertices.clear();m_errors[s.entity]="unsupported container gravity; retained volume";continue;}m_errors.erase(s.entity);
  // Vented cavity: only opening connectivity permits equalisation. Its external
  // head determines a TARGET volume; transfer the delta, never copy overlap.
  std::optional<LiquidSample> external;for(V lip:s.containerSettings.opening){auto q=Sample(glm::vec3(global(s.pose,lip)),s.handle);if(q&&q->handle.id!=s.handle.id){external=q;break;}}
  if(external){auto* source=Get(external->handle);if(source&&source->material.id==s.material.id){V point=local(s.pose,V(external->surfacePoint));double target=LiquidCapacity(s.geometry,s.equilibrium,s.equilibrium.Coordinate(point));double head=std::max(0.,target-s.volume);double flow=s.containerSettings.discharge*s.containerSettings.openingArea*std::sqrt(2*eq.magnitude*std::max(.001,external->depth))*dt;Transfer(source->handle,s.handle,std::min(head,flow));}}
  double excess=std::max(0.,s.volume-s.stableCapacity);if(excess>1e-12){V lip=s.containerSettings.opening.front();for(V v:s.containerSettings.opening)if(s.equilibrium.Coordinate(v)<s.equilibrium.Coordinate(lip))lip=v;double head=std::max(0.,s.q-s.equilibrium.Coordinate(lip));double amount=std::min(excess,s.containerSettings.discharge*s.containerSettings.openingArea*std::sqrt(2*eq.magnitude*head)*dt);auto body=world.RuntimeBody(s.entity);glm::vec3 velocity(0);if(world.Physics().IsDynamicBody(body))velocity=world.Physics().GetLinearVelocity(body)+glm::cross(world.Physics().GetAngularVelocity(body),glm::vec3(global(s.pose,lip))-pose.position);const V outward=glm::dquat(s.pose.rotation)*openingNormal(s);velocity+=glm::vec3(outward)*float(std::sqrt(2*eq.magnitude*head));Emit(s.handle,amount,glm::vec3(global(s.pose,lip)+outward*.002),velocity);}}
 for(auto& o:world.ScriptObjects())if(o.liquidConnection){auto c=*o.liquidConnection;m_connections[o.id]=false;if(!c.enabled)continue;auto* a=Get(Handle(c.source));auto* b=Get(Handle(c.destination));if(!a||!b||!a->basin||!b->basin||!a->enabled||!b->enabled||a->material.id!=b->material.id)continue;GravityEquilibrium eq;if(!world.Gravity().Equilibrium(o.transform.position,eq))continue;if(!localized(eq,a->pose).Equivalent(a->equilibrium)||!localized(eq,b->pose).Equivalent(b->equilibrium)){m_errors[o.id]="spill basins must share one supported equilibrium field";continue;}double threshold=eq.Coordinate(V(o.transform.position));double qa=surfaceQ(*a),qb=surfaceQ(*b);if(std::max(qa,qb)<=threshold)continue;m_connections[o.id]=true;if(qb>qa){if(!c.bidirectional)continue;std::swap(a,b);std::swap(qa,qb);}double flow=c.discharge*c.openingArea*std::sqrt(2*eq.magnitude*std::max(0.,qa-std::max(qb,threshold)))*dt;double low=0,high=std::min({a->volume,b->capacity-b->volume,flow});
  // Bound by equalisation, so large timesteps cannot ping-pong reservoirs.
  for(int i=0;i<30;++i){double delta=(low+high)*.5;double aq=LiquidInverse(*a->basin,a->volume-delta),bq=LiquidInverse(*b->basin,b->volume+delta);double ao=surfaceQ(*a)-a->q,bo=surfaceQ(*b)-b->q;if(aq+ao>bq+bo&&aq+ao>threshold)low=delta;else high=delta;}Transfer(a->handle,b->handle,low);}
 // Test the existing authoritative solid query FIRST. Receiving volume cannot
 // pass through a wall merely because another cavity lies behind it.
 std::vector<std::uint64_t> parcelIds;for(const auto& [id,p]:m_parcels)parcelIds.push_back(id);
 for(auto id:parcelIds){auto it=m_parcels.find(id);if(it==m_parcels.end()||it->second.parked)continue;auto& p=it->second;const auto start=p.position;p.velocity+=world.Gravity().Sample(start)*float(dt);const auto end=start+p.velocity*float(dt);const double distance=glm::length(end-start);PhysicsQueryFilter filter;auto sourceBody=world.RuntimeBody(p.source);if(sourceBody.id!=BodyHandle::kInvalidId)filter.ignoredBodies.push_back(sourceBody);auto hit=distance>1e-8?world.Physics().Raycast(start,(end-start)/float(distance),float(distance),filter):PhysicsCastHit{};const auto limit=hit.hit?hit.point:end;double travel=glm::length(limit-start);bool received=false;int samples=std::min(256,std::max(1,int(std::ceil(travel/.03))));
  for(int i=1;i<=samples&&!received;++i){auto point=glm::mix(start,limit,float(i)/samples);for(auto& [sid,s]:m_states){if(!s.enabled||!s.equilibriumValid||s.material.id!=p.material.id||s.material.density!=p.material.density||s.entity==p.source||s.capacity<=s.volume)continue;V v=local(s.pose,V(point));if(v.x<s.minimum.x||v.y<s.minimum.y||v.z<s.minimum.z||v.x>s.maximum.x||v.y>s.maximum.y||v.z>s.maximum.z)continue;if(s.container&&!throughOpening(s,V(start),V(point)))continue;for(auto& t:s.geometry.cells){bool inside;LiquidCoordinate(t,s.equilibrium,v,inside);if(inside){const double volume=p.volume;if(Receive(id,s.handle,volume)>0)received=true;break;}}if(received)break;}}
  it=m_parcels.find(id);if(it==m_parcels.end())continue;auto& remainder=it->second;if(hit.hit){remainder.position=hit.point;remainder.velocity={0,0,0};remainder.parked=true;}else remainder.position=end;
 }
 for(auto& o:world.ScriptObjects())if(o.liquidInteraction&&o.liquidInteraction->enabled){auto h=world.RuntimeBody(o.id);if(!world.Physics().IsDynamicBody(h)||!world.Physics().IsBodyEnabled(h)||world.Physics().IsBodySensor(h)||world.Physics().GetMass(h)<=0)continue;auto pose=world.Physics().GetTransform(h);LiquidGeometry body;if(o.body->shape==SceneShape::Box)body=LiquidBox(-V(o.body->halfExtents),V(o.body->halfExtents));else if(o.body->shape==SceneShape::Compound)for(auto b:o.body->compoundBoxes){auto g=LiquidBox(V(b.localCenter-b.halfExtents),V(b.localCenter+b.halfExtents));body.cells.insert(body.cells.end(),g.cells.begin(),g.cells.end());}else continue;for(auto& t:body.cells)for(V& p:t)p=V(pose.position)+glm::dquat(pose.rotation)*p;auto submerged=Submerged(body);if(submerged.volume>0){world.Physics().ApplyForce(h,submerged.buoyancy);world.Physics().ApplyTorque(h,glm::cross(submerged.center-pose.position,submerged.buoyancy));auto v=world.Physics().GetLinearVelocity(h);double coefficient=std::min(o.liquidInteraction->drag*submerged.displacedMass,world.Physics().GetMass(h)/dt*.5);world.Physics().ApplyForce(h,-v*float(coefficient));}}
}
