#include "PerformanceProfiler.h"
#include "NavigationSystem.h"
#include "NavigationBackend.h"
#include "RuntimeWorld.h"
#include "Prefab.h"
#include "ResourceManager.h"
#include <DetourNavMesh.h>
#include <DetourNavMeshQuery.h>
#include <DetourNavMeshBuilder.h>
#include <DetourTileCache.h>
#include <DetourObstacleAvoidance.h>
#include <glm/gtc/quaternion.hpp>

#include <algorithm>
#include <set>
#include <cmath>
#include <cstring>
namespace {
struct Filter:dtQueryFilter {CategoryMask mask;Filter(const NavigationFilter& f):mask(f.include&~f.exclude){for(auto [id,c]:f.costs)if(id<62&&std::isfinite(c)&&c>=1)setAreaCost(id+1,c);}bool passFilter(dtPolyRef,const dtMeshTile*,const dtPoly* p)const override{return p->getArea()>0&&(mask&CategoryBit(p->getArea()-1));}};
struct MeshProcess:dtTileCacheMeshProcess {void process(dtNavMeshCreateParams* p,unsigned char* a,unsigned short* f)override{for(int i=0;i<p->polyCount;++i){if(a[i]==63)a[i]=1;f[i]=1;}}};
struct Surface {
 SceneTransform frame;std::shared_ptr<const NavigationData> data;dtTileCacheAlloc alloc;NavigationCompressor compressor;MeshProcess process;
 dtNavMesh* mesh=dtAllocNavMesh();dtNavMeshQuery* query=dtAllocNavMeshQuery();dtTileCache* cache=dtAllocTileCache();
 struct Obstacle{dtObstacleRef ref=0;SceneTransform pose;NavigationObstacleSettings settings;};std::map<SceneObjectId,Obstacle> obstacles;
 ~Surface(){dtFreeTileCache(cache);dtFreeNavMeshQuery(query);dtFreeNavMesh(mesh);}
 glm::vec3 local(glm::vec3 p)const{return glm::inverse(frame.rotation)*(p-frame.position);}glm::vec3 world(glm::vec3 p)const{return frame.position+frame.rotation*p;}
 bool nearest(glm::vec3 point,float range,const Filter& f,dtPolyRef& ref,glm::vec3& result)const{glm::vec3 p=local(point),ext(range);return dtStatusSucceed(query->findNearestPoly(&p.x,&ext.x,&f,&ref,&result.x))&&ref;}
 NavigationPath path(glm::vec3 start,glm::vec3 end,const NavigationFilter& options)const{NavigationPath out;Filter f(options);dtPolyRef a=0,b=0;glm::vec3 p,q;if(!nearest(start,2,f,a,p)||!nearest(end,2,f,b,q))return out;dtPolyRef corridor[512];int n=0;auto status=query->findPath(a,b,&p.x,&q.x,&f,corridor,&n,512);if(dtStatusFailed(status)||!n)return out;out.status=(corridor[n-1]==b&&!dtStatusDetail(status,DT_BUFFER_TOO_SMALL))?NavigationPath::Status::Complete:NavigationPath::Status::Partial;if(corridor[n-1]!=b)query->closestPointOnPoly(corridor[n-1],&q.x,&q.x,nullptr);float points[512*3];unsigned char flags[512];dtPolyRef refs[512];int count=0;auto straight=query->findStraightPath(&p.x,&q.x,corridor,n,points,flags,refs,&count,512,DT_STRAIGHTPATH_ALL_CROSSINGS);if(dtStatusFailed(straight))return {};if(dtStatusDetail(straight,DT_BUFFER_TOO_SMALL))out.status=NavigationPath::Status::Partial;for(int i=0;i<count;++i){NavigationCorner c;c.position=world(glm::vec3(points[i*3],points[i*3+1],points[i*3+2]));if(i){float distance=glm::distance(out.corners.back().position,c.position);out.distance+=distance;const dtMeshTile* tile=nullptr;const dtPoly* poly=nullptr;out.cost+=distance*(refs[i-1]&&dtStatusSucceed(mesh->getTileAndPolyByRef(refs[i-1],&tile,&poly))?f.getAreaCost(poly->getArea()):1);}out.corners.push_back(c);}for(int i=0;i<n;++i){const dtMeshTile* t;const dtPoly* poly;if(dtStatusSucceed(mesh->getTileAndPolyByRef(corridor[i],&t,&poly))){unsigned area=poly->getArea()-1;if(std::find(out.areas.begin(),out.areas.end(),area)==out.areas.end())out.areas.push_back(area);}}return out;}
};
}
struct NavigationSystem::Impl {ProjectNavigation config;std::map<SceneObjectId,std::unique_ptr<Surface>> surfaces,staged;std::map<SceneObjectId,std::string> errors;std::map<SceneObjectId,NavigationAgentState> agents;std::map<SceneObjectId,SceneObject> links;std::set<SceneObjectId> pending;unsigned revision=1;dtObstacleAvoidanceQuery* avoidance=dtAllocObstacleAvoidanceQuery();Impl(ProjectNavigation p):config(std::move(p)){if(avoidance)avoidance->init(32,32);}~Impl(){dtFreeObstacleAvoidanceQuery(avoidance);}};
NavigationSystem::NavigationSystem(ProjectNavigation p):m(std::make_unique<Impl>(std::move(p))){}NavigationSystem::~NavigationSystem()=default;
const ProjectNavigation& NavigationSystem::Configuration()const{return m->config;}unsigned NavigationSystem::Revision()const{return m->revision;}const std::map<SceneObjectId,std::string>& NavigationSystem::Errors()const{return m->errors;}
bool NavigationSystem::LoadSurface(SceneObjectId id,const SceneTransform& pose,std::shared_ptr<const NavigationData> data,std::string& error,bool publish){auto s=std::make_unique<Surface>();s->frame=pose;s->data=data;if(!data||!s->mesh||!s->query||!s->cache){error="navigation allocation failed";return false;}const auto& a=data->settings;dtNavMeshParams np{};glm::vec3 origin=-a.halfExtents;std::memcpy(np.orig,&origin.x,12);np.tileWidth=np.tileHeight=a.tileSize*a.cellSize;np.maxTiles=std::max(32,static_cast<int>(data->layers.size())*4);np.maxPolys=2048;dtTileCacheParams cp{};std::memcpy(cp.orig,np.orig,12);cp.cs=a.cellSize;cp.ch=a.cellHeight;cp.width=cp.height=a.tileSize;cp.walkableHeight=data->profile.height;cp.walkableRadius=data->profile.radius;cp.walkableClimb=data->profile.climb;cp.maxSimplificationError=a.simplification;cp.maxTiles=np.maxTiles;cp.maxObstacles=256;
 if(dtStatusFailed(s->mesh->init(&np))||dtStatusFailed(s->query->init(s->mesh,4096))||dtStatusFailed(s->cache->init(&cp,&s->alloc,&s->compressor,&s->process))){error="invalid navigation cache parameters";return false;}for(auto& layer:data->layers){auto* bytes=static_cast<unsigned char*>(dtAlloc(layer.size(),DT_ALLOC_PERM));if(!bytes){error="navigation layer allocation failed";return false;}std::memcpy(bytes,layer.data(),layer.size());dtCompressedTileRef ref;if(dtStatusFailed(s->cache->addTile(bytes,layer.size(),DT_COMPRESSEDTILE_FREE_DATA,&ref))){dtFree(bytes);error="invalid navigation tile layer";return false;}if(dtStatusFailed(s->cache->buildNavMeshTile(ref,s->mesh))){error="cannot build runtime navigation tile";return false;}}if(publish){m->surfaces[id]=std::move(s);m->errors.erase(id);++m->revision;}else m->staged[id]=std::move(s);return true;}
void NavigationSystem::PublishSurfaces(const std::vector<SceneObjectId>& ids){for(auto id:ids)if(auto it=m->staged.find(id);it!=m->staged.end()){m->surfaces[id]=std::move(it->second);m->staged.erase(it);m->errors.erase(id);++m->revision;}}
void NavigationSystem::RemoveSurface(SceneObjectId id){m->staged.erase(id);bool removed=m->surfaces.erase(id)!=0;if(removed)++m->revision;m->errors.erase(id);if(removed)for(auto& [_,agent]:m->agents){agent.path={};agent.onLink=false;agent.steering={};agent.elapsed=1e10f;}}
std::optional<NavigationLocation> NavigationSystem::Sample(glm::vec3 p,float range,const NavigationFilter& f)const{
    JUDAS_PROFILE_SCOPE("Navigation position query");if(!(range>0)||!std::isfinite(range)||!std::isfinite(glm::dot(p,p)))return {};Filter filter(f);std::optional<NavigationLocation> best;float distance=range*range;for(auto& [id,s]:m->surfaces)if(s->data->settings.profile==f.profile){dtPolyRef ref;glm::vec3 result;if(s->nearest(p,range,filter,ref,result)){auto world=s->world(result);float d=glm::dot(p-world,p-world);if(d<=distance){const dtMeshTile* t;const dtPoly* poly;s->mesh->getTileAndPolyByRef(ref,&t,&poly);best=NavigationLocation{world,id,static_cast<unsigned>(poly->getArea()-1)};distance=d;}}}return best;}
NavigationPath NavigationSystem::FindPath(glm::vec3 start,glm::vec3 end,const NavigationFilter& f)const{
    JUDAS_PROFILE_SCOPE("Navigation path query");
 JUDAS_PROFILE_COUNTER("Navigation path requests",1,ProfileCounterMode::Sum);
 NavigationPath best;best.revision=m->revision;if(!std::isfinite(glm::dot(start,start))||!std::isfinite(glm::dot(end,end)))return best;for(auto& [id,s]:m->surfaces)if(s->data->settings.profile==f.profile){auto p=s->path(start,end,f);if(p.status==NavigationPath::Status::Complete&&(best.status!=p.status||p.cost<best.cost))best=std::move(p);else if(best.status==NavigationPath::Status::Failed&&p.status==NavigationPath::Status::Partial)best=std::move(p);}if(best.status==NavigationPath::Status::Complete){best.revision=m->revision;return best;}
 // Explicit endpoint graph: Detour supplies every on-surface segment. Links never move entities.
 struct Node{glm::vec3 point;SceneObjectId link=0;glm::vec3 end;unsigned area=0;};std::vector<Node> nodes{{start,0,{},0},{end,0,{},0}};for(auto& [id,o]:m->links){auto l=*o.navigationLink;if(!(f.include&~f.exclude&CategoryBit(l.area)))continue;auto a=o.transform.position+o.transform.rotation*l.start,b=o.transform.position+o.transform.rotation*l.end;if(!Sample(a,l.radius,f)||!Sample(b,l.radius,f))continue;nodes.push_back({a,id,b,l.area});if(l.bidirectional)nodes.push_back({b,id,a,l.area});}
 std::vector<float> dist(nodes.size(),1e30f);std::vector<bool> done(nodes.size());std::vector<NavigationPath> routes(nodes.size());dist[0]=0;
 for(size_t iteration=0;iteration<nodes.size();++iteration){size_t u=nodes.size();for(size_t i=0;i<nodes.size();++i)if(!done[i]&&(u==nodes.size()||dist[i]<dist[u]))u=i;if(u==nodes.size()||dist[u]>=1e30f)break;done[u]=true;if(u==1){routes[u].status=NavigationPath::Status::Complete;routes[u].revision=m->revision;return routes[u];}glm::vec3 from=u>1?nodes[u].end:nodes[u].point;
  for(size_t v=1;v<nodes.size();++v)if(!done[v]&&v!=u){NavigationPath segment;for(auto& [id,s]:m->surfaces)if(s->data->settings.profile==f.profile){auto p=s->path(from,nodes[v].point,f);if(p.status==NavigationPath::Status::Complete&&(segment.status!=p.status||p.cost<segment.cost))segment=std::move(p);}if(segment.status!=NavigationPath::Status::Complete)continue;float linkDistance=v>1?glm::distance(nodes[v].point,nodes[v].end):0;float cost=segment.cost+linkDistance*(f.costs.count(nodes[v].area)?f.costs.at(nodes[v].area):1);if(dist[u]+cost<dist[v]){dist[v]=dist[u]+cost;routes[v]=routes[u];routes[v].corners.insert(routes[v].corners.end(),segment.corners.begin(),segment.corners.end());routes[v].areas.insert(routes[v].areas.end(),segment.areas.begin(),segment.areas.end());routes[v].distance+=segment.distance+linkDistance;if(v>1){routes[v].corners.back().link=nodes[v].link;routes[v].corners.back().linkEnd=nodes[v].end;routes[v].areas.push_back(nodes[v].area);}}}
 }best.revision=m->revision;return best;
}
std::optional<NavigationLocation> NavigationSystem::Raycast(glm::vec3 a,glm::vec3 b,const NavigationFilter& options)const{
    JUDAS_PROFILE_SCOPE("Navigation ray query");if(!std::isfinite(glm::dot(a,a))||!std::isfinite(glm::dot(b,b)))return {};Filter f(options);for(auto& [id,s]:m->surfaces)if(s->data->settings.profile==options.profile){dtPolyRef ref;glm::vec3 p;if(!s->nearest(a,2,f,ref,p))continue;auto q=s->local(b);float t;glm::vec3 normal;dtPolyRef visited[256];int count;if(dtStatusSucceed(s->query->raycast(ref,&p.x,&q.x,&f,&t,&normal.x,visited,&count,256))){auto point=s->world(p+(q-p)*std::min(t,1.0f));unsigned area=0;if(count){const dtMeshTile* tile=nullptr;const dtPoly* poly=nullptr;if(dtStatusSucceed(s->mesh->getTileAndPolyByRef(visited[count-1],&tile,&poly)))area=poly->getArea()-1;}return NavigationLocation{point,id,area};}}return {};}
NavigationAgentState* NavigationSystem::Agent(SceneObjectId id){auto it=m->agents.find(id);return it==m->agents.end()?nullptr:&it->second;}const NavigationAgentState* NavigationSystem::Agent(SceneObjectId id)const{auto it=m->agents.find(id);return it==m->agents.end()?nullptr:&it->second;}
bool NavigationSystem::SetDestination(SceneObjectId id,glm::vec3 p){auto a=Agent(id);if(!a||!std::isfinite(glm::dot(p,p)))return false;a->hasDestination=true;a->destination=p;a->elapsed=1e10f;return true;}
void NavigationSystem::ClearDestination(SceneObjectId id){if(auto a=Agent(id)){a->hasDestination=false;a->steering={};a->path={};a->remaining=0;a->corner=0;a->onLink=false;}}
bool NavigationSystem::CompleteLink(SceneObjectId id){auto a=Agent(id);if(!a||!a->onLink)return false;a->onLink=false;++a->corner;return true;}
void NavigationSystem::Update(RuntimeWorld& world,float dt){
    JUDAS_PROFILE_SCOPE("Navigation update");auto objects=world.ScriptObjects();std::set<SceneObjectId> liveSurfaces,liveAgents,liveLinks;Scene geometry;geometry.Objects()=objects;
 for(auto& o:objects){if(o.navigationLink&&o.navigationLink->enabled){auto existing=m->links.find(o.id);if(existing==m->links.end()||NavigationProperties(existing->second)!=NavigationProperties(o)||existing->second.transform.position!=o.transform.position||existing->second.transform.rotation!=o.transform.rotation)++m->revision;m->links[o.id]=o;liveLinks.insert(o.id);}if(o.navigationAgent&&o.navigationAgent->enabled){m->agents.try_emplace(o.id);liveAgents.insert(o.id);}if(o.navigationSurface&&o.navigationSurface->enabled){liveSurfaces.insert(o.id);if(!m->surfaces.count(o.id)&&!m->errors.count(o.id)&&world.Resources()){
  std::string error;auto data=world.Resources()->GetNavigation(o.navigationSurface->asset,error);if(data){NavigationGeometry source;if(!CollectNavigationGeometry(geometry,o,m->config,source,error,world.Resources()->Assets())||source.fingerprint!=data->fingerprint){m->errors[o.id]="stale navigation bake: "+error;continue;}if(!LoadSurface(o.id,o.transform,data,error))m->errors[o.id]=error;}else if(error!="loading")m->errors[o.id]=error;
 }}}
 for(auto it=m->surfaces.begin();it!=m->surfaces.end();)if(!liveSurfaces.count(it->first)){it=m->surfaces.erase(it);++m->revision;}else ++it;
 for(auto it=m->agents.begin();it!=m->agents.end();)if(!liveAgents.count(it->first))it=m->agents.erase(it);else ++it;
 for(auto it=m->links.begin();it!=m->links.end();)if(!liveLinks.count(it->first)){it=m->links.erase(it);++m->revision;}else ++it;
 JUDAS_PROFILE_COUNTER("Navigation agents",double(m->agents.size()),ProfileCounterMode::Latest);
 for(auto& [id,s]:m->surfaces){JUDAS_PROFILE_SCOPE("Navigation obstacles and tile cache"); JUDAS_PROFILE_COUNTER("Navigation obstacle batches",1,ProfileCounterMode::Sum);std::set<SceneObjectId> present;for(auto& o:objects)if(o.navigationObstacle&&o.navigationObstacle->enabled){present.insert(o.id);auto p=o.transform;EntityPhysicalState state;if(world.GetEntityState(o.id,state)){p.position=state.position;p.rotation=state.rotation;}auto settings=*o.navigationObstacle;auto it=s->obstacles.find(o.id);if(it!=s->obstacles.end()&&glm::distance(p.position,it->second.pose.position)<settings.updateDistance&&std::abs(glm::dot(p.rotation,it->second.pose.rotation))>.9999f&&it->second.settings.enabled==settings.enabled&&it->second.settings.cylinder==settings.cylinder&&it->second.settings.halfExtents==settings.halfExtents&&it->second.settings.radius==settings.radius&&it->second.settings.height==settings.height)continue;if(it!=s->obstacles.end()){if(dtStatusFailed(s->cache->removeObstacle(it->second.ref)))continue;s->obstacles.erase(it);}dtObstacleRef ref=0;auto center=s->local(p.position);dtStatus status;if(settings.cylinder){center.y-=settings.height*.5f;status=s->cache->addObstacle(&center.x,settings.radius,settings.height,&ref);}else{auto rotation=glm::inverse(s->frame.rotation)*p.rotation;glm::vec3 h(0);for(int k=0;k<3;++k){glm::vec3 axis(0);axis[k]=settings.halfExtents[k];h+=glm::abs(rotation*axis);}auto lo=center-h,hi=center+h;status=s->cache->addBoxObstacle(&lo.x,&hi.x,&ref);}if(dtStatusSucceed(status)){s->obstacles[o.id]={ref,p,settings};++m->revision;}else m->errors[o.id]="tile cache obstacle queue/capacity exceeded";}
  for(auto it=s->obstacles.begin();it!=s->obstacles.end();)if(!present.count(it->first)&&dtStatusSucceed(s->cache->removeObstacle(it->second.ref))){it=s->obstacles.erase(it);++m->revision;}else ++it;
  bool ready=false;auto status=s->cache->update(dt,s->mesh,&ready);if(dtStatusFailed(status))m->errors[id]="tile cache update failed";if(!ready)m->pending.insert(id);else if(m->pending.erase(id))++m->revision;
 }
 for(auto& [id,a]:m->agents){const auto* o=world.RuntimeDefinition(id);if(!o||!o->navigationAgent)continue;auto cfg=*o->navigationAgent;auto position=o->transform.position;EntityPhysicalState state;if(world.GetEntityState(id,state))position=state.position;auto motor=world.RuntimeCharacter(id);if(motor)position=motor->position+motor->orientation*(motor->settings.offset-glm::vec3(0,motor->settings.halfHeight+motor->settings.radius,0));a.elapsed+=dt;a.steering={};if(!a.hasDestination||a.stopped)continue;
  NavigationFilter f{cfg.profile,cfg.areas,0,cfg.costs};
  // Track progress on the navigation surface, not vertical root/pivot distance.
  // This is a query projection only: physical poses remain entirely untouched.
  if(!a.onLink)if(auto location=Sample(position,2,f))position=location->position;
  if(!a.onLink&&a.elapsed>=cfg.repathSeconds&&(a.path.revision!=m->revision||a.elapsed>=cfg.repathSeconds)){a.path=FindPath(position,a.destination,f);a.corner=0;a.onLink=false;a.elapsed=0;}if(a.path.status==NavigationPath::Status::Failed){a.remaining=0;continue;}while(a.corner<a.path.corners.size()&&glm::distance(position,a.path.corners[a.corner].position)<=cfg.cornerDistance){if(a.path.corners[a.corner].link){a.onLink=true;break;}++a.corner;}a.remaining=0;glm::vec3 last=position;for(size_t i=a.corner;i<a.path.corners.size();++i){a.remaining+=glm::distance(last,a.path.corners[i].position);last=a.path.corners[i].position;}if(a.onLink||a.corner==a.path.corners.size()||glm::distance(position,a.destination)<=cfg.arrival)continue;auto direction=a.path.corners[a.corner].position-position;auto loc=Sample(position,2,f);auto surface=loc?m->surfaces.find(loc->surface):m->surfaces.end();if(surface==m->surfaces.end())continue;auto up=surface->second->frame.rotation*glm::vec3(0,1,0);direction-=up*glm::dot(direction,up);if(glm::dot(direction,direction)<1e-6f)continue;a.steering=glm::normalize(direction)*cfg.speed;
  if(cfg.avoidance&&m->avoidance){JUDAS_PROFILE_SCOPE("Navigation local avoidance");auto& s=*surface->second;auto local=s.local(position),desired=glm::inverse(s.frame.rotation)*a.steering;glm::vec3 velocity(0);if(motor)velocity=glm::inverse(s.frame.rotation)*motor->velocity;m->avoidance->reset();int count=0;for(auto& [other,b]:m->agents)if(other!=id&&count<32){auto* def=world.RuntimeDefinition(other);if(!def)continue;auto pos=def->transform.position;if(auto c=world.RuntimeCharacter(other))pos=c->position+c->orientation*(c->settings.offset-glm::vec3(0,c->settings.halfHeight+c->settings.radius,0));auto p=s.local(pos);if(glm::dot(p-local,p-local)>36)continue;auto observed=b.steering;if(auto bodyMotor=world.RuntimeCharacter(other))observed=bodyMotor->velocity;else{EntityPhysicalState state;if(world.GetEntityState(other,state))observed=state.linearVelocity;}auto v=glm::inverse(s.frame.rotation)*observed;auto desiredOther=glm::inverse(s.frame.rotation)*b.steering;unsigned profile=def->navigationAgent?def->navigationAgent->profile:0;float radius=m->config.profiles.count(profile)?m->config.profiles.at(profile).radius:.3f;m->avoidance->addCircle(&p.x,radius,&v.x,&desiredOther.x);++count;}Filter filter(f);dtPolyRef ref=0;glm::vec3 nearest;if(s.nearest(position,2,filter,ref,nearest)){float segments[6*DT_VERTS_PER_POLYGON];int count=0;if(dtStatusSucceed(s.query->getPolyWallSegments(ref,&filter,segments,nullptr,&count,DT_VERTS_PER_POLYGON)))for(int i=0;i<count;++i)m->avoidance->addSegment(segments+i*6,segments+i*6+3);}
  dtObstacleAvoidanceParams params{};params.velBias=.4f;params.weightDesVel=2;params.weightCurVel=.75f;params.weightSide=.75f;params.weightToi=2.5f;params.horizTime=2.5f;params.adaptiveDivs=5;params.adaptiveRings=2;params.adaptiveDepth=3;float result[3];m->avoidance->sampleVelocityAdaptive(&local.x,(m->config.profiles.count(cfg.profile)?m->config.profiles.at(cfg.profile).radius:.3f),cfg.speed,&velocity.x,&desired.x,result,&params);a.steering=s.frame.rotation*glm::vec3(result[0],0,result[2]);}
 }
}
void NavigationSystem::Debug(DebugLineList& lines)const{for(auto& [id,s]:m->surfaces)for(int i=0;i<s->mesh->getMaxTiles();++i){const auto* t=static_cast<const dtNavMesh*>(s->mesh)->getTile(i);if(!t||!t->header)continue;for(int j=0;j<t->header->polyCount;++j){auto& p=t->polys[j];for(int k=0;k<p.vertCount;++k){auto a=t->verts+p.verts[k]*3,b=t->verts+p.verts[(k+1)%p.vertCount]*3;lines.Line(s->world({a[0],a[1],a[2]}),s->world({b[0],b[1],b[2]}),p.getArea()==1?glm::vec3(.1f,.8f,.7f):glm::vec3(.8f,.4f,.9f));}}}for(auto& [id,o]:m->links){const auto& link=*o.navigationLink;auto start=o.transform.position+o.transform.rotation*link.start,end=o.transform.position+o.transform.rotation*link.end;lines.Line(start,end,{.8f,.4f,1});glm::vec3 up=o.transform.rotation*glm::vec3(0,.5f,0);lines.Line(start,start+up,{.8f,.4f,1});lines.Line(end,end+up,{.8f,.4f,1});}for(auto& [id,a]:m->agents)for(size_t i=1;i<a.path.corners.size();++i)lines.Line(a.path.corners[i-1].position,a.path.corners[i].position,{1,.8f,.1f});}

void NavigationSystem::RegisterAgent(SceneObjectId id){m->agents.try_emplace(id);}

NavigationStatistics NavigationSystem::Statistics()const{NavigationStatistics stats;stats.surfaces=m->surfaces.size();stats.agents=m->agents.size();for(const auto& [id,s]:m->surfaces){stats.obstacles+=s->obstacles.size();for(int i=0;i<s->mesh->getMaxTiles();++i){const auto* tile=static_cast<const dtNavMesh*>(s->mesh)->getTile(i);if(tile&&tile->header){++stats.tiles;stats.polygons+=tile->header->polyCount;}}}return stats;}
