// FTFT9 controller contract tests. Samples here are explicit continuum input,
// not acceptance evidence for particle-field reconstruction; the ordinary
// runtime fluid/body/player fixtures independently exercise that input path.
#include <chrono>
#include <cmath>
#include <iomanip>
#include <iostream>
#include <limits>
#include <stdexcept>
#include <string>
#include <glm/gtc/quaternion.hpp>
#include "PlayerController.h"
#include "UniformGravity.h"
#include "Window.h"
namespace {
int checks=0,failures=0,steps=0;
constexpr float dt=1.0f/60.0f;
void Check(bool value,const std::string& label){++checks;failures+=!value;if(!value)std::cerr<<"FAIL "<<label<<'\n';}
void Near(glm::vec3 actual,glm::dvec3 expected,double tolerance,const std::string& label){const double error=glm::length(glm::dvec3(actual)-expected);Check(std::isfinite(error)&&error<=tolerance,label);std::cout<<std::setprecision(17)<<"VECTOR "<<label<<" actual="<<actual.x<<','<<actual.y<<','<<actual.z<<" expected="<<expected.x<<','<<expected.y<<','<<expected.z<<" error="<<error<<" tolerance="<<tolerance<<'\n';}
struct Fixture{PhysicsWorld physics;PlayerController player{{0,0,0},0};Window window;Fixture(){Check(physics.Init(),"physics init");Check(player.Spawn(physics),"query-only player shape");window.SetTestInputMode(true);}~Fixture(){player.Destroy(physics);physics.Shutdown();}
void Step(const GravityField& gravity,int count=1,bool input=true){for(int i=0;i<count;++i){player.UpdateFrameInput(window);physics.Step(dt);player.FixedUpdate(window,physics,gravity,dt,input);++steps;}}};
void Density(){const glm::quat q=glm::angleAxis(.83f,glm::normalize(glm::vec3(1,-2,3)));for(bool rotated:{false,true})for(float density:{500.f,1000.f,2000.f}){Fixture f;const glm::vec3 g=rotated?q*glm::vec3(0,-9.81f,0):glm::vec3(0,-9.81f,0);UniformGravity gravity(g);f.player.SetFluidParameters(density,0,4);f.player.SetFluidSample({1,1000,{0,0,0},{0,0,0}});f.Step(gravity,120);
const glm::dvec3 a=glm::dvec3(g)*(1.-1000./double(density));const std::string label=(rotated?"rotated-":"identity-")+std::to_string(int(density));Near(f.player.GetVelocity(),a*(120.*double(dt)),4e-5,label+" density acceleration");Near(f.player.GetPosition(),a*(double(dt)*double(dt)*120.*121./2.),8e-5,label+" physical drift");Check(f.physics.AliveBodies().empty(),label+" player is never a rigid body");}}
void NeutralAndFreefall(){UniformGravity g({0,-9.81f,0});for(float density:{500.f,1000.f,2000.f}){Fixture f;f.player.SetFluidParameters(density,2,4);glm::vec3 expected(0);for(int i=0;i<240;++i){expected+=glm::vec3(0,-9.81f,0)*dt;f.player.SetFluidSample({1,1000,expected,{0,-9.81f,0}});f.Step(g);}Near(f.player.GetVelocity(),glm::dvec3(expected),5e-5,"common free fall density "+std::to_string(density));}
Fixture neutral;neutral.player.SetFluidParameters(1000,2,4);neutral.player.SetFluidSample({1,1000,{0,0,0},{0,0,0}});neutral.Step(g,240);Near(neutral.player.GetPosition(),{0,0,0},0,"neutral immersed has no secular drift");Near(neutral.player.GetVelocity(),{0,0,0},0,"neutral immersed has no acceleration");
for(float density:{500.f,1000.f,2000.f}){Fixture zero;zero.player.SetFluidParameters(density,2,4);zero.player.SetFluidSample({1,1000,{0,0,0},{0,0,0}});zero.Step(UniformGravity({0,0,0}),120);Near(zero.player.GetPosition(),{0,0,0},0,"zero gravity invents no buoyancy "+std::to_string(density));}}
void Drag(){Fixture f;const glm::vec3 before(3,-2,1),water(.4f,.2f,-.1f);f.player.SetVelocityAfterRelease(before);f.player.SetFluidParameters(1000,2,4);f.player.SetFluidSample({.4f,1000,water,{0,0,0}});f.Step(UniformGravity({0,0,0}),120);const double factor=std::exp(-2.*double(.4f)*double(dt)*120.);Near(f.player.GetVelocity(),glm::dvec3(water)+(glm::dvec3(before)-glm::dvec3(water))*factor,8e-6,"relative drag exponential oracle");Check(glm::length(f.player.GetVelocity()-water)<glm::length(before-water),"drag dissipates relative kinetic energy");
Fixture stiff;stiff.player.SetFluidParameters(1000,1e6f,4);stiff.player.SetVelocityAfterRelease(before);stiff.player.SetFluidSample({1,1000,water,{0,0,0}});stiff.Step(UniformGravity({0,0,0}));Near(stiff.player.GetVelocity(),glm::dvec3(water),0,"large configured drag cannot overshoot fluid velocity");}
void Swim(){for(bool diagonal:{false,true}){Fixture f;f.player.SetFluidParameters(1000,0,4);f.player.SetFluidSample({1,1000,{0,0,0},{0,0,0}});f.window.QueueTestMouseDelta(-300,-200);f.player.UpdateFrameInput(f.window);f.window.SetTestActionState(Action::MoveForward,true);if(diagonal){f.window.SetTestActionState(Action::MoveUp,true);f.window.SetTestActionState(Action::StrafeRight,true);}const glm::vec3 look=f.player.GetLookDirection();f.Step(UniformGravity({0,0,0}),60);if(!diagonal)Near(f.player.GetVelocity(),glm::dvec3(look)*(4.*double(dt)*60.),5e-6,"full look pitch drives swimming");Check(glm::length(f.player.GetVelocity())<=4.*double(dt)*60.+5e-6,"combined swim intent bounded by authored propulsion");Check(f.player.GetPosition().y>.5f,"look/up propulsion has vertical movement without particle push");}
Fixture jump;jump.player.SetFluidParameters(1000,0,4);jump.player.SetFluidSample({1,1000,{0,0,0},{0,0,0}});jump.window.RequestTestJump();jump.Step(UniformGravity({0,0,0}));Near(jump.player.GetVelocity(),{0,4.*double(dt),0},1e-7,"jump input supplies bounded swim pulse");
Fixture disabled;disabled.player.SetFluidParameters(1000,0,4);disabled.player.SetFluidSample({1,1000,{0,0,0},{0,0,0}});disabled.window.SetTestActionState(Action::MoveUp,true);disabled.window.RequestTestJump();disabled.Step(UniformGravity({0,0,0}),1,false);Near(disabled.player.GetVelocity(),{0,0,0},0,"disabled input produces no swim propulsion");}
void EnterAndLeave(){Fixture f;UniformGravity g({0,-9.81f,0});f.player.SetFluidParameters(1000,2,4);f.Step(g,10);const float entered=f.player.GetPosition().y;Check(entered<0,"dry entry falls normally");f.player.SetFluidSample({1,1000,{0,0,0},{0,0,0}});f.window.SetTestActionState(Action::MoveUp,true);f.Step(g,180);Check(f.player.GetPosition().y>entered+2,"immersed propulsion moves against gravity without particle contacts");const auto wet=f.player.GetVelocity();f.player.SetFluidSample({});f.window.SetTestActionState(Action::MoveUp,false);f.Step(g);Near(f.player.GetVelocity(),glm::dvec3(wet)+glm::dvec3(0,-9.81f,0)*double(dt),3e-7,"leaving fluid restores dry gravity without stale drag");f.player.Reset();Check(f.player.GetFluidSample().immersion==0&&f.player.Density()==1000,"reset clears transient field while retaining authored density");
Fixture floor;floor.physics.CreateStaticBox({0,-1,0},{3,.1f,3},0,0);floor.player.SetFluidParameters(1000,0,4);floor.player.SetFluidSample({1,1000,{0,0,0},{0,0,0}});floor.window.RequestTestJump();floor.Step(g);Near(floor.player.GetVelocity(),{0,4.*double(dt),0},3e-7,"fully submerged supported jump is propulsion not a hidden launch");}
void Validation(){Fixture f;bool caught=false;try{f.player.SetFluidParameters(0,2,4);}catch(const std::invalid_argument&){caught=true;}Check(caught,"invalid player density rejected");caught=false;try{f.player.SetFluidSample({1.1f,1000,{0,0,0},{0,0,0}});}catch(const std::invalid_argument&){caught=true;}Check(caught,"invalid immersion rejected rather than clamped");caught=false;try{f.player.SetFluidSample({1,1000,{std::numeric_limits<float>::infinity(),0,0},{0,0,0}});}catch(const std::invalid_argument&){caught=true;}Check(caught,"nonfinite liquid field rejected");f.player.SetFluidSample({1,1000,{0,0,0},{0,0,0}});f.player.FixedUpdateAttached({2,3,4},glm::quat(1,0,0,0));Check(f.player.GetFluidSample().immersion==0,"secured attachment discards transient independent fluid response");}
}
int main(){const auto start=std::chrono::steady_clock::now();Density();NeutralAndFreefall();Drag();Swim();EnterAndLeave();Validation();const double seconds=std::chrono::duration<double>(std::chrono::steady_clock::now()-start).count();std::cout<<"{\"checks\":"<<checks<<",\"failures\":"<<failures<<",\"steps\":"<<steps<<",\"seconds\":"<<seconds<<",\"pass\":"<<(failures?"false":"true")<<"}\n";return failures?1:0;}
